alias: get-preprocessed-dataset-kits19
uid: 2094d9b9ab6c4c9e
automation_alias: script
automation_uid: 5b4e0237da074764

# Metadata
category: AI/ML datasets
tags:
- get
- dataset
- medical-imaging
- kits19
- preprocessed

# Cache
cache: true

# Environment
default_env:
  MLC_DATASET: kits19
  MLC_DATASET_DTYPE: fp32
new_env_keys:
- MLC_DATASET_*

# Input mapping
input_mapping:
  dir: MLC_DATASET_PREPROCESSED_PATH
  threads: MLC_NUM_PREPROCESS_THREADS

# Dependencies
deps:
- names:
  - python3
  - python
  tags: get,python3
- names:
  - original-dataset
  tags: get,dataset,medical-imaging,kits19,original
- names:
  - inference-src
  tags: mlperf,mlcommons,inference,source,src
- tags: get,generic-python-lib,_scipy
- tags: get,generic-python-lib,_nibabel
- names:
  - numpy
  tags: get,generic-python-lib,_numpy

# Variations
variations:
  '1':
    adr:
      original-dataset:
        tags: _1
    env:
      MLC_DATASET_SIZE: '1'
    group: dataset-count
  '5':
    adr:
      original-dataset:
        tags: _5
    env:
      MLC_DATASET_SIZE: '5'
    group: dataset-count
  '50':
    adr:
      original-dataset:
        tags: _50
    env:
      MLC_DATASET_SIZE: '50'
    group: dataset-count
  '500':
    adr:
      original-dataset:
        tags: _500
    env:
      MLC_DATASET_SIZE: '500'
    group: dataset-count
  full:
    adr:
      original-dataset:
        tags: _full
    env:
      MLC_DATASET_SIZE: ''
    group: dataset-count
  fp32:
    default: true
    env:
      MLC_DATASET_DTYPE: fp32
    group: dataset-precision
  int8:
    env:
      MLC_DATASET_DTYPE: int8
    group: dataset-precision
  calibration:
    add_deps:
      original-dataset:
        tags: _calibration
    env:
      MLC_DATASET_PATH: <<<MLC_CALIBRATION_DATASET_PATH>>>
    group: dataset-type
  validation:
    add_deps:
      original-dataset:
        tags: _validation
    default: true
    group: dataset-type
  nvidia:
    env:
      MLC_PREPROCESSING_BY_NVIDIA: 'yes'
