alias: wrapper-reproduce-octoml-tinyml-submission
uid: b946001e289c4480
automation_alias: script
automation_uid: 5b4e0237da074764

# Metadata
category: TinyML automation
tags:
- run
- generate-tiny
- generate
- submission
- tiny
- generate-tiny-submission
- results
- mlcommons
- mlperf
- octoml

# Environment
env: {}

# Input mapping
input_mapping:
  flash: MLC_FLASH_BOARD
  recreate_binary: MLC_RECREATE_BINARY

# Dependencies
deps:
- names:
  - python
  - python3
  tags: get,python3

# Versions
default_version: r1.0
versions:
  r1.0: {}
