alias: get-mlperf-single-node-system-info
automation_alias: script
automation_uid: 5b4e0237da074764
cache: false
category: Platform information
deps:
- tags: detect,os
- tags: detect,cpu
- tags: get,cuda-devices
- skip_if_env:
    MLC_HOST_OS_TYPE:
    - windows
  tags: detect,sudo
- tags: get,python
  names:
  - python
  - python3
- tags: get,platform-details
  names:
  - platform-details
input_mapping:
  out_dir_path: MLC_SINGLE_NODE_SYSTEM_INFO_DIR_PATH
  out_file_name: MLC_SINGLE_NODE_SYSTEM_INFO_FILE_NAME
  node_id: MLC_SINGLE_NODE_SYSTEM_ID
tags:
- get
- mlperf
- single-node
- system-info
uid: fe91d73029c94ec1
variations:
  cuda:
    adr:
      platform-details:
        tags: _cuda