alias: get-docker
automation_alias: script
automation_uid: 5b4e0237da074764
cache: true
category: Detection or installation of tools and artifacts
deps:
- tags: detect,os
input_description: {}
input_mapping: {}
new_env_keys: [
  "MLC_DOCKER_VERSION",
  "MLC_CONTAINER_TOOL"
]
new_state_keys: []
post_deps: []
posthook_deps: []
prehook_deps: []
tags:
- get
- install
- docker
- engine
uid: 6192accce4234084
variations: {}
versions: {}
