alias: app-code-aster
uid: de8532232e543115
automation_alias: script
automation_uid: 5b4e0237da074764

# Metadata
category: HPC Application

tags:
- app
- code-aster
- hpc

# Cache
cache: true

# Environment
default_env: {}
new_env_keys:
- MLC_CODE_ASTER_SRC_PATH
- MLC_CODE_ASTER_INSTALL_PATH
- MLC_CODE_ASTER_BIN_PATH
- +PATH
new_state_keys: []

# Dependencies
deps:
- tags: detect,cpu
- env:
    MLC_GENERIC_SYS_UTIL_IGNORE_MISSING_PACKAGE: true
  tags: get,generic-sys-util,_build-essential
- tags: get,generic-sys-util,_gfortran
- tags: get,generic-sys-util,_liblapack-dev
- tags: get,generic-sys-util,_libopenblas-dev
- tags: get,generic-sys-util,_python3-dev
- tags: get,generic-sys-util,_cmake
- tags: get,git,repo
  names:
  - code-aster-repo
  extra_cache_tags: code-aster,repo,code-aster-repo
  env:
    MLC_GIT_CHECKOUT_PATH_ENV_NAME: MLC_CODE_ASTER_SRC_PATH
  force_env_keys:
  - MLC_GIT_*
  update_tags_from_env_with_prefix:
    _branch.:
    - MLC_GIT_CHECKOUT
    _repo.:
    - MLC_GIT_REPO_URL
    _tag.:
    - MLC_GIT_CHECKOUT_TAG
prehook_deps: []
posthook_deps: []
post_deps: []

# Variations
variations:
  repo.#:
    env:
      MLC_GIT_REPO_URL: '#'
    group: repo
  repo.official:
    default: true
    env:
      MLC_GIT_REPO_URL: https://gitlab.com/codeaster/src.git
    group: repo
  tag.#:
    env:
      MLC_GIT_CHECKOUT_TAG: '#'
    group: version
  branch.#:
    env:
      MLC_GIT_CHECKOUT: '#'
    group: version
  version.18.1.8:
    default: true
    group: version
    env:
      MLC_GIT_CHECKOUT_TAG: 18.1.8

# Tests
tests:
  run_inputs: []
