alias: extract-file
automation_alias: script
automation_uid: 5b4e0237da074764
cache: false
can_force_cache: true
category: DevOps automation
deps:
- tags: detect,os
- enable_if_env:
    MLC_HOST_OS_FLAVOR:
    - macos
  skip_if_any_env:
    MLC_EXTRACT_EXTRACTED_CHECKSUM:
    - 'off'
    MLC_EXTRACT_EXTRACTED_CHECKSUM_FILE:
    - 'off'
  tags: get,generic-sys-util,_md5sha1sum
input_description: {}
input_mapping:
  extra_folder: MLC_EXTRACT_TO_FOLDER
  extract_path: MLC_EXTRACT_PATH
  input: MLC_EXTRACT_FILEPATH
  to: MLC_EXTRACT_PATH
new_env_keys:
- MLC_EXTRACT_EXTRACTED_PATH
- MLC_EXTRACT_EXTRACTED_SUBDIR_PATH
- <<<MLC_EXTRACT_FINAL_ENV_NAME>>>
- MLC_GET_DEPENDENT_CACHED_PATH
new_state_keys: []
post_deps: []
posthook_deps: []
prehook_deps: []
tags:
- extract
- file
tags_help: extract file
uid: 3f0b76219d004817
variations:
  keep:
    group: keep
    default: true
    env:
      MLC_EXTRACT_REMOVE_EXTRACTED: 'no'
  remove-extracted:
    group: keep
    env:
      MLC_EXTRACT_REMOVE_EXTRACTED: 'yes'
  path.#:
    env:
      MLC_EXTRACT_FILEPATH: '#'
versions: {}
