alias: app-cloverleaf
uid: a7b4c5d6e8f9012b
automation_alias: script
automation_uid: 5b4e0237da074764

# Metadata
category: HPC Application
tags:
- app
- cloverleaf
- hpc

# Cache
cache: true

# Environment
default_env: {}
new_env_keys:
- MLC_CLOVERLEAF_SRC_PATH
- MLC_CLOVERLEAF_INSTALL_PATH
- MLC_CLOVERLEAF_BIN_PATH
- +PATH
new_state_keys: []

# Dependencies
deps:
- tags: detect,cpu
- tags: get,generic,sys-util,_libopenmpi-dev
- tags: get,generic,sys-util,_gfortran
  names:
  - gfortran
- tags: get,git,repo
  names:
  - cloverleaf-repo
  extra_cache_tags: cloverleaf,repo,cloverleaf-repo
  env:
    MLC_GIT_CHECKOUT_PATH_ENV_NAME: MLC_CLOVERLEAF_SRC_PATH
  force_env_keys:
  - MLC_GIT_*
  update_tags_from_env_with_prefix:
    _branch.:
    - MLC_GIT_CHECKOUT
    _repo.:
    - MLC_GIT_REPO_URL
    _tag.:
    - MLC_GIT_CHECKOUT_TAG
prehook_deps: []
posthook_deps: []
post_deps: []

# Variations
variations:
  repo.#:
    env:
      MLC_GIT_REPO_URL: '#'
    group: repo
  repo.official:
    default: true
    env:
      MLC_GIT_REPO_URL: https://github.com/UK-MAC/CloverLeaf_ref.git
    group: repo
  tag.#:
    env:
      MLC_GIT_CHECKOUT_TAG: '#'
    group: version
  version.1.1:
    group: version
    env:
      MLC_GIT_CHECKOUT_TAG: v1.1
  version.1.3:
    default: true
    group: version
    env:
      MLC_GIT_CHECKOUT_TAG: v1.3
  branch.#:
    env:
      MLC_GIT_CHECKOUT: '#'
  master:
    env:
      MLC_GIT_CHECKOUT: master

# Tests
tests:
  run_inputs:
  - variations_list:
    - repo.official
