alias: get-nvidia-mitten
automation_alias: script
automation_uid: 5b4e0237da074764
cache: true
category: MLPerf benchmark support
default_version: main
deps:
- tags: detect,os
- names:
  - python3
  - python
  tags: get,python3
- tags: get,generic-python-lib,_pycuda
  names:
    - pycuda
- env:
    MLC_GIT_CHECKOUT_PATH_ENV_NAME: MLC_NVIDIA_MITTEN_SRC
  extra_cache_tags: nvidia,mitten,src
  force_env_keys:
  - MLC_GIT_CHECKOUT
  - MLC_GIT_PATCH_FILEPATHS
  names:
  - nvidia-mitten-git-src
  tags: get,git,_repo.https://github.com/NVIDIA/mitten
extra_cache_tags_from_env:
- env: MLC_PYTHON_CACHE_TAGS
  prefix: python-
new_env_keys:
- MLC_NVIDIA_MITTEN*
tags:
- get
- nvidia
- mitten
- nvidia-mitten
uid: 1c045f2902374de9
variations:
  patched:
    group: numpy-patch
    default: true
    adr:
      nvidia-mitten-git-src:
        tags: _patch
    env: 
      MLC_GIT_PATCH_FILEPATHS: <<<MLC_TMP_CURRENT_SCRIPT_PATH>>>/patch/numpy-mitten-v5.0.patch
  default:
    group: numpy-patch
