alias: run-docker-container
uid: 1e0c884107514b46

automation_alias: script
automation_uid: 5b4e0237da074764

tags:
- run
- docker
- container

cache: false

category: Docker automation

default_env:
  MLC_DOCKER_DETACHED_MODE: 'yes'
  MLC_DOCKER_REUSE_EXISTING_CONTAINER: 'no'
  MLC_DOCKER_PRIVILEGED_MODE: 'no'
  MLC_PODMAN_MAP_USER_ID: 'no'

input_mapping:
  all_gpus: MLC_DOCKER_ADD_ALL_GPUS
  num_gpus: MLC_DOCKER_ADD_NUM_GPUS
  base: MLC_DOCKER_IMAGE_BASE
  cache: MLC_DOCKER_CACHE
  mlc_repo: MLC_MLOPS_REPO
  detached: MLC_DOCKER_DETACHED_MODE
  device: MLC_DOCKER_ADD_DEVICE
  docker_image_base: MLC_DOCKER_IMAGE_BASE
  docker_base_image: MLC_DOCKER_IMAGE_BASE
  base_image: MLC_DOCKER_IMAGE_BASE
  keep_detached: MLC_KEEP_DETACHED_CONTAINER
  docker_os: MLC_DOCKER_OS
  docker_os_version: MLC_DOCKER_OS_VERSION
  os: MLC_DOCKER_OS
  os_version: MLC_DOCKER_OS_VERSION
  extra_run_args: MLC_DOCKER_EXTRA_RUN_ARGS
  fake_run_option: MLC_DOCKER_FAKE_RUN_OPTION
  gh_token: MLC_GH_TOKEN
  image_name: MLC_DOCKER_IMAGE_NAME
  image_repo: MLC_DOCKER_IMAGE_REPO
  image_tag: MLC_DOCKER_IMAGE_TAG
  image_tag_extra: MLC_DOCKER_IMAGE_TAG_EXTRA
  interactive: MLC_DOCKER_INTERACTIVE_MODE
  it: MLC_DOCKER_INTERACTIVE
  mounts: MLC_DOCKER_VOLUME_MOUNTS
  pass_user_id: MLC_DOCKER_PASS_USER_ID
  pass_user_group: MLC_DOCKER_PASS_USER_GROUP
  port_maps: MLC_DOCKER_PORT_MAPS
  post_run_cmds: MLC_DOCKER_POST_RUN_COMMANDS
  pre_run_cmds: MLC_DOCKER_PRE_RUN_COMMANDS
  real_run: MLC_REAL_RUN
  recreate: MLC_DOCKER_IMAGE_RECREATE
  rebuild: MLC_DOCKER_IMAGE_RECREATE
  run_cmd: MLC_DOCKER_RUN_CMD
  run_cmd_extra: MLC_DOCKER_RUN_CMD_EXTRA
  save_script: MLC_DOCKER_SAVE_SCRIPT
  script_tags: MLC_DOCKER_RUN_SCRIPT_TAGS
  shm_size: MLC_DOCKER_SHM_SIZE

new_env_keys:
  - 'MLC_DOCKER_CONTAINER_ID'

deps:
  - tags: get,docker

prehook_deps:
- names:
  - build-docker-image
  skip_if_any_env:
    MLC_DOCKER_IMAGE_EXISTS:
    - 'yes'
    MLC_DOCKER_SKIP_BUILD:
    - 'yes'
    MLC_DOCKER_CONTAINER_ID:
    - on
  tags: build,docker,image
- tags: get,docker
