alias: get-mlperf-automotive-src
automation_alias: script
automation_uid: 5b4e0237da074764
cache: true
category: MLPerf benchmark support
default_env:
  MLC_GIT_CHECKOUT_FOLDER: automotive
  MLC_GIT_DEPTH: --depth 4
  MLC_GIT_PATCH: 'no'
  MLC_GIT_RECURSE_SUBMODULES: ''
default_version: master
deps:
- tags: detect,os
- names:
  - python
  - python3
  tags: get,python3
new_env_keys:
- MLC_MLPERF_INFERENCE_BEVFORMER_PATH
- MLC_MLPERF_INFERENCE_SSD_RESNET50_PATH
- MLC_MLPERF_INFERENCE_DEEPLABV3PLUS_PATH
- MLC_MLPERF_LAST_RELEASE
- MLC_MLPERF_INFERENCE_SOURCE
- MLC_MLPERF_INFERENCE_SOURCE_VERSION
- +PYTHONPATH
prehook_deps:
- env:
    MLC_GIT_CHECKOUT_PATH_ENV_NAME: MLC_MLPERF_INFERENCE_SOURCE
  extra_cache_tags: automotive,src
  force_env_keys:
  - MLC_GIT_*
  names:
  - automotive-git-repo
  tags: get,git,repo
  update_tags_from_env_with_prefix:
    _branch.:
    - MLC_GIT_CHECKOUT
    _repo.:
    - MLC_GIT_URL
    _sha.:
    - MLC_GIT_SHA
    _submodules.:
    - MLC_GIT_SUBMODULES
print_env_at_the_end:
  MLC_MLPERF_INFERENCE_SOURCE: Path to MLPerf automotive benchmark source
tags:
- get
- src
- source
- automotive
- automotive-src
- automotive-source
- mlperf
- mlcommons
uid: c3842e6e35d947ef
variations:
  branch.#:
    default_version: custom
    env:
      MLC_GIT_CHECKOUT: '#'
    group: checkout
  full-history:
    env:
      MLC_GIT_DEPTH: ''
    group: git-history
  no-recurse-submodules:
    env:
      MLC_GIT_RECURSE_SUBMODULES: ''
  patch:
    ad:
      automotive-git-repo:
        tags: _patch
    env:
      MLC_GIT_PATCH: 'yes'
  pybind:
    env:
      MLC_SUBMODULE_PYBIND: 'yes'
  recurse-submodules:
    env:
      MLC_GIT_RECURSE_SUBMODULES: ' --recurse-submodules'
  repo.#:
    env:
      MLC_GIT_URL: '#'
  sha.#:
    env:
      MLC_GIT_SHA: '#'
    group: checkout
  short-history:
    default: true
    env:
      MLC_GIT_DEPTH: --depth 10
    group: git-history
  submodules.#:
    env:
      MLC_GIT_SUBMODULES: '#'
versions:
  custom:
    env:
      MLC_MLPERF_LAST_RELEASE: v0.5
  master:
    env:
      MLC_MLPERF_LAST_RELEASE: v0.5
      MLC_TMP_GIT_CHECKOUT: master
