alias: get-brew
uid: 4a2c5eab1ccf484f
automation_alias: script
automation_uid: 5b4e0237da074764

# Metadata
category: Detection or installation of tools and artifacts
tags:
- get
- brew

# Cache
cache: false

# Environment
new_env_keys: []
new_state_keys: []

# Input mapping
input_mapping: {}
input_description: {}

# Dependencies
deps: []
prehook_deps: []
posthook_deps: []
post_deps: []

# Variations
variations: {}

# Versions
versions: {}
