alias: app-nektar
uid: 60ae8d37599e0bc1
automation_alias: script
automation_uid: 5b4e0237da074764

# Metadata
category: HPC Application

tags:
- app
- nektar
- hpc

# Cache
cache: true

# Environment
default_env: {}
new_env_keys:
- MLC_NEKTAR_SRC_PATH
- MLC_NEKTAR_INSTALL_PATH
- MLC_NEKTAR_BIN_PATH
- +PATH
new_state_keys: []

# Dependencies
deps:
- tags: detect,cpu
- env:
    MLC_GENERIC_SYS_UTIL_IGNORE_MISSING_PACKAGE: true
  tags: get,generic-sys-util,_build-essential
- tags: get,generic-sys-util,_cmake
- tags: get,generic-sys-util,_libboost-all-dev
- tags: get,generic-sys-util,_libfftw3-dev
- tags: get,generic-sys-util,_libtinyxml-dev
- tags: get,generic-sys-util,_liblapack-dev
- tags: get,generic-sys-util,_libopenblas-dev
- tags: get,generic-sys-util,_flex
- tags: get,generic-sys-util,_bison
- tags: get,git,repo
  names:
  - nektar-repo
  extra_cache_tags: nektar,repo,nektar-repo
  env:
    MLC_GIT_CHECKOUT_PATH_ENV_NAME: MLC_NEKTAR_SRC_PATH
  force_env_keys:
  - MLC_GIT_*
  update_tags_from_env_with_prefix:
    _branch.:
    - MLC_GIT_CHECKOUT
    _repo.:
    - MLC_GIT_REPO_URL
    _tag.:
    - MLC_GIT_CHECKOUT_TAG
prehook_deps: []
posthook_deps: []
post_deps: []

# Variations
variations:
  repo.#:
    env:
      MLC_GIT_REPO_URL: '#'
    group: repo
  repo.official:
    default: true
    env:
      MLC_GIT_REPO_URL: https://gitlab.nektar.info/nektar/nektar.git
    group: repo
  tag.#:
    env:
      MLC_GIT_CHECKOUT_TAG: '#'
    group: version
  branch.#:
    env:
      MLC_GIT_CHECKOUT: '#'
    group: version
  version.5.9.0:
    default: true
    group: version
    env:
      MLC_GIT_CHECKOUT_TAG: v5.9.0

# Tests
tests:
  run_inputs:
  - variations_list:
    - repo.official
