alias: get-gcc
uid: dbf4ab5cbed74372
automation_alias: script
automation_uid: 5b4e0237da074764

# Metadata
name: Detect or install GCC compiler
category: Compiler automation
tags:
- get
- gcc
- compiler
- c-compiler
- cpp-compiler
- get-gcc

# Cache
cache: true
clean_files: []

# Environment
new_env_keys:
- MLC_GCC_*
- MLC_C_COMPILER_*
- MLC_CXX_COMPILER_*
- MLC_COMPILER_*
- MLC_LINKER_*
- + CFLAGS
- + CXXFLAGS
- + FFLAGS
- + LDFLAGS
- +MLC_HOST_OS_DEFAULT_INCLUDE_PATH
- +PATH

# Dependencies
deps:
- tags: detect,os
post_deps:
- tags: get,compiler-flags

# Variations
variations:
  version.#:
    group: version
  path.#:
    env:
      MLC_GCC_DIR_PATH: '#'
      MLC_TMP_GCC_FORCE_GIVEN_PATH: 'yes'

# Output / debugging
sort: 500
