alias: get-gcc
automation_alias: script
automation_uid: 5b4e0237da074764
cache: true
category: Compiler automation
clean_files: []
deps:
- tags: detect,os
name: Detect or install GCC compiler
new_env_keys:
- MLC_GCC_*
- MLC_C_COMPILER_*
- MLC_CXX_COMPILER_*
- MLC_COMPILER_*
- MLC_LINKER_*
- + CFLAGS
- + CXXFLAGS
- + FFLAGS
- + LDFLAGS
- +MLC_HOST_OS_DEFAULT_INCLUDE_PATH
- +PATH
post_deps:
- tags: get,compiler-flags
sort: 500
tags:
- get
- gcc
- compiler
- c-compiler
- cpp-compiler
- get-gcc
uid: dbf4ab5cbed74372
variations:
  path.#:
    env:
      MLC_GCC_DIR_PATH: '#'
