alias: get-nvidia-docker
uid: 465ae240998e4779
automation_alias: script
automation_uid: 5b4e0237da074764

# Metadata
category: Detection or installation of tools and artifacts
tags:
- get
- install
- nvidia
- nvidia-container-toolkit
- nvidia-docker
- engine

# Cache
cache: true

# Environment
new_env_keys: []
new_state_keys: []

# Input mapping
input_mapping: {}
input_description: {}

# Dependencies
deps:
- tags: detect,os
- tags: get,docker
prehook_deps: []
posthook_deps: []
post_deps: []

# Variations
variations: {}

# Versions
versions: {}
