from setuptools import setup
from setuptools.command.build_py import build_py
import json
import os
import shutil
import subprocess

try:
    import tomllib  # For Python 3.11+
except ImportError:
    import toml  # For older Python versions (requires `pip install toml`)


HERE = os.path.dirname(os.path.abspath(__file__))

# Directory the script content is shipped under inside the wheel. mlcflow
# resolves this from the running interpreter and registers it as an ordinary
# non-git repo, so the name is a contract between the two projects.
PACKAGE_REPO_MODULE = "mlc_scripts"


def get_project_meta(file_path="pyproject.toml"):
    """
    Extracts project metadata from the given pyproject.toml file.

    Args:
        file_path (str): Path to the pyproject.toml file.

    Returns:
        dict: Dictionary containing the project metadata.
    """
    try:
        with open(file_path, "r") as f:
            content_tmp = f.read()
            if 'tomllib' in globals():
                # Use tomllib for Python 3.11+
                project_data = tomllib.loads(content_tmp)
            else:
                # Use toml for older versions
                project_data = toml.loads(content_tmp)

        # Extract metadata under [project]
        project_meta = project_data.get("project", {})
        return project_meta

    except FileNotFoundError:
        raise FileNotFoundError(f"Error: {file_path} not found.")
    except Exception as e:
        raise RuntimeError(f"Error reading {file_path}: {e}")
    return {}


def read_file(file_name, default=""):
    if os.path.isfile(file_name):
        with open(file_name, "r", encoding="utf-8") as f:
            return f.read().strip()
    return default


def get_commit_hash():
    """The commit this wheel is actually built from.

    Ask git first. git_commit_hash.txt is only regenerated by
    build_wheel_off.yml, which no longer runs, so it has been frozen since
    2025-02-09 — every wheel published since has carried that same stale
    hash in its provenance, which is the one field whose job is to tell a
    tester what they are running.

    The file stays as the fallback for builds from an sdist, where there is
    no git metadata to ask. A dirty tree is marked, since such a wheel is
    not reproducible from the commit alone.
    """
    try:
        commit = subprocess.run(
            ["git", "-C", HERE, "rev-parse", "HEAD"],
            capture_output=True, text=True, check=True).stdout.strip()
        if commit:
            dirty = subprocess.run(
                ["git", "-C", HERE, "status", "--porcelain",
                 "--untracked-files=no"],
                capture_output=True, text=True, check=True).stdout.strip()
            return f"{commit}+dirty" if dirty else commit
    except (subprocess.SubprocessError, FileNotFoundError, OSError):
        pass

    try:
        with open(os.path.join(HERE, 'git_commit_hash.txt'), 'r') as f:
            return f.read().strip()
    except FileNotFoundError:
        return "unknown"


class BuildPyWithScriptContent(build_py):
    """Copy the script content into the wheel.

    The scripts used to arrive through a post-install `git clone` hooked onto
    setup.py's install command. Modern pip never runs that command - it builds
    a wheel and installs the wheel - so the hook fired at most once per
    machine, into the *builder's* home, and never at all once pip had cached
    the wheel. Shipping the content as the package payload removes the second
    step entirely.

    meta.yaml is rewritten with `git: false`: once installed there is no
    checkout, and recording otherwise would make `mlc pull repo` try to
    git-pull inside site-packages.
    """

    def run(self):
        super().run()

        target = os.path.join(self.build_lib, PACKAGE_REPO_MODULE)
        os.makedirs(target, exist_ok=True)

        self._write_meta(target)
        self._copy_scripts(target)
        self._write_provenance(target)

    def _write_meta(self, target):
        src = os.path.join(HERE, "meta.yaml")
        if not os.path.isfile(src):
            raise RuntimeError(
                "meta.yaml not found at the repo root; the wheel would have no repo identity.")

        with open(src, "r", encoding="utf-8") as f:
            lines = f.read().splitlines()

        out, replaced = [], False
        for line in lines:
            if line.strip().startswith("git:"):
                out.append("git: false")
                replaced = True
            else:
                out.append(line)
        if not replaced:
            out.append("git: false")

        with open(os.path.join(target, "meta.yaml"), "w", encoding="utf-8") as f:
            f.write("\n".join(out) + "\n")

    def _copy_scripts(self, target):
        src = os.path.join(HERE, "script")
        if not os.path.isdir(src):
            raise RuntimeError(
                "script/ not found at the repo root; the wheel would ship no content.")

        dst = os.path.join(target, "script")
        if os.path.isdir(dst):
            shutil.rmtree(dst)
        # by-category/ is a presentational tree of relative symlinks into the
        # real script directories. mlcflow never indexes it - _index_single_repo
        # walks script/*/ and skips anything without a meta file - so copying
        # it would only duplicate every script in the wheel, and one of its
        # links is already dangling.
        shutil.copytree(
            src, dst,
            symlinks=False,
            ignore_dangling_symlinks=True,
            ignore=shutil.ignore_patterns(
                "by-category", "__pycache__", "*.pyc", ".git", ".pytest_cache"))

    def _write_provenance(self, target):
        provenance = {
            "version": read_file(os.path.join(HERE, "VERSION"), default="0.0.1"),
            "commit": get_commit_hash(),
            "source": "https://github.com/mlcommons/mlperf-automations",
        }
        with open(os.path.join(target, ".mlc-provenance.json"), "w", encoding="utf-8") as f:
            json.dump(provenance, f, indent=2)


# Get project metadata from pyproject.toml
project_meta = get_project_meta()

# Read version from the VERSION file
version = read_file("VERSION", default="0.0.1")

setup(

    name=project_meta.get("name", "mlperf"),
    version=version,
    description=project_meta.get("description", "MLPerf Automations."),
    author=", ".join(a.get("name", "")
                     for a in project_meta.get("authors", [])),
    author_email=", ".join(a.get("email", "")
                           for a in project_meta.get("authors", [])),
    # ONLY the script payload. find_packages() would also sweep this repo's
    # automation/ directory into a generic top-level `automation` package -
    # the exact path mlcflow installs its own bundled engine to. mlc-scripts
    # installs after mlcflow (dependency ordering), so it would overwrite the
    # engine, and `pip uninstall mlc-scripts` would then delete files
    # mlcflow's RECORD also claims and leave mlcflow unable to start.
    # automation/ stays in the git checkout for pre-bundling mlcflow
    # releases; it has never belonged in the wheel.
    packages=[PACKAGE_REPO_MODULE],
    install_requires=project_meta.get("dependencies", []),
    python_requires=project_meta.get("python-requires", ">=3.8"),
    cmdclass={
        'build_py': BuildPyWithScriptContent,
    },
)
