alias: get-lib-mimalloc
automation_alias: script
automation_uid: 5b4e0237da074764
cache: true
category: Detection or installation of tools and artifacts
deps:
- env:
    MLC_GIT_CHECKOUT_PATH_ENV_NAME: MLC_MIMALLOC_SRC_PATH
  extra_cache_tags: mimalloc,repo,mimalloc-repo
  force_env_keys:
  - MLC_GIT_*
  names:
  - mimalloc-repo
  tags: get,git,repo
  update_tags_from_env_with_prefix:
    _branch.:
    - MLC_GIT_CHECKOUT
    _repo.:
    - MLC_GIT_URL
    _sha.:
    - MLC_GIT_SHA
    _submodules.:
    - MLC_GIT_SUBMODULES
- tags: get,cmake
- env:
    MLC_GENERIC_SYS_UTIL_IGNORE_MISSING_PACKAGE: true
  tags: get,generic-sys-util,_build-essential
new_env_keys:
- MLC_MIMALLOC_PATH
- MLC_MIMALLOC_LIB_PATH
- +LD_LIBRARY_PATH
new_state_keys: []
post_deps: []
posthook_deps: []
prehook_deps: []
tags:
- get-lib-mimalloc
- get
- lib
- mimalloc
tests:
  run_inputs:
  - variations_list:
    - branch.main
uid: 81d0dc1269fe41cc
variations:
  branch.#:
    env:
      MLC_GIT_CHECKOUT: '#'
  config.#:
    env:
      MLC_MIMALLOC_CONFIG: '#'
  sha.#:
    env:
      MLC_GIT_SHA: '#'
  url.#:
    env:
      MLC_GIT_URL: '#'
    group: version
  url.official:
    default: true
    env:
      MLC_GIT_URL: https://github.com/microsoft/mimalloc.git
    group: version
  version.official:
    base:
    - url.official
