alias: app-gizmo
uid: 3d985a98aab3e178
automation_alias: script
automation_uid: 5b4e0237da074764

# Metadata
category: HPC Application

tags:
- app
- gizmo
- hpc

# Cache
cache: true

# Environment
default_env: {}
new_env_keys:
- MLC_GIZMO_SRC_PATH
- MLC_GIZMO_INSTALL_PATH
- MLC_GIZMO_BIN_PATH
- +PATH
new_state_keys: []

# Dependencies
deps:
- tags: detect,cpu
- env:
    MLC_GENERIC_SYS_UTIL_IGNORE_MISSING_PACKAGE: true
  tags: get,generic-sys-util,_build-essential
- tags: get,generic-sys-util,_gfortran
- tags: get,generic-sys-util,_libgsl-dev
- tags: get,generic-sys-util,_libfftw3-dev
- tags: get,generic-sys-util,_libhdf5-dev
- tags: get,generic-sys-util,_libopenmpi-dev
- tags: get,git,repo
  names:
  - gizmo-repo
  extra_cache_tags: gizmo,repo,gizmo-repo
  env:
    MLC_GIT_CHECKOUT_PATH_ENV_NAME: MLC_GIZMO_SRC_PATH
  force_env_keys:
  - MLC_GIT_*
  update_tags_from_env_with_prefix:
    _branch.:
    - MLC_GIT_CHECKOUT
    _repo.:
    - MLC_GIT_REPO_URL
    _tag.:
    - MLC_GIT_CHECKOUT_TAG
prehook_deps: []
posthook_deps: []
post_deps: []

# Variations
variations:
  repo.#:
    env:
      MLC_GIT_REPO_URL: '#'
    group: repo
  repo.official:
    default: true
    env:
      MLC_GIT_REPO_URL: https://bitbucket.org/phopkins/gizmo-public.git
    group: repo
  tag.#:
    env:
      MLC_GIT_CHECKOUT_TAG: '#'
    group: version
  branch.#:
    env:
      MLC_GIT_CHECKOUT: '#'
    group: version
  branch.master:
    default: true
    group: version
    env:
      MLC_GIT_CHECKOUT: master

# Tests
tests:
  run_inputs: []
