alias: app-hmmer
uid: f6a3b4c5d7e8901a
automation_alias: script
automation_uid: 5b4e0237da074764
category: HPC Application
tags:
- app
- hmmer
- hpc
cache: true
new_env_keys:
- MLC_HMMER_SRC_PATH
- MLC_HMMER_INSTALL_PATH
- MLC_HMMER_BIN_PATH
- +PATH
new_state_keys: []
deps:
- tags: detect,cpu
- tags: get,generic,sys-util,_libopenmpi-dev
- tags: get,generic,sys-util,_autoconf
- tags: get,git,repo
  names:
  - hmmer-repo
  extra_cache_tags: hmmer,repo,hmmer-repo
  env:
    MLC_GIT_CHECKOUT_PATH_ENV_NAME: MLC_HMMER_SRC_PATH
  force_env_keys:
  - MLC_GIT_*
  update_tags_from_env_with_prefix:
    _branch.:
    - MLC_GIT_CHECKOUT
    _repo.:
    - MLC_GIT_REPO_URL
    _tag.:
    - MLC_GIT_CHECKOUT_TAG
prehook_deps: []
posthook_deps: []
post_deps: []
variations:
  repo.#:
    env:
      MLC_GIT_REPO_URL: '#'
    group: repo
  repo.official:
    default: true
    env:
      MLC_GIT_REPO_URL: https://github.com/EddyRivasLab/hmmer.git
    group: repo
  branch.#:
    env:
      MLC_GIT_CHECKOUT: '#'
  tag.#:
    env:
      MLC_GIT_CHECKOUT_TAG: '#'
    group: version
  version.3.4:
    default: true
    group: version
    env:
      MLC_GIT_CHECKOUT_TAG: hmmer-3.4
  version.3.3.2:
    group: version
    env:
      MLC_GIT_CHECKOUT_TAG: hmmer-3.3.2
  master:
    env:
      MLC_GIT_CHECKOUT: master
default_env: {}
tests:
  run_inputs:
  - variations_list:
    - repo.official
