alias: get-onnxruntime-prebuilt
automation_alias: script
automation_uid: 5b4e0237da074764
cache: true
category: AI/ML frameworks
clean_files: []
default_version: 1.20.1
deps:
- tags: detect,os
new_env_keys:
- MLC_ONNXRUNTIME_LIB_PATH
- MLC_ONNXRUNTIME_INCLUDE_PATH
- +PATH
- +C_INCLUDE_PATH
- +CPLUS_INCLUDE_PATH
- +LD_LIBRARY_PATH
- +DYLD_FALLBACK_LIBRARY_PATH
tags:
- install
- onnxruntime
- get
- prebuilt
- lib
- lang-c
- lang-cpp
uid: be02c84ff57c4244
variations:
  cpu:
    default: true
    env:
      MLC_ONNXRUNTIME_DEVICE: ''
    group: device
  cuda:
    env:
      MLC_ONNXRUNTIME_DEVICE: gpu
    group: device
