alias: get-ml-model-pointpillars
automation_alias: script
automation_uid: 5b4e0237da074764
cache: true
tags:
- get
- ml-model
- ml
- model
- pointpillars
uid: 3562621a8994411d
new_env_keys:
  - MLC_ML_MODEL_POINT_PILLARS_PATH
input_mapping:
  pp_path: MLC_ML_MODEL_POINT_PILLARS_PATH  
variations:
  gpu:
    default: true
    group: device
    env:
      MLC_ML_MODEL_PP_FORMAT: pth
  cpu:
    group: device
    env:
      MLC_ML_MODEL_PP_FORMAT: onnx
  
