alias: get-cache-dir
automation_alias: script
automation_uid: 5b4e0237da074764
cache: true
category: MLC Interface
deps: []
docker:
  run: false
input_description: {}
new_env_keys:
- MLC_CACHE_DIR
- <<<MLC_CACHE_DIR_ENV_NAME>>>
new_state_keys: []
post_deps: []
posthook_deps: []
prehook_deps: []
tags:
- get
- cache
- dir
- directory
uid: 48f4622e059b45ce
variations:
  name.#:
    env:
      MLC_CACHE_DIR_NAME: '#'
versions: {}
