alias: get-python3
automation_alias: script
automation_uid: 5b4e0237da074764
cache: true
category: Python automation
clean_files: []
extra_cache_tags_from_env:
- env: MLC_PYTHON_INSTALL_CACHE_TAGS
  prefix: python-
new_env_keys:
- MLC_PYTHON_*
- +LD_LIBRARY_PATH
- +C_INCLUDE_PATH
- +PATH
new_state_keys:
- script_prefix
prehook_deps:
- enable_if_env:
    MLC_REQUIRE_INSTALL:
    - 'yes'
  inherit_variation_tags: true
  reuse_version: true
  tags: install,python,src
tags:
- get
- python
- python3
- get-python
- get-python3
uid: d0b5dd74373f4a62
variations:
  conda.#:
    adr:
      pip-package:
        tags: _conda.#
    deps:
    - names:
      - conda-package
      - conda-python
      tags: get,generic,conda-package,_name.#,_package.python
    env:
      MLC_PYTHON_CONDA: 'yes'
      MLC_PYTHON_INSTALL_CACHE_TAGS: _conda.#
  custom-path.#:
    env:
      MLC_PYTHON_BIN_WITH_PATH: '#'
  lto: {}
  optimized: {}
  shared: {}
  with-custom-ssl: {}
  with-ssl: {}
