alias: app-vasp
uid: dae7f8a9b0c2345e
automation_alias: script
automation_uid: 5b4e0237da074764

# Metadata
category: HPC Application
tags:
- app
- vasp
- hpc

# Cache
cache: true

# Environment
default_env:
  MLC_VASP_SRC_PATH: ''
new_env_keys:
- MLC_VASP_SRC_PATH
- MLC_VASP_INSTALL_PATH
- MLC_VASP_BIN_PATH
- +PATH
- +LD_LIBRARY_PATH
new_state_keys: []

# Input mapping
input_mapping:
  vasp_src_path: MLC_VASP_SRC_PATH
input_description:
  vasp_src_path:
    desc: Path to VASP source directory (VASP requires a license)

# Dependencies
deps:
- tags: detect,cpu
- tags: get,generic,sys-util,_libopenmpi-dev
- tags: get,generic,sys-util,_gfortran
  names:
  - gfortran
- tags: get,generic,sys-util,_libfftw3-dev
- tags: get,generic,sys-util,_libhdf5-openmpi-dev
- tags: get,cmake
prehook_deps: []
posthook_deps: []
post_deps: []

# Variations
variations: {}

# Tests
tests:
  run_inputs: []
