alias: app-grid
uid: 7d96cf15f4f9b763
automation_alias: script
automation_uid: 5b4e0237da074764

# Metadata
category: HPC Application

tags:
- app
- grid
- hpc

# Cache
cache: true

# Environment
default_env: {}
new_env_keys:
- MLC_GRID_SRC_PATH
- MLC_GRID_INSTALL_PATH
- MLC_GRID_BIN_PATH
- +PATH
new_state_keys: []

# Dependencies
deps:
- tags: detect,cpu
- env:
    MLC_GENERIC_SYS_UTIL_IGNORE_MISSING_PACKAGE: true
  tags: get,generic-sys-util,_build-essential
- tags: get,generic-sys-util,_make
- tags: get,generic-sys-util,_autoconf
- tags: get,generic-sys-util,_automake
- tags: get,generic-sys-util,_libtool
- tags: get,generic-sys-util,_libgmp-dev
- tags: get,generic-sys-util,_libmpfr-dev
- tags: get,generic-sys-util,_zlib1g-dev
- tags: get,generic-sys-util,_wget
- tags: get,git,repo
  names:
  - grid-repo
  extra_cache_tags: grid,repo,grid-repo
  env:
    MLC_GIT_CHECKOUT_PATH_ENV_NAME: MLC_GRID_SRC_PATH
  force_env_keys:
  - MLC_GIT_*
  update_tags_from_env_with_prefix:
    _branch.:
    - MLC_GIT_CHECKOUT
    _repo.:
    - MLC_GIT_REPO_URL
    _tag.:
    - MLC_GIT_CHECKOUT_TAG
prehook_deps: []
posthook_deps: []
post_deps: []

# Variations
variations:
  repo.#:
    env:
      MLC_GIT_REPO_URL: '#'
    group: repo
  repo.official:
    default: true
    env:
      MLC_GIT_REPO_URL: https://github.com/paboyle/Grid.git
    group: repo
  tag.#:
    env:
      MLC_GIT_CHECKOUT_TAG: '#'
    group: version
  branch.#:
    env:
      MLC_GIT_CHECKOUT: '#'
    group: version
  version.0.8.0:
    default: true
    group: version
    env:
      MLC_GIT_CHECKOUT_TAG: v0.8.0

# Tests
tests:
  run_inputs:
  - variations_list:
    - repo.official
