alias: get-dlrm
uid: 63680ac2449a4241
automation_alias: script
automation_uid: 5b4e0237da074764

# Metadata
category: AI/ML models
tags:
- get
- src
- dlrm

# Cache
cache: true

# Environment
default_env:
  MLC_GIT_DEPTH: --depth 10
  MLC_GIT_PATCH: 'no'
  MLC_GIT_URL: https://github.com/facebookresearch/dlrm.git
new_env_keys:
- DLRM_DIR

# Dependencies
deps:
- tags: detect,os

# Variations
variations:
  full-history:
    env:
      MLC_GIT_DEPTH: ''

# Versions
default_version: main
versions:
  main:
    env:
      MLC_GIT_CHECKOUT: main
