alias: install-vllm-from-src
automation_alias: script
automation_uid: 5b4e0237da074764
cache: true
category: Compiler automation
deps:
- tags: detect,os
- tags: detect,cpu
- names:
  - python
  - python3
  skip_if_env:
    MLC_CONDA_ENV:
    - 'yes'
  tags: get,python3
- names:
  - python-pip
  - pip
  skip_if_env:
    MLC_GENERIC_PYTHON_PACKAGE_NAME:
    - pip
  tags: get,generic-python-lib,_pip
- names:
  - compiler
  tags: get,compiler
- tags: get,generic,sys-util,_cmake
- env:
    MLC_GIT_CHECKOUT_PATH_ENV_NAME: MLC_VLLM_SRC_REPO_PATH
  extra_cache_tags: vllm,src,vllm-src,vllm-src-repo
  names:
  - vllm-src-repo
  tags: get,git,repo
  update_tags_from_env_with_prefix:
    _branch.:
    - MLC_GIT_CHECKOUT
    _repo.:
    - MLC_GIT_URL
    _sha.:
    - MLC_GIT_CHECKOUT_SHA
    _tag.:
    - MLC_GIT_CHECKOUT_TAG
env:
  MLC_GIT_URL: https://github.com/vllm-project/vllm
name: Build vllm from sources
new_env_keys:
- MLC_VLLM_*
prehook_deps: []
sort: 1000
tags:
- install-vllm-from-src
uid: 7b3ad76e24d742c7
variations:
  branch.#:
    env:
      MLC_GIT_CHECKOUT: '#'
  cherrypicks.#:
    ad:
      pytorch-src-repo:
        tags: _cherrypicks.#
    env: {}
  cpu:
    group: device
    default: true
    env:
      MLC_TMP_DEVICE: cpu
    deps:
      - tags: get,generic-python-lib,_package.setuptools_scm
      - tags: get,generic-sys-util,_libnuma-dev
  cuda:
    deps:
    - names:
      - cuda
      tags: get,cuda,_cudnn
    env:
      CUDA_HOME: <<<MLC_CUDA_INSTALLED_PATH>>>
      CUDA_NVCC_EXECUTABLE: <<<MLC_NVCC_BIN_WITH_PATH>>>
      CUDNN_INCLUDE_PATH: <<<MLC_CUDA_PATH_INCLUDE_CUDNN>>>
      CUDNN_LIBRARY_PATH: <<<MLC_CUDA_PATH_LIB_CUDNN>>>
      TORCH_CUDA_ARCH_LIST: Ampere Ada Hopper
      TORCH_CXX_FLAGS: -D_GLIBCXX_USE_CXX11_ABI=1
      USE_CUDA: '1'
      USE_CUDNN: '1'
  pr-to-apply.#:
    ad:
      pytorch-src-repo:
        tags: _pr-to-apply.#
    env: {}
  repo.#:
    env:
      MLC_GIT_URL: '#'
    group: repo
  repo.https://github.com/vllm-project/vllm:
    default: true
    env:
      MLC_GIT_URL: https://github.com/vllm-project/vllm
    group: repo
  branch.main:
    default: true
    group: branch
  sha.#:
    env:
      MLC_GIT_CHECKOUT_SHA: '#'
  tag.#:
    ad:
      vllm-src-repo:
        tags: _no-recurse-submodules,_full-history
    env:
      MLC_GIT_CHECKOUT_TAG: '#'
versions: {}
