alias: get-lib-dnnl
uid: 1cd35a6a3b0b4530
automation_alias: script
automation_uid: 5b4e0237da074764

# Metadata
category: Detection or installation of tools and artifacts
tags:
- get
- lib-dnnl
- lib
- dnnl

# Cache
cache: true

# Environment
env:
  MLC_DNNL_CLEAN_BUILD: 'yes'
  MLC_GIT_URL: https://github.com/oneapi-src/oneDNN
  DNNL_BUILD_EXAMPLES: 'OFF'
  DNNL_BUILD_TESTS: 'OFF'
  DNNL_CPU_RUNTIME: OMP
new_env_keys:
- MLC_LIB_DNNL_*
- +C_INCLUDE_PATH
- +CPLUS_INCLUDE_PATH
- +LD_LIBRARY_PATH

# Dependencies
deps:
- tags: detect,cpu
- tags: cmake,get-cmake

# Versions
default_version: dev
versions:
  2.2.4:
    env:
      MLC_GIT_CHECKOUT: v2.2.4
  dev:
    env:
      MLC_GIT_CHECKOUT: master
