alias: compile-program
uid: c05042ba005a4bfa
automation_alias: script
automation_uid: 5b4e0237da074764

# Metadata
category: DevOps automation
tags:
- compile
- program
- c-program
- cpp-program
- compile-program
- compile-c-program
- compile-cpp-program

# Cache
clean_files:
- tmp-run.out

# Environment
default_env:
  SKIP_RECOMPILE: 'no'

# Dependencies
deps:
- tags: detect,cpu
- names:
  - compiler
  tags: get,compiler
- tags: get,compiler-flags
