alias: install-python-src
automation_alias: script
automation_uid: 5b4e0237da074764
cache: true
category: Python automation
default_env:
  MLC_CUSTOM_SSL: 'no'
  MLC_ENABLE_SSL: 'no'
  MLC_PYTHON_LTO_FLAG: ''
  MLC_PYTHON_OPTIMIZATION_FLAG: ''
  MLC_SHARED_BUILD: 'no'
  MLC_WGET_URL: https://www.python.org/ftp/python/[PYTHON_VERSION]/Python-[PYTHON_VERSION].tgz
default_version: 3.10.13
deps:
- tags: detect,os
- tags: detect,cpu
- tags: get,generic-sys-util,_libffi-dev
- tags: get,generic-sys-util,_libbz2-dev
  enable_if_env:
    MLC_HOST_OS_FLAVOR:
    - ubuntu
- tags: get,generic-sys-util,_libssl-dev
  enable_if_env:
    MLC_ENABLE_SSL: 
    - 'yes'
- enable_if_env:
    MLC_HOST_OS_FLAVOR:
    - ubuntu
  tags: get,generic-sys-util,_liblzma-dev
- enable_if_env:
    MLC_HOST_OS_FLAVOR:
    - ubuntu
  tags: get,generic-sys-util,_libncurses-dev
- enable_if_env:
    MLC_HOST_OS_FLAVOR:
    - ubuntu
  tags: get,generic-sys-util,_libreadline-dev
- enable_if_env:
    MLC_HOST_OS_FLAVOR:
    - ubuntu
  tags: get,generic-sys-util,_libsqlite3-dev
new_env_keys:
- MLC_PYTHON_INSTALL_PATH
- MLC_PYTHON_BIN_WITH_PATH
- +PATH
- +LD_LIBRARY_PATH
- +C_INCLUDE_PATH
post_deps:
- inherit_variation_tags: 'True'
  names:
  - python
  - python3
  reuse_version: true
  skip_if_env:
    MLC_REQUIRE_INSTALL:
    - 'yes'
  tags: get,python3
tags:
- install
- src
- python
- python3
- src-python3
- src-python
uid: 12d3a608afe14a1e
variations:
  lto:
    env:
      MLC_PYTHON_INSTALL_CACHE_TAGS: with-lto
      MLC_PYTHON_LTO_FLAG: ' --lto'
  optimized:
    env:
      MLC_PYTHON_INSTALL_CACHE_TAGS: optimized
      MLC_PYTHON_OPTIMIZATION_FLAG: ' --enable-optimizations'
  shared:
    env:
      MLC_PYTHON_INSTALL_CACHE_TAGS: shared
      MLC_SHARED_BUILD: 'yes'
  with-custom-ssl:
    deps:
    - tags: get,openssl
    env:
      MLC_CUSTOM_SSL: 'yes'
      MLC_PYTHON_INSTALL_CACHE_TAGS: with-custom-ssl
  with-ssl:
    env:
      MLC_ENABLE_SSL: 'yes'
      MLC_PYTHON_INSTALL_CACHE_TAGS: with-ssl
    group: ssl
    default: true
