alias: get-spec-ptd
automation_alias: script
automation_uid: 5b4e0237da074764
cache: true
category: MLPerf benchmark support
default_env:
  MLC_GIT_CHECKOUT: main
  MLC_GIT_DEPTH: --depth 1
  MLC_GIT_PATCH: 'no'
  MLC_GIT_RECURSE_SUBMODULES: ' '
  MLC_GIT_URL: https://github.com/mlcommons/power.git
default_version: main
deps:
- tags: detect,os
- names:
  - python
  - python3
  tags: get,python3
- env:
    MLC_GIT_AUTH: 'yes'
    MLC_GIT_CHECKOUT_PATH_ENV_NAME: MLC_MLPERF_POWER_SOURCE
  extra_cache_tags: mlperf,power,spec,ptdaemon,ptd
  force_env_keys:
  - MLC_GIT_*
  tags: get,git,repo,_repo.https://github.com/mlcommons/power
input_description:
  input:
    desc: Path to SPEC PTDaemon (Optional)
input_mapping:
  input: MLC_INPUT
new_env_keys:
- MLC_SPEC_PTD_PATH
- MLC_MLPERF_PTD_PATH
tags:
- get
- spec
- ptd
- ptdaemon
- power
- daemon
- power-daemon
- mlperf
- mlcommons
uid: 7423a878e4524136
versions:
  custom:
    env: {}
  main:
    env:
      MLC_GIT_CHECKOUT: main
