alias: install-llvm-prebuilt
uid: cda9094971724a0a
automation_alias: script
automation_uid: 5b4e0237da074764

# Metadata
name: Install prebuilt LLVM compiler
category: Compiler automation
tags:
- install
- prebuilt
- llvm
- prebuilt-llvm
- install-prebuilt-llvm

# Cache
cache: true

# Environment
new_env_keys:
- MLC_LLVM_*
- MLC_COMPILER_NAME
- +PATH
- +LD_LIBRARY_PATH
- +C_INCLUDE_PATH
- +CPLUS_INCLUDE_PATH

# Dependencies
deps:
- tags: detect,os
post_deps:
- skip_if_env:
    MLC_REQUIRE_INSTALL:
    - 'yes'
  tags: get,llvm

# Versions
default_version: 15.0.6
