alias: install-numactl-from-src
automation_alias: script
automation_uid: 5b4e0237da074764
cache: true
category: Detection or installation of tools and artifacts
deps:
- tags: detect,os
- tags: detect,cpu
- env:
    MLC_GIT_CHECKOUT_PATH_ENV_NAME: MLC_NUMACTL_SRC_REPO_PATH
  extra_cache_tags: numactl,src,numactl-src,numactl-src-repo
  names:
  - numactl-src-repo
  tags: get,git,repo
  update_tags_from_env_with_prefix:
    _branch.:
    - MLC_GIT_CHECKOUT
    _repo.:
    - MLC_GIT_URL
    _sha.:
    - MLC_GIT_CHECKOUT_SHA
    _tag.:
    - MLC_GIT_CHECKOUT_TAG
env:
  MLC_GIT_URL: https://github.com/numactl/numactl
name: Build numactl from sources
new_env_keys:
- MLC_NUMACTL_*
- +PATH
sort: 1000
tags:
- install
- src
- from.src
- numactl
- src-numactl
uid: 4f355ae8ca1948b2
variations:
  branch.#:
    env:
      MLC_GIT_CHECKOUT: '#'
  repo.#:
    env:
      MLC_GIT_URL: '#'
    group: repo
  repo.https://github.com/numactl/numactl:
    default: true
    env:
      MLC_GIT_URL: https://github.com/numactl/numactl
    group: repo
  sha.#:
    env:
      MLC_GIT_CHECKOUT_SHA: '#'
  tag.#:
    ad:
      pytorch-src-repo:
        tags: _no-recurse-submodules,_full-history
    env:
      MLC_GIT_CHECKOUT_TAG: '#'
warnings:
- This MLC script will need sudo to install numactl!
