alias: get-microtvm
uid: a9cad70972a140b9
automation_alias: script
automation_uid: 5b4e0237da074764

# Metadata
category: TinyML automation
tags:
- get
- src
- source
- microtvm
- tiny

# Cache
cache: true

# Environment
env:
  MLC_GIT_AUTH: 'yes'
  MLC_GIT_DEPTH: ''
  MLC_GIT_PATCH: 'no'
  MLC_GIT_URL: https://github.com/mlcommons/tiny_results_v1.0
new_env_keys:
- MLC_MICROTVM_*
local_env_keys:
- MLC_GIT_*

# Input mapping
input_mapping:
  ssh: MLC_GIT_SSH

# Dependencies
deps:
- tags: detect,os

# Variations
variations:
  full-history:
    env:
      MLC_GIT_DEPTH: --depth 10
  short-history:
    env:
      MLC_GIT_DEPTH: --depth 10

# Versions
default_version: main
versions:
  custom: {}
  main:
    env:
      MLC_GIT_CHECKOUT: main
