alias: get-geekbench
automation_alias: script
automation_uid: 5b4e0237da074764
cache: true
category: Detection or installation of tools and artifacts
default_env:
  MLC_GEEKBENCH_VERSION_MAJOR: '6'
default_version: 6.6.0
deps:
- tags: detect,os
- tags: detect,cpu
input_mapping:
  version: MLC_VERSION
  local_file: MLC_GEEKBENCH_LOCAL_FILE
new_env_keys:
- MLC_GEEKBENCH_*
- MLC_GET_DEPENDENT_CACHED_PATH
- +PATH
prehook_deps:
# Download and extract for Linux/macOS
- enable_if_env:
    MLC_GEEKBENCH_NEED_EXTRACT:
    - 'yes'
  skip_if_env:
    MLC_GEEKBENCH_INSTALLED_PATH:
      - on
  env:
    MLC_DAE_EXTRACT_DOWNLOADED: 'yes'
    MLC_DOWNLOAD_FINAL_ENV_NAME: MLC_GEEKBENCH_DOWNLOAD_PATH
    MLC_EXTRACT_FINAL_ENV_NAME: MLC_GEEKBENCH_EXTRACTED_PATH
  extra_cache_tags: geekbench
  force_cache: true
  names:
  - download-geekbench
  tags: download-and-extract,_extract
  update_tags_from_env_with_prefix:
    _url.:
    - MLC_GEEKBENCH_PACKAGE_URL
# Download only for Windows (direct exe)
- enable_if_env:
    MLC_GEEKBENCH_NEED_EXTRACT:
    - 'no'
  skip_if_env:
    MLC_GEEKBENCH_INSTALLED_PATH:
      - on
  env:
    MLC_DOWNLOAD_FINAL_ENV_NAME: MLC_GEEKBENCH_DOWNLOAD_PATH
  extra_cache_tags: geekbench
  force_cache: true
  names:
  - download-geekbench
  tags: download-and-extract
  update_tags_from_env_with_prefix:
    _url.:
    - MLC_GEEKBENCH_PACKAGE_URL
tags:
- get
- geekbench
- get-geekbench
uid: f0ae6ec4a8f94fd2
versions:
  5.5.1:
    env:
      MLC_GEEKBENCH_VERSION_MAJOR: '5'
  6.3.0:
    env:
      MLC_GEEKBENCH_VERSION_MAJOR: '6'
  6.4.0:
    env:
      MLC_GEEKBENCH_VERSION_MAJOR: '6'
  6.6.0:
    env:
      MLC_GEEKBENCH_VERSION_MAJOR: '6'
variations:
  path.#:
    env:
      MLC_GEEKBENCH_INSTALLED_PATH: '#'
    default_version: ''
