alias: get-preprocessed-dataset-openorca
automation_alias: script
automation_uid: 5b4e0237da074764
cache: true
category: AI/ML datasets
category_sort: 8500
default_env:
  MLC_DATASET_CALIBRATION: 'no'
deps:
- tags: get,sys-utils-mlc
- names:
  - python
  - python3
  tags: get,python3
- names:
  - openorca-original
  - dataset-original
  skip_if_env:
    MLC_DATASET_PREPROCESSED_BY_MLC:
    - 'on'
    - 'yes'
  tags: get,dataset,original,openorca
- force_env_keys:
  - MLC_GIT_*
  names:
  - inference-src
  skip_if_env:
    MLC_DATASET_PREPROCESSED_BY_MLC:
    - 'on'
    - 'yes'
  tags: mlperf,inference,source
- names:
  - pyarrow
  tags: get,generic-python-lib,_package.pyarrow
- names:
  - fastparquet
  tags: get,generic-python-lib,_package.fastparquet
- names:
  - transformers
  tags: get,generic-python-lib,_package.transformers
- skip_if_env:
    MLC_DATASET_PREPROCESSED_BY_MLC:
    - 'on'
    - 'yes'
  tags: get,ml-model,llama2
docker:
  real_run: false
env:
  MLC_DATASET: OPENORCA
tags:
- get
- dataset
- openorca
- language-processing
- preprocessed
uid: 5614c39cb1564d72
variations:
  '60':
    ad:
      dataset-original:
        tags: _60
    group: size
  calibration:
    base:
    - mlcommons
    env:
      MLC_DATASET_CALIBRATION: 'yes'
    group: dataset-type
    new_env_keys:
    - MLC_DATASET_CALIBRATION_PATH
    - MLC_DATASET_OPENORCA_CALIBRATION_PATH
  full:
    ad:
      dataset-original:
        tags: _full
    default: true
    group: size
  mlc:
    alias: mlcommons
  mlcommons:
    deps:
    - env:
        MLC_DOWNLOAD_FINAL_ENV_NAME: MLC_OPENORCA_PREPROCESSED_ROOT
        MLC_EXTRACT_FINAL_ENV_NAME: MLC_OPENORCA_PREPROCESSED_ROOT
        MLC_EXTRACT_TO_FOLDER: openorca-preprocessed
        MLC_RCLONE_CONFIG_NAME: mlc-inference
      extra_cache_tags: openorca,preprocessed,dataset
      force_cache: true
      names:
      - dae
      tags: download-and-extract,_rclone
      update_tags_from_env_with_prefix:
        _url.:
        - MLC_RCLONE_URL
    env:
      MLC_DATASET_PREPROCESSED_BY_MLC: 'yes'
      MLC_RCLONE_URL: mlc-inference:mlcommons-inference-wg-public/open_orca
  size.#:
    ad:
      dataset-original:
        tags: _size.#
    group: size
  validation:
    default: true
    env:
      MLC_DATASET_CALIBRATION: 'no'
    group: dataset-type
    new_env_keys:
    - MLC_DATASET_PREPROCESSED_PATH
    - MLC_DATASET_OPENORCA_PREPROCESSED_PATH
