alias: preprocess-mlperf-inference-submission
automation_alias: script
automation_uid: 5b4e0237da074764
cache: false
category: MLPerf benchmark support
clean_files: []
deps:
- names:
  - python
  - python3
  tags: get,python3
- names:
  - inference-src
  - submission-checker-src
  tags: get,mlcommons,inference,src
- names:
  - get-mlperf-submission-dir
  skip_if_env:
    MLC_MLPERF_INFERENCE_SUBMISSION_DIR:
    - 'on'
  tags: get,mlperf,submission,dir
input_mapping:
  input: MLC_MLPERF_INFERENCE_SUBMISSION_DIR
  submission_dir: MLC_MLPERF_INFERENCE_SUBMISSION_DIR
  version: MLC_MLPERF_SUBMISSION_CHECKER_VERSION
  submitter: MLC_MLPERF_SUBMITTER
  submission_preprocessor_args: MLC_MLPERF_PREPROCESS_SUBMISSION_EXTRA_ARGS
tags:
- run
- mlc
- mlcommons
- mlperf
- inference
- submission
- mlperf-inference
- processor
- preprocessor
- preprocess
uid: c23068394a314266
