alias: run-apptainer-container
uid: d3bdc61a712c4703
automation_alias: script
automation_uid: 5b4e0237da074764
tags:
- run
- apptainer
- container
cache: false
category: Container automation
default_env:
  MLC_APPTAINER_WRITABLE_TMPFS: 'yes'
  MLC_APPTAINER_CLEANENV: 'yes'
  MLC_APPTAINER_OS: ubuntu
  MLC_APPTAINER_OS_VERSION: '24.04'
input_mapping:
  image: MLC_APPTAINER_IMAGE
  image_url: MLC_APPTAINER_IMAGE_URL
  docker_image: MLC_APPTAINER_FROM_DOCKER
  sandbox: MLC_APPTAINER_SANDBOX
  sandbox_path: MLC_APPTAINER_SANDBOX_PATH
  writable: MLC_APPTAINER_WRITABLE
  writable_tmpfs: MLC_APPTAINER_WRITABLE_TMPFS
  cleanenv: MLC_APPTAINER_CLEANENV
  nv: MLC_APPTAINER_NV
  rocm: MLC_APPTAINER_ROCM
  bind: MLC_APPTAINER_BIND_MOUNTS
  overlay: MLC_APPTAINER_OVERLAY
  extra_args: MLC_APPTAINER_EXTRA_ARGS
  pre_run_cmds: MLC_APPTAINER_PRE_RUN_COMMANDS
  post_run_cmds: MLC_APPTAINER_POST_RUN_COMMANDS
  run_cmd: MLC_APPTAINER_RUN_CMD
  run_cmd_extra: MLC_APPTAINER_RUN_CMD_EXTRA
  script_tags: MLC_APPTAINER_RUN_SCRIPT_TAGS
  fakeroot: MLC_APPTAINER_FAKEROOT
  no_home: MLC_APPTAINER_NO_HOME
  contain: MLC_APPTAINER_CONTAIN
  containall: MLC_APPTAINER_CONTAINALL
  home: MLC_APPTAINER_HOME
  pwd: MLC_APPTAINER_PWD
  env_vars: MLC_APPTAINER_ENV_VARS
  save_script: MLC_APPTAINER_SAVE_SCRIPT
  os: MLC_APPTAINER_OS
  os_version: MLC_APPTAINER_OS_VERSION
  docker_os: MLC_APPTAINER_OS
  docker_os_version: MLC_APPTAINER_OS_VERSION
  image_name: MLC_APPTAINER_IMAGE_NAME
  image_tag: MLC_APPTAINER_IMAGE_TAG
  recreate: MLC_APPTAINER_IMAGE_RECREATE
  rebuild: MLC_APPTAINER_IMAGE_RECREATE
new_env_keys:
- MLC_APPTAINER_*
deps:
- tags: get-apptainer
prehook_deps:
- names:
  - build-apptainer-image
  skip_if_any_env:
    MLC_APPTAINER_IMAGE_EXISTS:
    - 'yes'
    MLC_APPTAINER_SKIP_BUILD:
    - 'yes'
  tags: build,apptainer,image
