alias: install-rocm
uid: 9d13f90463ce4545
automation_alias: script
automation_uid: 5b4e0237da074764

# Metadata
category: AI/ML frameworks
tags:
- install
- rocm
- install-rocm

# Cache
cache: true
clean_files: []

# Environment
env: {}
new_env_keys:
- MLC_ROMLC_*
- +PATH

# Dependencies
deps:
- tags: detect,os

# Versions
default_version: 5.7.1
versions: {}
