alias: install-rocm
uid: 9d13f90463ce4545
automation_alias: script
automation_uid: 5b4e0237da074764

# Metadata
category: AI/ML frameworks
tags:
- install
- rocm
- install-rocm

# Cache
cache: true
clean_files: []

# Input mapping
input_mapping:
  rocm_install_prefix: MLC_ROCM_INSTALL_PREFIX

# Environment
env: {}
new_env_keys:
- MLC_ROMLC_*
- MLC_ROCM_INSTALL_PREFIX
- +PATH

# Dependencies
deps:
- tags: detect,os
- tags: detect,sudo

# Prehook dependencies
prehook_deps:
- tags: download,file
  extra_cache_tags: rocm,installer,runfile
  force_cache: true
  enable_if_env:
    MLC_ROCM_USE_RUNFILE:
    - 'yes'
  env:
    MLC_DOWNLOAD_FILENAME: <<<MLC_ROCM_RUNFILE_NAME>>>
  force_env_keys:
  - MLC_DOWNLOAD_URL
  - MLC_DOWNLOAD_FILENAME

# Variations
variations:
  compiler-only:
    env:
      MLC_ROCM_COMPILER_ONLY: 'yes'

# Versions
default_version: 7.2.2
versions:
  '7.2.2': {}
  '7.2.1': {}
  '6.2.0': {}
  '6.1.0': {}
  '5.7.1': {}

# Tests
tests:
  run_inputs:
  - variations_list: []
