alias: get-dataset-deeplab-resnet50
automation_alias: script
automation_uid: 5b4e0237da074764
cache: true
tags:
- get
- ml-model
- ml
- model
- resnet50-deeplab
- resnet50
- deeplab
uid: 93097b691a6a4fce
new_env_keys:
  - MLC_ML_MODEL_DPLAB_RESNET50_PATH
input_mapping:
  dp_resnet50_path: MLC_ML_MODEL_DPLAB_RESNET50_PATH
variations:
  gpu:
    default: true
    group: device
    env:
      MLC_ML_MODEL_DPLAB_RESNET50_FORMAT: pth
  cpu:
    group: device
    env:
      MLC_ML_MODEL_DPLAB_RESNET50_FORMAT: onnx
