alias: detect-host-system-details
uid: dcd80c5fa31d4172
automation_alias: script
automation_uid: 5b4e0237da074764

# Metadata
category: Platform information
tags:
- detect
- host
- system
- details

# Cache
cache: false
clean_files:
- tmp-run.out

# Environment
new_env_keys:
- MLC_HOST_MEMORY_CONFIGURATION
- MLC_HOST_STORAGE_TYPE
- MLC_HOST_NETWORK_CARD_COUNT
- MLC_HOST_NETWORKING

# Dependencies
deps:
- tags: detect,sudo
  skip_if_env:
    MLC_HOST_OS_TYPE:
    - windows
- tags: get,python
  names:
  - python
  - python3

# Output / debugging
print_files_if_script_error:
- tmp-run.out
