alias: get-mlperf-automotive-loadgen
uid: 82396582494a4d38

automation_alias: script
automation_uid: 5b4e0237da074764

cache: true

category: MLPerf benchmark support

default_env:
  MLC_SHARED_BUILD: 'no'

default_version: master

deps:
- tags: detect,os
- names:
  - python3
  - python
  tags: get,python3
- force_env_keys:
  - MLC_GIT_URL
  - MLC_GIT_CHECKOUT
  names:
  - automotive-src-loadgen
  skip_if_env:
    MLC_MLPERF_AUTOMOTIVE_LOADGEN_DOWNLOAD:
    - 'YES'
  tags: get,mlcommons,automotive,src
- enable_if_env:
    MLC_MLPERF_AUTOMOTIVE_LOADGEN_DOWNLOAD:
    - 'YES'
  force_cache: true
  names:
  - automotive-src-loadgen-download
  tags: download-and-extract,file,_wget,_extract
  update_tags_from_env_with_prefix:
    _url.:
    - MLC_MLPERF_AUTOMOTIVE_LOADGEN_DOWNLOAD_URL
- names:
  - compiler
  skip_if_any_env:
    MLC_HOST_OS_TYPE:
    - windows
    MLC_TMP_MLPERF_AUTOMOTIVE_LOADGEN_INSTALL_FROM_PIP:
    - 'yes'
  tags: get,compiler
- enable_if_env:
    MLC_HOST_OS_TYPE:
    - windows
  skip_if_env:
    MLC_TMP_MLPERF_AUTOMOTIVE_LOADGEN_INSTALL_FROM_PIP:
    - 'yes'
  names:
  - compiler
  tags: get,cl
- names:
  - cmake
  tags: get,cmake
  version_min: '3.12'
- names:
  - pip-package
  - wheel
  tags: get,generic-python-lib,_package.wheel
- names:
  - pip-package
  - pip
  tags: get,generic-python-lib,_pip
- names:
  - pip-package
  - pybind11
  tags: get,generic-python-lib,_package.pybind11
- names:
  - pip-package
  - setuputils
  tags: get,generic-python-lib,_package.setuptools

extra_cache_tags_from_env:
- env: MLC_PYTHON_CACHE_TAGS
  prefix: python-
- env: MLC_COMPILER_CACHE_TAGS
  prefix: compiler-

new_env_keys:
- +PYTHONPATH
- +C_INCLUDE_PATH
- +CPLUS_INCLUDE_PATH
- +LD_LIBRARY_PATH
- +DYLD_FALLBACK_LIBRARY_PATH
- MLC_MLPERF_AUTOMOTIVE_LOADGEN_*

tags:
- get
- loadgen
- automotive
- automotive-loadgen
- mlperf
- mlcommons

variations:
  from-pip:
    env:
      MLC_TMP_MLPERF_AUTOMOTIVE_LOADGEN_INSTALL_FROM_PIP: 'yes'
    deps:
    - tags: get,generic-python-lib,_package.mlcommons-loadgen
  custom-python:
    ad:
      pip-package:
        tags: _custom-python
      python3:
        skip_if_env:
          MLC_TMP_USE_CUSTOM_PYTHON:
          - 'on'
    env:
      MLC_TMP_USE_CUSTOM_PYTHON: 'on'
  keep-build:
    group: clean-build
    env:
      MLC_MLPERF_AUTOMOTIVE_LOADGEN_BUILD_CLEAN: 'no'
  clean-build:
    group: clean-build
    default: true
    env:
      MLC_MLPERF_AUTOMOTIVE_LOADGEN_BUILD_CLEAN: 'yes'
  no-compilation-warnings:
    env:
      '+ CXXFLAGS':
        - '-Werror'
        - '-Wno-unused-parameter'

versions:
  custom:
    add_deps:
      automotive-src-loadgen:
        version: custom
  master:
    add_deps:
      automotive-src-loadgen:
        version: master

print_env_at_the_end:
  MLC_MLPERF_AUTOMOTIVE_LOADGEN_INSTALL_PATH: "Path to the tool"
