alias: get-one-api
automation_alias: script
automation_uid: 5b4e0237da074764
cache: true
category: Compiler automation
clean_files: []
default_version: 2025.1.1
deps:
- tags: detect,os
name: Detect or install OneAPI compiler
new_env_keys:
- MLC_ONEAPI_*
- MLC_ONEAPI_COMPILER_*
- MLC_COMPILER_*
- MLC_LINKER_*
- +PATH
- +LD_LIBRARY_PATH

input_mapping:
  oneapi_dir: MLC_ONEAPI_DIR_PATH
 
post_deps_off:
- tags: get,compiler-flags
sort: 500
tags:
- get
- oneapi
- compiler
- get-oneapi
uid: 1af872e81ef54742

tests:
  - variations_list:
    - fortran

versions:
  2025.1.1:
    env:
      MLC_ONEAPI_INSTALL_URL_BASE: https://registrationcenter-download.intel.com/akdlm/IRC_NAS/6bfca885-4156-491e-849b-1cd7da9cc760
      MLC_ONEAPI_INSTALL_FILENAME: intel-oneapi-base-toolkit-2025.1.1.36_offline.sh
      MLC_ONEAPI_INSTALL_VERSION_PREFIX: '2025.1'
      MLC_VERSION: '2025.1.1'

variations:
  path.#:
    env:
      MLC_ONEAPI_DIR_PATH: "#"
  fortran:
    env:
      MLC_ONEAPI_FORTRAN: 'yes'
