alias: get-rclone
automation_alias: script
automation_uid: 5b4e0237da074764
cache: true
category: Detection or installation of tools and artifacts
default_version: 1.65.2
deps:
- tags: detect,os
- enable_if_env:
    MLC_HOST_OS_TYPE:
    - windows
  tags: get,sys-utils-min
new_env_keys:
- MLC_RCLONE_CACHE_TAGS
- MLC_RCLONE_BIN_WITH_PATH
- MLC_RCLONE_VERSION
- +PATH
tags:
- get
- rclone
uid: 22ffb43c49c9419e
variations:
  gdrive:
    env:
      MLC_RCLONE_GDRIVE: 'yes'
  system:
    env:
      MLC_RCLONE_SYSTEM: 'yes'
    warnings:
    - This MLC script will install rclone using sudo/brew!
