alias: get-rclone
uid: 22ffb43c49c9419e
automation_alias: script
automation_uid: 5b4e0237da074764

# Metadata
category: Detection or installation of tools and artifacts
tags:
- get
- rclone

# Cache
cache: true

# Environment
new_env_keys:
- MLC_RCLONE_CACHE_TAGS
- MLC_RCLONE_BIN_WITH_PATH
- MLC_RCLONE_VERSION
- +PATH

# Dependencies
deps:
- tags: detect,os
- enable_if_env:
    MLC_HOST_OS_TYPE:
    - windows
  tags: get,sys-utils-min

# Variations
variations:
  gdrive:
    env:
      MLC_RCLONE_GDRIVE: 'yes'
  system:
    env:
      MLC_RCLONE_SYSTEM: 'yes'
    warnings:
    - This MLC script will install rclone using sudo/brew!

# Versions
default_version: 1.65.2
