alias: get-lib-aocl-blis
uid: 29afd85b811a44cd
automation_alias: script
automation_uid: 5b4e0237da074764

# Metadata
category: Detection or installation of tools and artifacts
tags:
- get
- lib
- lib-aocl-blis
- aocl-blis
- aocl
- blis

# Cache
cache: true

# Environment
default_env:
  MLC_AOCL_ACCEPT_EULA: 'no'
new_env_keys:
- MLC_AOCL_BLIS_SRC_PATH
- MLC_AOCL_BLIS_BUILD_PATH
- MLC_AOCL_BLIS_INSTALL_PATH
- MLC_AOCL_BLIS_LIB_PATH
- +LD_LIBRARY_PATH
- +LIBRARY_PATH
- +C_INCLUDE_PATH
- +CPLUS_INCLUDE_PATH
- MLC_AOCL_BINARY_INSTALL_PATH
- MLC_AOCL_BLIS_BINARY_PATH
new_state_keys: []

# Input mapping
input_mapping:
  accept_eula: MLC_AOCL_ACCEPT_EULA
input_description:
  accept_eula:
    desc: Accept the AMD EULA for binary downloads (yes/no)

# Dependencies
deps:
- tags: detect,cpu
- tags: get,utils,aocl-utils
  skip_if_env:
    MLC_AOCL_BINARY_DOWNLOAD:
    - 'yes'
- tags: get,git,repo
  names:
  - aocl-blis-repo
  extra_cache_tags: aocl-blis,repo,aocl-blis-repo
  env:
    MLC_GIT_CHECKOUT_PATH_ENV_NAME: MLC_AOCL_BLIS_SRC_PATH
  force_env_keys:
  - MLC_GIT_*
  update_tags_from_env_with_prefix:
    _branch.:
    - MLC_GIT_CHECKOUT
    _repo.:
    - MLC_GIT_REPO_URL
    _tag.:
    - MLC_GIT_CHECKOUT_TAG
  skip_if_env:
    MLC_AOCL_BINARY_DOWNLOAD:
    - 'yes'

# Variations
variations:
  binary.aocc:
    env:
      MLC_AOCL_BINARY_COMPILER: aocc
    group: binary-compiler
    default: true
  binary.gcc:
    env:
      MLC_AOCL_BINARY_COMPILER: gcc
    group: binary-compiler
  repo.#:
    env:
      MLC_GIT_REPO_URL: '#'
    group: repo
  repo.amd:
    default: true
    env:
      MLC_GIT_REPO_URL: https://github.com/amd/blis.git
    group: repo
  tag.#:
    env:
      MLC_GIT_CHECKOUT_TAG: '#'
    group: version
  version.5.1.0:
    group: version
    env:
      MLC_GIT_CHECKOUT: 5.1.0
      MLC_AOCL_BINARY_VERSION: 5.1.0
      MLC_AOCL_BINARY_VERSION_PATH: 5-1
  version.5.2.2:
    default: true
    group: version
    env:
      MLC_GIT_CHECKOUT: 5.2.2
      MLC_AOCL_BINARY_VERSION: 5.2.2
      MLC_AOCL_BINARY_VERSION_PATH: 5-2
  binary:
    env:
      MLC_AOCL_BINARY_DOWNLOAD: 'yes'
      MLC_AOCL_BINARY_LIB_NAME: blas
      MLC_AOCL_BINARY_COMPILER: aocc
    prehook_deps:
    - tags: download-and-extract
      names:
      - aocl-blis-binary
      extra_cache_tags: aocl,blis,binary
      force_cache: true
      env:
        MLC_DAE_URL: https://download.amd.com/developer/eula/<<<MLC_AOCL_BINARY_LIB_NAME>>>/<<<MLC_AOCL_BINARY_LIB_NAME>>>-<<<MLC_AOCL_BINARY_VERSION_PATH>>>/aocl-blis-linux-<<<MLC_AOCL_BINARY_COMPILER>>>-<<<MLC_AOCL_BINARY_VERSION>>>.tar.gz
        MLC_DOWNLOAD_FINAL_ENV_NAME: MLC_AOCL_BLIS_BINARY_PATH
        MLC_EXTRACT_FINAL_ENV_NAME: MLC_AOCL_BLIS_BINARY_PATH
        MLC_DAE_EXTRACT_DOWNLOADED: 'yes'
      update_tags_from_env_with_prefix:
        _url.:
        - MLC_DAE_URL
      force_env_keys:
      - MLC_OUTDIRNAME
    default_variations:
      version: version.5.1.0
  branch.#:
    env:
      MLC_GIT_CHECKOUT: '#'
  master:
    env:
      MLC_GIT_CHECKOUT: master

# Tests
tests:
  run_inputs:
  - variations_list:
    - repo.amd
  - variations_list:
    - binary
    env:
      MLC_AOCL_ACCEPT_EULA: 'yes'
