alias: set-echo-off-win
uid: 49d94b57524f4fcf
automation_alias: script
automation_uid: 5b4e0237da074764

# Metadata
category: DevOps automation
tags:
- set
- echo
- 'off'
- win
- echo-off-win
- echo-off

# Environment
new_state_keys:
- script_prefix
