alias: get-aocc
uid: 1ceb0656e99a44ec
automation_alias: script
automation_uid: 5b4e0237da074764

# Metadata
name: Detect or install AOCC compiler
category: Compiler automation
tags:
- compiler
- get
- aocc

# Cache
cache: true
clean_files: []

# Environment
new_env_keys:
- MLC_AOCC_*
- MLC_C_COMPILER_*
- MLC_CXX_COMPILER_*
- MLC_FORTRAN_COMPILER_*
- MLC_COMPILER_*
- MLC_LINKER_*
- + CFLAGS
- + CXXFLAGS
- + FFLAGS
- + LDFLAGS
- +MLC_HOST_OS_DEFAULT_INCLUDE_PATH
- +PATH

# Input mapping
input_mapping:
  accept_eula: MLC_AOCC_ACCEPT_EULA
  aocc_dir: MLC_AOCC_DIR_PATH
  tar_file_path: MLC_AOCC_TAR_FILE_PATH

# Dependencies
deps:
- tags: detect,os
- tags: download,file,_mlcutil
  extra_cache_tags: aocc,download
  update_tags_from_env_with_prefix:
    _url.:
    - MLC_AOCC_URL
  force_cache: true
  env:
    MLC_DOWNLOAD_FINAL_ENV_NAME: MLC_AOCC_TAR_FILE_PATH
  enable_if_env:
    MLC_AOCC_URL:
    - true
    MLC_AOCC_ACCEPT_EULA:
    - true
- tags: extract,file
  update_tags_from_env_with_prefix:
    _path.:
    - MLC_AOCC_TAR_FILE_PATH
  extra_cache_tags: aocc,extract
  force_cache: true
  env:
    MLC_EXTRACT_FINAL_ENV_NAME: MLC_AOCC_DIR_PATH
    MLC_EXTRACT_TO_FOLDER: aocc_install
  enable_if_env:
    MLC_AOCC_NEEDS_TAR:
    - true

# Variations
variations:
  download-and-install:
    group: install-type
    default: true
    default_version: 5.0.0
    env:
      MLC_AOCC_DOWNLOAD: true
  local-install:
    group: install-type
    env:
      MLC_AOCC_DOWNLOAD: false
  path.#:
    default_variations:
      install-type: local-install
    env:
      MLC_AOCC_DIR_PATH: '#'

# Versions
versions:
  5.0.0:
    env:
      MLC_AOCC_URL: https://download.amd.com/developer/eula/aocc/aocc-5-0/aocc-compiler-5.0.0.tar
      MLC_DOWNLOAD_CHECKSUM: c01ee764a8370a2ed546c1a38e41bb42
      MLC_AOCC_NEEDS_TAR: true
      MLC_VERSION: 5.0.0-Build#1377

# Output / debugging
sort: 500

# Tests
tests:
  run_inputs:
  - accept_eula: true
