alias: send-mail
automation_alias: script
automation_uid: 5b4e0237da074764
category: Utils
deps:
  - tags: get,python
    names:
      - python
      - python3
  - tags: get,generic-sys-util,_postfix
    enable_if_env:
      MLC_HOST_OS_FLAVOR:
      - ubuntu
new_env_keys: []
new_state_keys: []
post_deps: []
posthook_deps: []
prehook_deps: []
input_mapping:
  subject: MLC_EMAIL_SUBJECT
  to_addresses: MLC_EMAIL_TO_ADDRESSES
  to_address: MLC_EMAIL_TO_ADDRESSES
  attachments: MLC_EMAIL_ATTACHMENTS
  attachment: MLC_EMAIL_ATTACHMENTS
tags:
- send
- mail
- email
uid: 5f9b9654ecbe4662
