alias: app-mlperf-inference-mlcommons-cpp
uid: bf62405e6c7a44bf
automation_alias: script
automation_uid: 5b4e0237da074764

# Metadata
category: MLPerf Inference
developers: '[Thomas Zhu](https://www.linkedin.com/in/hanwen-zhu-483614189), [Arjun Suresh](https://www.linkedin.com/in/arjunsuresh), [Grigori Fursin](https://cKnowledge.org/gfursin)'
tags:
- app
- mlcommons
- mlperf
- inference
- cpp

# Environment
default_env:
  MLC_BATCH_COUNT: '1'
  MLC_BATCH_SIZE: '1'
  MLC_FAST_COMPILATION: 'yes'
  MLC_MLPERF_SUT_NAME_IMPLEMENTATION_PREFIX: cpp
new_env_keys:
- MLC_MLPERF_*
- MLC_DATASET_*
- MLC_ML_MODEL_*
- MLC_HW_NAME
new_state_keys:
- mlperf-inference-implementation
- MLC_SUT_*

# Input mapping
input_mapping:
  count: MLC_MLPERF_LOADGEN_QUERY_COUNT
  max_batchsize: MLC_MLPERF_LOADGEN_MAX_BATCHSIZE
  mlperf_conf: MLC_MLPERF_CONF
  mode: MLC_MLPERF_LOADGEN_MODE
  output_dir: MLC_MLPERF_OUTPUT_DIR
  performance_sample_count: MLC_MLPERF_LOADGEN_PERFORMANCE_SAMPLE_COUNT
  scenario: MLC_MLPERF_LOADGEN_SCENARIO
  user_conf: MLC_MLPERF_USER_CONF

# Dependencies
deps:
- tags: detect,os
- tags: detect,cpu
- tags: get,sys-utils-mlc
- tags: get,cuda,_cudnn
  enable_if_env:
    MLC_MLPERF_DEVICE:
    - gpu
- tags: get,loadgen,_wg-inference
  names:
  - loadgen
- tags: get,mlcommons,inference,src
  names:
  - inference-src
- enable_if_env:
    MLC_MLPERF_BACKEND:
    - pytorch
  names:
  - pytorch
  tags: get,generic-python-lib,_torch
- enable_if_env:
    MLC_MLPERF_BACKEND:
    - pytorch
  names:
  - torchvision
  tags: get,generic-python-lib,_torchvision
- enable_if_env:
    MLC_MLPERF_BACKEND:
    - onnxruntime
    MLC_MLPERF_DEVICE:
    - cpu
  tags: get,lib,onnxruntime,lang-cpp,_cpu
- enable_if_env:
    MLC_MLPERF_BACKEND:
    - onnxruntime
    MLC_MLPERF_DEVICE:
    - gpu
  tags: get,lib,onnxruntime,lang-cpp,_cuda
- enable_if_env:
    MLC_MODEL:
    - resnet50
  names:
  - imagenet-preprocessed
  tags: get,dataset,preprocessed,imagenet,_NCHW
- enable_if_env:
    MLC_MODEL:
    - resnet50
    MLC_MLPERF_BACKEND:
    - onnxruntime
  tags: get,ml-model,raw,resnet50,_onnx
- enable_if_env:
    MLC_MODEL:
    - resnet50
    MLC_MLPERF_BACKEND:
    - pytorch
  names:
  - resnet50-pytorch-weights
  tags: get,ml-model,raw,resnet50,_pytorch,_fp32
- enable_if_env:
    MLC_MODEL:
    - retinanet
  names:
  - openimages-preprocessed
  tags: get,dataset,preprocessed,openimages,_validation,_NCHW
- enable_if_env:
    MLC_MODEL:
    - retinanet
  tags: get,ml-model,retinanet,_onnx,_fp32
- enable_if_env:
    MLC_MODEL:
    - bert-99
    - bert-99.9
  names:
  - bert-model
  tags: get,ml-model,language-processing,bert-large,_onnx
- enable_if_env:
    MLC_MODEL:
    - bert-99
    - bert-99.9
  names:
  - squad-preprocessed
  tags: get,dataset,preprocessed,tokenized,squad,_raw
- enable_if_env:
    MLC_MODEL:
    - bert-99
    - bert-99.9
  names:
  - squad-vocab
  tags: get,dataset-aux,squad-vocab
- tags: generate,user-conf,mlperf,inference,_wg-inference
  names:
  - user-conf-generator
post_deps:
- names:
  - compile-program
  tags: compile,cpp-program
  skip_if_env:
    MLC_MLPERF_SKIP_RUN:
    - 'yes'
- names:
  - mlperf-runner
  tags: benchmark-mlperf
  skip_if_env:
    MLC_MLPERF_SKIP_RUN:
    - 'yes'
- tags: save,mlperf,inference,state
  names:
  - save-mlperf-inference-state

# Variations
variations:
  batch-size.#:
    group: batch-size
    env:
      MLC_MLPERF_LOADGEN_MAX_BATCHSIZE: '#'
  cpu:
    group: device
    default: true
    env:
      MLC_MLPERF_DEVICE: cpu
  cuda:
    group: device
    env:
      MLC_MLPERF_DEVICE: gpu
      MLC_MLPERF_DEVICE_LIB_NAMESPEC: cudart
  onnxruntime:
    group: framework
    default: true
    env:
      MLC_MLPERF_BACKEND: onnxruntime
      MLC_MLPERF_BACKEND_LIB_NAMESPEC: onnxruntime
  pytorch:
    group: framework
    env:
      MLC_MLPERF_BACKEND: pytorch
      MLC_MLPERF_BACKEND_LIB_NAMESPEC: torch
  tf:
    group: framework
    env:
      MLC_MLPERF_BACKEND: tf
  tflite:
    group: framework
    env:
      MLC_MLPERF_BACKEND: tflite
  tvm-onnx:
    group: framework
    env:
      MLC_MLPERF_BACKEND: tvm-onnx
  multistream:
    group: loadgen-scenario
    env:
      MLC_MLPERF_LOADGEN_SCENARIO: MultiStream
  offline:
    group: loadgen-scenario
    default: true
    env:
      MLC_MLPERF_LOADGEN_SCENARIO: Offline
  server:
    group: loadgen-scenario
    env:
      MLC_MLPERF_LOADGEN_SCENARIO: Server
  singlestream:
    group: loadgen-scenario
    env:
      MLC_MLPERF_LOADGEN_SCENARIO: SingleStream
      MLC_MLPERF_LOADGEN_MAX_BATCHSIZE: 1
  bert-99:
    group: model
    env:
      MLC_MODEL: bert-99
    default_env:
      MLC_MLPERF_LOADGEN_MAX_BATCHSIZE: 8
      MLC_MLPERF_LOADGEN_PERFORMANCE_SAMPLE_COUNT: '10833'
  bert-99.9:
    group: model
    env:
      MLC_MODEL: bert-99.9
    default_env:
      MLC_MLPERF_LOADGEN_MAX_BATCHSIZE: 8
      MLC_MLPERF_LOADGEN_PERFORMANCE_SAMPLE_COUNT: '10833'
  resnet50:
    group: model
    default: true
    env:
      MLC_MODEL: resnet50
  retinanet:
    group: model
    default_env:
      MLC_MLPERF_LOADGEN_MAX_BATCHSIZE: 1
    env:
      MLC_MODEL: retinanet
  bert-99,offline:
    default_env:
      MLC_MLPERF_LOADGEN_MAX_BATCHSIZE: 8
  bert-99,singlestream:
    default_env:
      MLC_MLPERF_LOADGEN_MAX_BATCHSIZE: 1
  bert-99.9,offline:
    default_env:
      MLC_MLPERF_LOADGEN_MAX_BATCHSIZE: 8
  bert-99.9,singlestream:
    default_env:
      MLC_MLPERF_LOADGEN_MAX_BATCHSIZE: 1
  multistream,resnet50:
    default_variations:
      batch-size: batch-size.8
  multistream,retinanet:
    default_variations:
      batch-size: batch-size.1
  offline,resnet50:
    default_variations:
      batch-size: batch-size.32
  resnet50,multistream:
    default_env:
      MLC_MLPERF_LOADGEN_MAX_BATCHSIZE: 8
  resnet50,offline:
    default_env:
      MLC_MLPERF_LOADGEN_MAX_BATCHSIZE: 32
  resnet50,server:
    default_env:
      MLC_MLPERF_LOADGEN_MAX_BATCHSIZE: 32

# Tests
tests:
  run_inputs:
  - variations_list:
    - resnet50,onnxruntime,cpu,offline
    env:
      MLC_MLPERF_LOADGEN_MODE: performance
      MLC_MLPERF_LOADGEN_SCENARIO: Offline
      MLC_MLPERF_LOADGEN_QUERY_COUNT: '10'
      MLC_MLPERF_LOADGEN_PERFORMANCE_SAMPLE_COUNT: '10'
  - variations_list:
    - resnet50,onnxruntime,cpu,singlestream
    env:
      MLC_MLPERF_LOADGEN_MODE: performance
      MLC_MLPERF_LOADGEN_SCENARIO: SingleStream
      MLC_MLPERF_LOADGEN_QUERY_COUNT: '10'
      MLC_MLPERF_LOADGEN_PERFORMANCE_SAMPLE_COUNT: '10'
  - variations_list:
    - resnet50,pytorch,cpu,offline
    env:
      MLC_MLPERF_LOADGEN_MODE: performance
      MLC_MLPERF_LOADGEN_SCENARIO: Offline
      MLC_MLPERF_LOADGEN_QUERY_COUNT: '10'
      MLC_MLPERF_LOADGEN_PERFORMANCE_SAMPLE_COUNT: '10'
  - variations_list:
    - bert-99,onnxruntime,cpu,offline
    env:
      MLC_MLPERF_LOADGEN_MODE: performance
      MLC_MLPERF_LOADGEN_SCENARIO: Offline
      MLC_MLPERF_LOADGEN_QUERY_COUNT: '3'
      MLC_MLPERF_LOADGEN_PERFORMANCE_SAMPLE_COUNT: '3'
