alias: get-qaic-apps-sdk
uid: 0a9e206af6764da9
automation_alias: script
automation_uid: 5b4e0237da074764

# Metadata
category: AI/ML frameworks
tags:
- get
- detect
- qaic
- apps
- sdk
- apps-sdk
- qaic-apps-sdk

# Cache
cache: true

# Environment
new_env_keys:
- +PATH
- MLC_QAIC_EXEC_PATH
- +C_INCLUDE_PATH
- +CPLUS_INCLUDE_PATH
- +LD_LIBRARY_PATH
- +DYLD_FALLBACK_LIBRARY_PATH
new_state_keys: []

# Input mapping
input_mapping: {}
input_description: {}

# Dependencies
deps: []
prehook_deps: []
posthook_deps: []
post_deps: []

# Variations
variations: {}

# Versions
versions: {}
