alias: app-gs2
uid: d49b91f5724084d1
automation_alias: script
automation_uid: 5b4e0237da074764

# Metadata
category: HPC Application

tags:
- app
- gs2
- hpc

# Cache
cache: true

# Environment
default_env: {}
new_env_keys:
- MLC_GS2_SRC_PATH
- MLC_GS2_INSTALL_PATH
- MLC_GS2_BIN_PATH
- +PATH
new_state_keys: []

# Dependencies
deps:
- tags: detect,cpu
- env:
    MLC_GENERIC_SYS_UTIL_IGNORE_MISSING_PACKAGE: true
  tags: get,generic-sys-util,_build-essential
- tags: get,generic-sys-util,_gfortran
- tags: get,generic-sys-util,_libfftw3-dev
- tags: get,generic-sys-util,_libnetcdf-dev
- tags: get,generic-sys-util,_libnetcdff-dev
- tags: get,generic-sys-util,_libopenmpi-dev
- tags: get,python3
  names:
  - python
  - python3
- tags: get,git,repo
  names:
  - gs2-repo
  extra_cache_tags: gs2,repo,gs2-repo
  env:
    MLC_GIT_CHECKOUT_PATH_ENV_NAME: MLC_GS2_SRC_PATH
  force_env_keys:
  - MLC_GIT_*
  update_tags_from_env_with_prefix:
    _branch.:
    - MLC_GIT_CHECKOUT
    _repo.:
    - MLC_GIT_REPO_URL
    _tag.:
    - MLC_GIT_CHECKOUT_TAG
prehook_deps: []
posthook_deps: []
post_deps: []

# Variations
variations:
  repo.#:
    env:
      MLC_GIT_REPO_URL: '#'
    group: repo
  repo.official:
    default: true
    env:
      MLC_GIT_REPO_URL: https://bitbucket.org/gyrokinetics/gs2.git
    group: repo
  tag.#:
    env:
      MLC_GIT_CHECKOUT_TAG: '#'
    group: version
  branch.#:
    env:
      MLC_GIT_CHECKOUT: '#'
    group: version
  version.8.0.1:
    default: true
    group: version
    env:
      MLC_GIT_CHECKOUT_TAG: v8.0.1

# Tests
tests:
  run_inputs: []
