alias: get-intel-sde-tool
automation_alias: script
automation_uid: 5b4e0237da074764
category: MLC Utils
cache: True
deps:
  - tags: detect,os
  - tags: download-and-extract,_extract
    enable_if_env:
      MLC_DOWNLOAD_URL:
        - on
    skip_if_env:
      MLC_INTEL_SDE_DIR_PATH:
        - on
    update_tags_from_env_with_prefix:
      _url.:
        - MLC_DOWNLOAD_URL
    extra_cache_tags: intel,sde,tool
    force_cache: True
    
new_env_keys:
  - MLC_INTEL_SDE_DIR_PATH
  - MLC_INTEL_SDE_BIN_WITH_PATH
  - MLC_INTEL_SDE_VERSION
  - +PATH
new_state_keys: []
post_deps: []
posthook_deps: []
tags:
- get
- tool
- sde
- intel
input_mapping:
  sde_dir: MLC_INTEL_SDE_DIR_PATH
uid: 3546409e71c847bc
variations:
  version.9_53_0:
    group: version
    default: true
    env:
      MLC_DOWNLOAD_URL: https://downloadmirror.intel.com/850782/sde-external-9.53.0-2025-03-16-lin.tar.xz
tests:
  run_inputs:
    - {}


