alias: clean-nvidia-mlperf-inference-scratch-space
uid: bb41f6e3608e4e8a
automation_alias: script
automation_uid: 5b4e0237da074764

# Metadata
tags:
- clean
- nvidia
- scratch
- space
- mlperf
- inference

# Cache
cache: false

# Input mapping
input_mapping:
  extra_cache_rm_tags: MLC_CLEAN_EXTRA_CACHE_RM_TAGS

# Dependencies
deps:
- tags: get,mlperf,inference,nvidia,scratch,space
  names:
  - nvidia-scratch-space

# Variations
variations:
  downloaded-data:
    group: artifact
    env:
      MLC_CLEAN_ARTIFACT_NAME: downloaded_data
  downloaded-model:
    group: artifact
    env:
      MLC_CLEAN_ARTIFACT_NAME: models
  models:
    group: artifact
    env:
      MLC_CLEAN_ARTIFACT_NAME: models
  preprocessed-data:
    group: artifact
    env:
      MLC_CLEAN_ARTIFACT_NAME: preprocessed_data
  3d-unet-99:
    group: model
    env:
      MLC_MODEL: 3d-unet-99
  3d-unet-99.9:
    group: model
    env:
      MLC_MODEL: 3d-unet-99.9
  bert-99:
    group: model
    env:
      MLC_MODEL: bert-99
  bert-99.9:
    group: model
    env:
      MLC_MODEL: bert-99.9
  dlrm-v2-99:
    group: model
    env:
      MLC_MODEL: dlrm-v2-99
  dlrm-v2-99.9:
    group: model
    env:
      MLC_MODEL: dlrm-v2-99.9
  gptj-99:
    group: model
    env:
      MLC_MODEL: gptj-99
  gptj-99.9:
    group: model
    env:
      MLC_MODEL: gptj-99.9
  llama2-70b-99:
    group: model
    env:
      MLC_MODEL: llama2-70b-99
  llama2-70b-99.9:
    group: model
    env:
      MLC_MODEL: llama2-70b-99.9
  resnet50:
    group: model
    env:
      MLC_MODEL: resnet50
  retinanet:
    group: model
    env:
      MLC_MODEL: retinanet
  rnnt:
    group: model
    env:
      MLC_MODEL: rnnt
  sdxl:
    group: model
    env:
      MLC_MODEL: sdxl
  stable-diffusion-xl:
    group: model
    env:
      MLC_MODEL: stable-diffusion-xl
  v4.0:
    group: version
    env:
      MLC_NVIDIA_MLPERF_INFERENCE_CODE_VERSION: v4.0
  v4.1:
    group: version
    env:
      MLC_NVIDIA_MLPERF_INFERENCE_CODE_VERSION: v4.1
