alias: get-lib-qaic-api
uid: 1e253ae184e44f23
automation_alias: script
automation_uid: 5b4e0237da074764

# Metadata
category: Detection or installation of tools and artifacts
tags:
- get
- api
- lib-qaic-api
- lib
- qaic

# Cache
cache: true

# Environment
env: {}
new_env_keys:
- MLC_LIB_QAIC_*
- MLC_QAIC_API_*
- +C_INCLUDE_PATH
- +CPLUS_INCLUDE_PATH
- +LD_LIBRARY_PATH

# Dependencies
deps:
- tags: detect,os
prehook_deps: []

# Versions
default_version: master
versions:
  master:
    env:
      MLC_LIB_QAIC_VERSION: master
