alias: get-ml-model-deeplabv3-plus
automation_alias: script
automation_uid: 5b4e0237da074764
cache: true
tags:
- get
- ml-model
- deeplab
- v3-plus
- deeplabv3-plus
uid: cfb2d53b9dbc4dc0
new_env_keys:
  - MLC_ML_MODEL_DEEPLABV3_PLUS_PATH
  - MLC_ML_MODEL_FILE_WITH_PATH
print_env_at_the_end:
  MLC_ML_MODEL_DEEPLABV3_PLUS_PATH: DeepLabV3+ checkpoint path
variations:
  onnx:
    group: model-format
    default: true
    env:
      MLC_MODEL_FORMAT: onnx
      MLC_MODEL_RCLONE_FILEPATH: model_checkpoint_deeplab/deeplabv3+_8mp.onnx
      MLC_ML_MODEL_FILENAME: deeplabv3+_8mp.onnx
  dynamic: {}
  onnx,dynamic:
    group: model-format
    env:
      MLC_MODEL_FORMAT: onnx
      MLC_MODEL_RCLONE_FILEPATH: model_checkpoint_deeplab/deeplabv3+_dynamic.onnx
      MLC_ML_MODEL_FILENAME: deeplabv3+_dynamic.onnx
  pytorch:
    group: model-format
    env:
      MLC_MODEL_FORMAT: pth
      MLC_MODEL_RCLONE_FILEPATH: model_checkpoint_deeplab/latest_deeplabv3plus_resnet50_cognata_os16_it100000.pth
      MLC_ML_MODEL_FILENAME: latest_deeplabv3plus_resnet50_cognata_os16_it100000.pth
  mlc:
    group: download-src
    default: true
    prehook_deps:
      - tags: get,rclone
        enable_if_env:
          MLC_TMP_REQUIRE_DOWNLOAD:
          - yes
      - tags: get,rclone-config,_config-name.cognata
        force_cache: true
        enable_if_env:
          MLC_TMP_REQUIRE_DOWNLOAD:
          - yes
        env:
          MLC_RCLONE_DRIVE_FOLDER_ID: 1u5FDoeXHVtDrd4zClE47Gmyr7iLFidz1
      - enable_if_env:
          MLC_TMP_REQUIRE_DOWNLOAD:
          - 'yes'
        env:
          MLC_DOWNLOAD_FINAL_ENV_NAME: MLC_ML_MODEL_DEEPLABV3_PLUS_PATH
          MLC_EXTRACT_FINAL_ENV_NAME: MLC_ML_MODEL_DEEPLABV3_PLUS_PATH
          MLC_DOWNLOAD_URL: 'mlc-cognata:mlc_cognata_dataset/<<<MLC_MODEL_RCLONE_FILEPATH>>>'
          MLC_DOWNLOAD_EXTRA_OPTIONS: ' --include '
        extra_cache_tags: ml,model,deeplabv3,plus
        force_cache: true
        names:
          - dae
        tags: download-and-extract
        force_env_keys:
          - MLC_OUTDIRNAME  
        update_tags_from_env_with_prefix:
          _url.:
            - MLC_DOWNLOAD_URL
    env:
      MLC_DOWNLOAD_SRC: mlcommons
  rclone:
    group: download-tool
    add_deps_recursive:
      dae:
        tags: _rclone
    default: true
  dry-run:
    group: run-mode
    env:
      MLC_DOWNLOAD_MODE: dry
  dry-run,rclone:
    env:
      MLC_DOWNLOAD_EXTRA_OPTIONS: --dry-run
tests:
  needs_pat: true
  run_inputs:
  - variations_list:
      - onnx,rclone,mlc,dry-run
      - onnx_dynamic,rclone,mlc,dry-run
      - pytorch,rclone,mlc,dry-run