alias: get-mlperf-inference-utils
uid: e341e5f86d8342e5
automation_alias: script
automation_uid: 5b4e0237da074764

# Metadata
tags:
- get
- mlperf
- inference
- util
- utils
- functions

# Cache
cache: false

# Environment
new_env_keys:
- +PYTHONPATH

# Dependencies
deps:
- tags: get,mlperf,inference,src
  names:
  - inference-src
