alias: app-epoch
uid: 31f3d78fa6980c3c
automation_alias: script
automation_uid: 5b4e0237da074764

# Metadata
category: HPC Application

tags:
- app
- epoch
- hpc

# Cache
cache: true

# Environment
default_env: {}
new_env_keys:
- MLC_EPOCH_SRC_PATH
- MLC_EPOCH_INSTALL_PATH
- MLC_EPOCH_BIN_PATH
- +PATH
new_state_keys: []

# Dependencies
deps:
- tags: detect,cpu
- env:
    MLC_GENERIC_SYS_UTIL_IGNORE_MISSING_PACKAGE: true
  tags: get,generic-sys-util,_build-essential
- tags: get,generic-sys-util,_gfortran
- tags: get,generic-sys-util,_libopenmpi-dev
- tags: get,python3
  names:
  - python
  - python3
- tags: get,git,repo
  names:
  - epoch-repo
  extra_cache_tags: epoch,repo,epoch-repo
  env:
    MLC_GIT_CHECKOUT_PATH_ENV_NAME: MLC_EPOCH_SRC_PATH
  force_env_keys:
  - MLC_GIT_*
  update_tags_from_env_with_prefix:
    _branch.:
    - MLC_GIT_CHECKOUT
    _repo.:
    - MLC_GIT_REPO_URL
    _tag.:
    - MLC_GIT_CHECKOUT_TAG
prehook_deps: []
posthook_deps: []
post_deps: []

# Variations
variations:
  repo.#:
    env:
      MLC_GIT_REPO_URL: '#'
    group: repo
  repo.official:
    default: true
    env:
      MLC_GIT_REPO_URL: https://github.com/Warwick-Plasma/epoch.git
    group: repo
  tag.#:
    env:
      MLC_GIT_CHECKOUT_TAG: '#'
    group: version
  branch.#:
    env:
      MLC_GIT_CHECKOUT: '#'
    group: version
  version.4.20.1:
    default: true
    group: version
    env:
      MLC_GIT_CHECKOUT_TAG: v4.20.1

# Tests
tests:
  run_inputs:
  - variations_list:
    - repo.official
