alias: gemini_call
uid: 1cfe3d0658364a2b
automation_alias: script
automation_uid: 5b4e0237da074764

# Metadata
category: MLC Script Template
tags:
- gemini-call
- query

# Environment
new_env_keys: []
new_state_keys:
- MLC_GEMINI_RESPONSE

# Input mapping
input_mapping:
  api_key: MLC_GEMINI_API_KEY
  config_path: MLC_GEMINI_CONFIG_PATH
  model: MLC_GEMINI_MODEL
  system_prompt: MLC_GEMINI_SYSTEM_PROMPT
  user_prompt: MLC_GEMINI_USER_PROMPT

# Dependencies
deps:
- tags: get,python3
  names:
  - python
  - python3
prehook_deps: []
posthook_deps: []
post_deps: []

# Variations
variations:
  gemini:
    group: api_provider
    default: true
    env:
      MLC_GEMINI_API_URL: https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key=

# Tests
tests:
  run_inputs: []
