alias: get-git-repo
uid: ed603e7292974f10
automation_alias: script
automation_uid: 5b4e0237da074764

# Metadata
category: DevOps automation
tags:
- get
- git
- repo
- repository
- clone

# Cache
cache: true
cache_expiration: 5d

# Environment
default_env:
  MLC_GIT_CHECKOUT_FOLDER: repo
  MLC_GIT_DEPTH: --depth 4
  MLC_GIT_PATCH: 'no'
  MLC_GIT_RECURSE_SUBMODULES: ' --recurse-submodules'
  MLC_GIT_URL: https://github.com/mlcommons/mlperf-automations
new_env_keys:
- MLC_GIT_CHECKOUT_PATH
- MLC_GIT_REPO_*
- <<<MLC_GIT_CHECKOUT_PATH_ENV_NAME>>>
- <<<MLC_GIT_REPO_VERSION_ENV_NAME>>>

# Input mapping
input_mapping:
  branch: MLC_GIT_CHECKOUT
  depth: MLC_GIT_DEPTH
  env_key: MLC_GIT_ENV_KEY
  folder: MLC_GIT_CHECKOUT_FOLDER
  patch: MLC_GIT_PATCH
  pull: MLC_GIT_REPO_PULL
  submodules: MLC_GIT_RECURSE_SUBMODULES
  update: MLC_GIT_REPO_PULL

# Dependencies
deps:
- tags: detect,os
post_deps:
- dynamic: true
  enable_if_env:
    MLC_GIT_REPO_PULL:
    - 'yes'
    - 'True'
  force_env_keys:
  - MLC_GIT_CHECKOUT_PATH
  names:
  - pull-git-repo
  tags: pull,git,repo

# Variations
variations:
  branch.#:
    env:
      MLC_GIT_BRANCH: '#'
    group: checkout
  tag.#:
    cache_expiration: 500d
    env:
      MLC_GIT_CHECKOUT_TAG: '#'
    group: checkout
  full-history:
    env:
      MLC_GIT_DEPTH: ''
    group: git-history
  short-history:
    default: true
    env:
      MLC_GIT_DEPTH: --depth 5
    group: git-history
  sha.#:
    cache_expiration: 500d
    default_variations:
      git-history: full-history
    env:
      MLC_GIT_SHA: '#'
    group: post-checkout
  repo.#:
    env:
      MLC_GIT_URL: '#'
    group: repo
  cherrypicks.#:
    env:
      MLC_GIT_CHERRYPICKS: '#'
  lfs:
    deps:
    - tags: get,generic,sys-util,_git-lfs
    env:
      MLC_GIT_REPO_NEEDS_LFS: 'yes'
  no-recurse-submodules:
    env:
      MLC_GIT_RECURSE_SUBMODULES: ''
  patch:
    env:
      MLC_GIT_PATCH: 'yes'
  patch.#:
    env:
      MLC_GIT_PATCH: 'yes'
      +,MLC_GIT_PATCH_FILEPATHS:
      - '#'
  pr-to-apply.#:
    env:
      MLC_GIT_PR_TO_APPLY: '#'
  submodules.#:
    env:
      MLC_GIT_SUBMODULES: '#'

# Output / debugging
print_env_at_the_end:
  MLC_GIT_CHECKOUT_PATH: MLC cache path to the Git repo

# Tests
tests:
  run_inputs:
  - variations_list:
    - repo.https://github.com/octocat/Hello-World,no-recurse-submodules
  - variations_list:
    - repo.https://github.com/octocat/Hello-World,branch.test,no-recurse-submodules
  - variations_list:
    - repo.https://github.com/octocat/Hello-World,sha.7fd1a60b01f91b314f59955a4e4d4e80d8edf11d,no-recurse-submodules
  - variations_list:
    - repo.https://github.com/octocat/Hello-World,full-history,no-recurse-submodules
  - variations_list:
    - repo.https://github.com/pallets/click,tag.8.3.2,short-history,no-recurse-submodules
