alias: get-lib-armnn
automation_alias: script
automation_uid: 5b4e0237da074764
cache: true
category: Detection or installation of tools and artifacts
default_version: '25.02'
deps:
- tags: detect,os
env:
  MLC_GIT_URL: https://github.com/ARM-software/armnn
new_env_keys:
- MLC_LIB_ARMNN_VERSION
- MLC_LIB_DNNL_*
- +C_INCLUDE_PATH
- +CPLUS_INCLUDE_PATH
- +LD_LIBRARY_PATH
prehook_deps:
- force_env_keys:
  - MLC_GIT_*
  tags: get,git,repo,_repo.https://github.com/ARM-software/armnn
tags:
- get
- lib-armnn
- lib
- armnn
uid: 9603a2e90fd44587
versions:
  '22.11':
    env:
      MLC_LIB_ARMNN_VERSION: v22.11
      MLC_TMP_GIT_BRANCH_NAME: branches/armnn_22_11
  '23.05':
    env:
      MLC_LIB_ARMNN_VERSION: v23.05
      MLC_TMP_GIT_BRANCH_NAME: branches/armnn_23_05
  '23.11':
    env:
      MLC_LIB_ARMNN_VERSION: v23.11
      MLC_TMP_GIT_BRANCH_NAME: branches/armnn_23_11
  '25.02':
    env:
      MLC_LIB_ARMNN_VERSION: v23.11
      MLC_TMP_GIT_BRANCH_NAME: branches/armnn_23_11
