alias: kill-process
automation_alias: script
automation_uid: 5b4e0237da074764
category: MLC Script Template
deps: []
new_env_keys: []
new_state_keys: []
post_deps: []
posthook_deps: []
prehook_deps: []
tags:
- kill
- process
tests:
  run_inputs: []
uid: 27b5651692454cb6
input_mapping:
  group: MLC_KILL_PROCESS_GROUP
  pid: MLC_KILL_PROCESS_ID
  pname: MLC_KILL_PROCESS_NAME
  

