alias: get-mlperf-inference-nvidia-common-code
automation_alias: script
automation_uid: 5b4e0237da074764
cache: true
category: MLPerf benchmark support
clean_files: []
deps:
- inherit_variation_tags: true
  names:
  - mlperf-inference-results
  tags: get,mlperf,inference,results,official
new_env_keys:
- +PYTHONPATH
- MLC_MLPERF_INFERENCE_NVIDIA_CODE_PATH
tags:
- get
- nvidia
- mlperf
- inference
- common-code
uid: 26b78bf3ffdc4926
variations:
  custom:
    group: repo-owner
    adr:
      mlperf-inference-results:
        tags: _custom
  go:
    group: repo-owner
    adr:
      mlperf-inference-results:
        tags: _go
  mlcommons:
    default: true
    group: repo-owner
    adr:
      mlperf-inference-results:
        tags: _mlcommons
  nvidia-only:
    group: repo-owner
    adr:
      mlperf-inference-results:
        tags: _nvidia-only
  v5.0:
    add_deps_recursive:
      mlperf-inference-results:
        tags: _code-only,_v5.0
  v5.1-dev:
    add_deps_recursive:
      mlperf-inference-results:
        tags: _code-only-for-v5.1,_v5.1-dev
versions:
  r2.1:
    add_deps_recursive:
      mlperf-inference-results:
        version: v2.1
        tags: _code-only
  r3.0:
    add_deps_recursive:
      mlperf-inference-results:
        version: v3.0
        tags: _code-only
  r3.1:
    add_deps_recursive:
      mlperf-inference-results:
        version: v3.1
        tags: _code-only
  r4.0:
    add_deps_recursive:
      mlperf-inference-results:
        version: v4.0
        tags: _code-only
  r4.1:
    add_deps_recursive:
      mlperf-inference-results:
        version: v4.1
        tags: _code-only
  r4.1-dev:
    add_deps_recursive:
      mlperf-inference-results:
        version: v4.0
        tags: _code-only-for-v5.0
