alias: runtime-system-infos
uid: 755cf27627784001
cache: false
automation_alias: script
automation_uid: 5b4e0237da074764
category: MLPerf Inference
docker:
  real_run: false
tags:
- runtime
- system
- utilisation
- infos
input_mapping:
  interval: MLC_SYSTEM_INFO_MEASUREMENT_INTERVAL
  log_dir: MLC_LOGS_DIR
deps:
- tags: detect,os
- tags: detect,cpu
- tags: get,sys-utils-mlc
- tags: get,python3
  names:
  - python
  - python3
variations:
  all:
    group: devices
  cpu:
    group: devices
  cuda:
    group: devices
