alias: get-dataset-criteo
uid: 194a47d908714897
automation_alias: script
automation_uid: 5b4e0237da074764

# Metadata
category: AI/ML datasets
tags:
- get
- dataset
- criteo
- original

# Cache
cache: true

# Environment
default_env:
  MLC_BACKUP_ZIPS: 'no'
env:
  MLC_DATASET: terabyte
new_env_keys:
- MLC_DATASET*

# Input mapping
input_mapping:
  criteo_path: MLC_CRITEO_PATH

# Variations
variations:
  backup:
    env:
      MLC_BACKUP_ZIPS: 'yes'
  fake:
    env:
      MLC_CRITEO_FAKE: 'yes'
