alias: get-preprocessed-dataset-criteo
automation_alias: script
automation_uid: 5b4e0237da074764
cache: true
category: AI/ML datasets
deps:
- names:
  - python3
  - python
  tags: get,python3
- names:
  - original-dataset
  - criteo-dataset
  skip_if_env:
    MLC_DATASET_PREPROCESSED_PATH:
    - 'on'
  tags: get,dataset,criteo,original
- names:
  - dlrm-src
  skip_if_env:
    MLC_DATASET_PREPROCESSED_PATH:
    - 'on'
  tags: get,dlrm,src
- names:
  - inference-src
  skip_if_env:
    MLC_DATASET_PREPROCESSED_PATH:
    - 'on'
  tags: mlperf,mlcommons,inference,source,src
- skip_if_env:
    MLC_DATASET_PREPROCESSED_PATH:
    - 'on'
  tags: get,generic-python-lib,_scikit-learn
- skip_if_env:
    MLC_DATASET_PREPROCESSED_PATH:
    - 'on'
  tags: get,generic-python-lib,_torch
- skip_if_env:
    MLC_DATASET_PREPROCESSED_PATH:
    - 'on'
  tags: get,generic-python-lib,_opencv-python
- skip_if_env:
    MLC_DATASET_PREPROCESSED_PATH:
    - 'on'
  tags: get,generic-python-lib,_decorator
- skip_if_env:
    MLC_DATASET_PREPROCESSED_PATH:
    - 'on'
  tags: get,generic-python-lib,_psutil
- skip_if_env:
    MLC_DATASET_PREPROCESSED_PATH:
    - 'on'
  tags: get,generic-python-lib,_onnx
- skip_if_env:
    MLC_DATASET_PREPROCESSED_PATH:
    - 'on'
  tags: get,generic-python-lib,_tqdm
- skip_if_env:
    MLC_DATASET_PREPROCESSED_PATH:
    - 'on'
  tags: get,generic-python-lib,_mlperf_logging
docker:
  run: false
input_mapping:
  dir: MLC_DATASET_PREPROCESSED_PATH
  output_dir: MLC_DATASET_PREPROCESSED_OUTPUT_PATH
  threads: MLC_NUM_PREPROCESS_THREADS
new_env_keys:
- MLC_DATASET_PREPROCESSED_PATH
- MLC_DATASET_CRITEO_MULTIHOT
- MLC_CRITEO_PREPROCESSED_PATH
tags:
- get
- dataset
- criteo
- recommendation
- dlrm
- preprocessed
uid: afa59956272a4ba4
variations:
  '1':
    env:
      MLC_DATASET_SIZE: '1'
  '50':
    env:
      MLC_DATASET_SIZE: '50'
  fake:
    add_deps_recursive:
      original-dataset:
        tags: _fake
    env:
      MLC_CRITEO_FAKE: 'yes'
  full:
    add_deps_recursive:
      original-dataset:
        tags: -_fake
    env: {}
  mlc:
    default: true
    env:
      MLC_DATASET_PREPROCESSED_CRITEO_FROM_MLC: 'yes'
      MLC_DATASET_PREPROCESSED_PATH: 'on'
    group: src
  multihot:
    default: true
    deps:
    - names:
      - mlperf-training
      - training-src
      skip_if_env:
        MLC_DATASET_PREPROCESSED_CRITEO_FROM_MLC:
        - 'yes'
      tags: get,mlperf,training,src
    - skip_if_env:
        MLC_DATASET_PREPROCESSED_CRITEO_FROM_MLC:
        - 'yes'
      tags: get,generic-python-lib,_package.typing_inspect
    - skip_if_env:
        MLC_DATASET_PREPROCESSED_CRITEO_FROM_MLC:
        - 'yes'
      tags: get,generic-python-lib,_package.iopath
    - skip_if_env:
        MLC_DATASET_PREPROCESSED_CRITEO_FROM_MLC:
        - 'yes'
      tags: get,generic-python-lib,_package.fbgemm_gpu
    - skip_if_env:
        MLC_DATASET_PREPROCESSED_CRITEO_FROM_MLC:
        - 'yes'
      tags: get,generic-python-lib,_package.torchrec
    - skip_if_env:
        MLC_DATASET_PREPROCESSED_CRITEO_FROM_MLC:
        - 'yes'
      tags: get,generic-python-lib,_package.pyre_extensions
    env:
      MLC_DATASET_CRITEO_MULTIHOT: 'yes'
    group: type
  multihot,mlc:
    deps:
    - env:
        MLC_DOWNLOAD_CHECKSUM_FILE: <<<MLC_TMP_CURRENT_SCRIPT_PATH>>>/checksums.txt
        MLC_DOWNLOAD_FINAL_ENV_NAME: MLC_DATASET_PREPROCESSED_PATH
        MLC_EXTRACT_FINAL_ENV_NAME: MLC_DATASET_PREPROCESSED_PATH
        MLC_EXTRACT_TO_FOLDER: criteo-preprocessed
        MLC_RCLONE_CONFIG_NAME: mlc-inference
        MLC_DOWNLOAD_URL: mlc-inference:mlcommons-inference-wg-public/dlrm_preprocessed
      extra_cache_tags: criteo,preprocessed,dataset
      force_cache: true
      names:
      - dae
      tags: download-and-extract
      update_tags_from_env_with_prefix:
          _url.:
            - MLC_DOWNLOAD_URL
  rclone:
    group: download-tool
    add_deps_recursive:
      dae:
        tags: _rclone
    default: true
  dry-run:
    group: run-mode
    env:
      MLC_DOWNLOAD_MODE: dry
  dry-run,rclone:
    env:
      MLC_DOWNLOAD_EXTRA_OPTIONS: --dry-run
  preprocess:
    group: src
  validation:
    add_deps:
      original-dataset:
        tags: _validation
