alias: get-xilinx-sdk
uid: 76d4d1bd09df4490
automation_alias: script
automation_uid: 5b4e0237da074764

# Metadata
category: Detection or installation of tools and artifacts
tags:
- get
- xilinx
- sdk

# Cache
cache: true

# Environment
new_env_keys:
- MLC_XILINX_*
- +PATH
new_state_keys: []

# Input mapping
input_mapping:
  input: MLC_XILINX_SDK_FILE_PATH
input_description: {}

# Dependencies
deps: []
posthook_deps: []
post_deps: []

# Variations
variations: {}

# Versions
default_version: '2019.1'
versions:
  '2019.1':
    env:
      MLC_DOWNLOAD_CHECKSUM: 7ccb3840d36c305a7cb34b314db7d7f2
      MLC_DOWNLOAD_URL: https://www.xilinx.com/member/forms/download/xef.html?filename=Xilinx_SDK_2019.1_0524_1430_Lin64.bin
