alias: app-nek5000
uid: 4029f591f6061e1e
automation_alias: script
automation_uid: 5b4e0237da074764

# Metadata
category: HPC Application
tags:
- app
- nek5000
- nek
- hpc

# Cache
cache: true

# Environment
default_env: {}
new_env_keys:
- MLC_NEK5000_SRC_PATH
- MLC_NEK5000_INSTALL_PATH
- MLC_NEK5000_BIN_PATH
- +PATH
new_state_keys: []

# Dependencies
deps:
- tags: detect,cpu
- env:
    MLC_GENERIC_SYS_UTIL_IGNORE_MISSING_PACKAGE: true
  tags: get,generic-sys-util,_build-essential
- tags: get,generic-sys-util,_gfortran
- tags: get,git,repo
  names:
  - nek5000-repo
  extra_cache_tags: nek5000,repo,nek5000-repo
  env:
    MLC_GIT_CHECKOUT_PATH_ENV_NAME: MLC_NEK5000_SRC_PATH
  force_env_keys:
  - MLC_GIT_*
  update_tags_from_env_with_prefix:
    _branch.:
    - MLC_GIT_CHECKOUT
    _repo.:
    - MLC_GIT_REPO_URL
    _tag.:
    - MLC_GIT_CHECKOUT_TAG
prehook_deps: []
posthook_deps: []
post_deps: []

# Variations
variations:
  repo.#:
    env:
      MLC_GIT_REPO_URL: '#'
    group: repo
  repo.official:
    default: true
    env:
      MLC_GIT_REPO_URL: https://github.com/Nek5000/Nek5000.git
    group: repo
  tag.#:
    env:
      MLC_GIT_CHECKOUT_TAG: '#'
    group: version
  branch.#:
    env:
      MLC_GIT_CHECKOUT: '#'
    group: version
  version.19.0:
    default: true
    group: version
    env:
      MLC_GIT_CHECKOUT_TAG: v19.0

# Tests
tests:
  run_inputs:
  - variations_list:
    - repo.official
