alias: get-llvm
automation_alias: script
automation_uid: 5b4e0237da074764
cache: true
category: Compiler automation
clean_files: []
env:
  MLC_REQUIRE_INSTALL: 'no'
name: Detect or install LLVM compiler
new_env_keys:
- MLC_LLVM_*
- MLC_C_COMPILER_*
- MLC_CXX_COMPILER_*
- MLC_COMPILER_*
- MLC_LINKER_*
- + CFLAGS
- + CXXFLAGS
- + FFLAGS
- + LDFLAGS
- +MLC_HOST_OS_DEFAULT_INCLUDE_PATH
- +PATH
post_deps:
- tags: get,compiler-flags
prehook_deps:
- enable_if_env:
    MLC_REQUIRE_INSTALL:
    - 'yes'
  names: llvm-install
  reuse_version: true
  inherit_variation_tags: true
  skip_inherit_variation_groups:
    - install-src
  tags: install,llvm
sort: 100
tags:
- get
- llvm
- compiler
- c-compiler
- cpp-compiler
- get-llvm
uid: 99832a103ed04eb8
variations:
  from-prebuilt:
    group: install-src
    default: true
    ad:
      llvm-install:
        tags: prebuilt
  from-src:
    group: install-src
    ad:
      llvm-install:
        tags: src,_clang
  path.#:
    env:
      MLC_LLVM_DIR_PATH: '#'
  release: {}
  version.#: {}
  branch.#: {}
  runtimes.#: {}
  flang: {}
  sha.#: {}
  tag.#: {}

