alias: get-llvm
uid: 99832a103ed04eb8
automation_alias: script
automation_uid: 5b4e0237da074764
name: Detect or install LLVM compiler
category: Compiler automation
tags:
- get
- llvm
- compiler
- c-compiler
- cpp-compiler
- get-llvm
cache: true
clean_files: []
env:
  MLC_REQUIRE_INSTALL: 'no'
new_env_keys:
- MLC_LLVM_*
- MLC_C_COMPILER_*
- MLC_CXX_COMPILER_*
- MLC_COMPILER_*
- MLC_LINKER_*
- + CFLAGS
- + CXXFLAGS
- + FFLAGS
- + LDFLAGS
- +MLC_HOST_OS_DEFAULT_INCLUDE_PATH
- +PATH
prehook_deps:
- enable_if_env:
    MLC_REQUIRE_INSTALL:
    - 'yes'
  names: llvm-install
  reuse_version: true
  inherit_variation_tags: true
  skip_inherit_variation_groups:
  - install-src
  tags: install,llvm
post_deps:
- tags: get,compiler-flags
variations:
  from-prebuilt:
    group: install-src
    default: true
    ad:
      llvm-install:
        tags: prebuilt
  from-src:
    group: install-src
    ad:
      llvm-install:
        tags: src,_clang
  branch.#: {}
  flang: {}
  path.#:
    env:
      MLC_LLVM_DIR_PATH: '#'
      MLC_TMP_LLVM_FORCE_GIVEN_PATH: 'yes'
  release: {}
  runtimes.#: {}
  sha.#: {}
  tag.#: {}
  version.#: {}
  custom-flags.#:
    env:
      MLC_LLVM_CUSTOM_FLAGS: '#'
sort: 100
