alias: app-mlperf-training-nvidia
uid: 1e2e357618cc4674
automation_alias: script
automation_uid: 5b4e0237da074764
category: MLPerf Training
tags:
- app
- vision
- language
- mlcommons
- mlperf
- training
- nvidia
default_env:
  MLC_MLPERF_SUT_NAME_IMPLEMENTATION_PREFIX: nvidia
input_mapping:
  clean: MLC_MLPERF_CLEAN_SUBMISSION_DIR
  docker: MLC_RUN_DOCKER_CONTAINER
  hw_name: MLC_HW_NAME
  model: MLC_MLPERF_CUSTOM_MODEL_PATH
  num_threads: MLC_NUM_THREADS
  output_dir: OUTPUT_BASE_DIR
  rerun: MLC_RERUN
new_env_keys:
- MLC_MLPERF_*
- MLC_DATASET_*
- MLC_HW_NAME
- MLC_ML_MODEL_*
new_state_keys:
- mlperf-inference-implementation
- MLC_SUT_*
deps:
- tags: detect,os
- tags: detect,cpu
- tags: get,sys-utils-mlc
- tags: get,python
  names:
  - python
  - python3
- tags: get,mlperf,training,src
  names:
  - training-src
  - mlperf-training-src
- tags: get,git,repo,_repo.https://github.com/mlcommons/training_results_v2.1
  extra_cache_tags: mlperf,training,results,v2.1
  names:
  - training-results
  - mlperf-training-results
- tags: get,cuda
  enable_if_env:
    MLC_MLPERF_DEVICE:
    - cuda
- tags: get,generic-python-lib,_torchvision_cuda
  names:
  - ml-engine-torchvision
  enable_if_env:
    MLC_MLPERF_BACKEND:
    - pytorch
    MLC_MLPERF_DEVICE:
    - cuda
- tags: get,generic-python-lib,_mlperf_logging
- tags: prepare,mlperf,training,data,bert,_nvidia
  names:
  - prepare-data
  - bert-model
  enable_if_env:
    MLC_MLPERF_MODEL:
    - bert
variations:
  cuda:
    group: device
    default: true
    env:
      MLC_MLPERF_DEVICE: cuda
      USE_CUDA: true
  tpu:
    group: device
    env:
      MLC_MLPERF_DEVICE: tpu
      CUDA_VISIBLE_DEVICES: ''
      USE_CUDA: false
  pytorch:
    group: framework
    env:
      MLC_MLPERF_BACKEND: pytorch
      MLC_MLPERF_BACKEND_VERSION: <<<MLC_TORCH_VERSION>>>
  tf:
    group: framework
    env:
      MLC_MLPERF_BACKEND: tf
      MLC_MLPERF_BACKEND_VERSION: <<<MLC_TENSORFLOW_VERSION>>>
  bert:
    env:
      MLC_MLPERF_MODEL: bert
    deps:
    - tags: get,generic-python-lib,_protobuf
      names:
      - protobuf
      version_max: '3.19'
      enable_if_env:
        MLC_MLPERF_BACKEND:
        - tf
        - tflite
    - tags: get,generic-python-lib,_torch
      names:
      - ml-engine-pytorch
  tensorflow:
    alias: tf
