# Identification of this MLC script
alias: app-mlperf-training-nvidia
uid: 1e2e357618cc4674

automation_alias: script
automation_uid: 5b4e0237da074764

category: "Modular MLPerf training benchmark pipeline"

# User-friendly tags to find this MLC script
tags:
  - app
  - vision
  - language
  - mlcommons
  - mlperf
  - training
  - nvidia

# Default environment
default_env:
  MLC_MLPERF_SUT_NAME_IMPLEMENTATION_PREFIX: nvidia

# Map script inputs to environment variables
input_mapping:
  docker: MLC_RUN_DOCKER_CONTAINER
  hw_name: MLC_HW_NAME
  num_threads: MLC_NUM_THREADS
  model: MLC_MLPERF_CUSTOM_MODEL_PATH
  output_dir: OUTPUT_BASE_DIR
  rerun: MLC_RERUN
  clean: MLC_MLPERF_CLEAN_SUBMISSION_DIR


# Env keys which are exposed to higher level scripts
new_env_keys:
  - MLC_MLPERF_*
  - MLC_DATASET_*
  - MLC_HW_NAME
  - MLC_ML_MODEL_*

new_state_keys:
  - mlperf-inference-implementation
  - MLC_SUT_*

# Dependencies on other MLC scripts
deps:

  # Detect host OS features
  - tags: detect,os

  # Detect host CPU features
  - tags: detect,cpu

  # Install system dependencies on a given host
  - tags: get,sys-utils-mlc

  # Detect/install python
  - tags: get,python
    names:
    - python
    - python3

  # Get MLPerf training source
  - tags: get,mlperf,training,src
    names:
    - training-src
    - mlperf-training-src

        
  - tags: get,git,repo,_repo.https://github.com/mlcommons/training_results_v2.1
    extra_cache_tags: mlperf,training,results,v2.1
    names:
    - training-results
    - mlperf-training-results

  # Detect CUDA if required
  - tags: get,cuda
    enable_if_env:
      MLC_MLPERF_DEVICE:
      - cuda


  ## Torchvision (CUDA)
  - tags: get,generic-python-lib,_torchvision_cuda
    names:
    - ml-engine-torchvision
    enable_if_env:
      MLC_MLPERF_BACKEND:
      - pytorch
      MLC_MLPERF_DEVICE:
      - cuda

  - tags: get,generic-python-lib,_mlperf_logging


  ########################################################################
  # Prepare Data 

  ## BERT
  - tags: prepare,mlperf,training,data,bert,_nvidia
    names:
    - prepare-data
    - bert-model
    enable_if_env:
      MLC_MLPERF_MODEL:
      - bert



# Variations to customize dependencies
variations:
  pytorch:
    group: framework
    env:
      MLC_MLPERF_BACKEND: pytorch
      MLC_MLPERF_BACKEND_VERSION: <<<MLC_TORCH_VERSION>>>

  tf:
    group: framework
    env:
      MLC_MLPERF_BACKEND: tf
      MLC_MLPERF_BACKEND_VERSION: <<<MLC_TENSORFLOW_VERSION>>>

  tensorflow:
    alias: tf

  # Reference MLPerf models
  bert:
    env:
      MLC_MLPERF_MODEL: bert
    deps:
    - tags: get,generic-python-lib,_protobuf
      names:
      - protobuf
      version_max: "3.19"
      enable_if_env:
        MLC_MLPERF_BACKEND:
        - tf
        - tflite
    - tags: get,generic-python-lib,_torch
      names:
      - ml-engine-pytorch
  tpu:
    group: device
    env:
      MLC_MLPERF_DEVICE: tpu
      CUDA_VISIBLE_DEVICES: ''
      USE_CUDA: no

  cuda:
    group: device
    default: true
    env:
      MLC_MLPERF_DEVICE: cuda
      USE_CUDA: yes
