alias: install-mmcv-from-src
automation_alias: script
automation_uid: 5b4e0237da074764
cache: true
category: Compiler automation
deps:
- tags: detect,os
- tags: detect,cpu
- names:
  - python
  - python3
  skip_if_env:
    MLC_CONDA_ENV:
    - 'yes'
  tags: get,python3
- env:
    MLC_GIT_CHECKOUT_PATH_ENV_NAME: MLC_MMCV_SRC_REPO_PATH
  extra_cache_tags: mmdetection,src,mmcv-src-repo
  names:
  - mmcv-src-repo
  tags: get,git,repo
  update_tags_from_env_with_prefix:
    _branch.:
    - MLC_GIT_CHECKOUT
    _repo.:
    - MLC_GIT_URL
    _sha.:
    - MLC_GIT_CHECKOUT_SHA
    _tag.:
    - MLC_GIT_CHECKOUT_TAG
- names:
  - python-pip
  - pip
  tags: get,generic-python-lib,_pip
- tags: get,generic-python-lib,_setuptools
env:
  MLC_GIT_URL: https://github.com/open-mmlab/mmcv.git
name: Build mmcv from sources
new_env_keys:
- MLC_mmcv_*
prehook_deps: []
sort: 1000
tags:
- install-mmcv-from-src
uid: 797dfce5d9cf49aa
variations:
  branch.#:
    env:
      MLC_GIT_CHECKOUT: '#'
  pr-to-apply.#:
    env: {}
  repo.#:
    env:
      MLC_GIT_URL: '#'
    group: repo
  sha.#:
    env:
      MLC_GIT_CHECKOUT_SHA: '#'
  tag.#:
    env:
      MLC_GIT_CHECKOUT_TAG: '#'
  uniad-automotive:
    default: true
    env:
      FORCE_CUDA: "1"
      MLC_GIT_CHECKOUT_TAG: v1.5.0
      MLC_MMDET_TASK: automotive
      MMCV_WITH_OPS: 1
    group: task
versions: {}
