alias: tar-my-folder
automation_alias: script
automation_uid: 5b4e0237da074764
cache: false
category: DevOps automation
clean_files: []
deps: []
input_mapping:
  input_dir: MLC_TAR_INPUT_DIR
  outfile: MLC_TAR_OUTFILE
  output_dir: MLC_TAR_OUTPUT_DIR
new_env_keys:
  - MLC_TAR_OUTFILE
tags:
- run
- tar
uid: 3784212e986c456b
