alias: install-pip-package-for-mlc-python
uid: b16ed087abab459c
automation_alias: script
automation_uid: 5b4e0237da074764

# Metadata
tags:
- install
- pip
- package
- pip-package
- for-mlc-python
- for.mlc-python

# Cache
cache: true

# Variations
variations:
  package.#:
    env:
      MLC_PIP_PACKAGE_NAME: '#'
