alias: install-pip-package-for-mlc-python
automation_alias: script
automation_uid: 5b4e0237da074764
cache: true
tags:
- install
- pip
- package
- pip-package
- for-mlc-python
- for.mlc-python
uid: b16ed087abab459c

variations:
  package.#:
    env:
      MLC_PIP_PACKAGE_NAME: "#"
