alias: get-qaic-software-kit
uid: 3344655922694bbb
automation_alias: script
automation_uid: 5b4e0237da074764

# Metadata
category: AI/ML frameworks
tags:
- get
- qaic
- software
- kit
- qaic-software-kit

# Cache
cache: true

# Environment
new_env_keys:
- +PATH
- MLC_QAIC_SOFTWARE_KIT_PATH
- MLC_QAIC_RUNNER_PATH
new_state_keys: []

# Input mapping
input_mapping: {}
input_description: {}

# Dependencies
deps:
- extra_cache_tags: qaic-software-git-repo,qaic-software,qaic,software,kit
  names:
  - qaic-software-git-repo
  tags: get,git,repo
  update_tags_from_env_with_prefix:
    _branch.:
    - MLC_GIT_CHECKOUT
    _repo.:
    - MLC_GIT_URL
- tags: get,generic,sys-util,_libudev-dev
- tags: get,generic,sys-util,_libpci-dev
- tags: get,google,test
- names:
  - cmake
  tags: get,cmake
  version_min: 3.24.0
- names:
  - compiler
  tags: get,compiler
prehook_deps: []
posthook_deps: []
post_deps: []

# Variations
variations:
  repo.#:
    env:
      MLC_GIT_URL: '#'
    group: repo-source
  repo.quic:
    default: true
    env:
      MLC_GIT_URL: https://github.com/quic/software-kit-for-qualcomm-cloud-ai-100
    group: repo-source
  branch.#:
    env:
      MLC_GIT_CHECKOUT: '#'

# Versions
versions: {}
