alias: download-file
uid: 9cdc8dc41aae437e
automation_alias: script
automation_uid: 5b4e0237da074764

# Metadata
category: DevOps automation
tags:
- download
- file
- download-file
tags_help: download file

# Cache
cache: false
can_force_cache: true

# Environment
default_env:
  MLC_RCLONE_COPY_USING: sync
  MLC_EXTRACT_REMOVE_EXTRACTED: false
  MLC_DOWNLOAD_RETRY_COUNT: 2
new_env_keys:
- MLC_DOWNLOAD_DOWNLOADED_PATH
- <<<MLC_DOWNLOAD_FINAL_ENV_NAME>>>
- MLC_GET_DEPENDENT_CACHED_PATH
new_state_keys: []

# Input mapping
input_mapping:
  download_path: MLC_DOWNLOAD_PATH
  from: MLC_DOWNLOAD_LOCAL_FILE_PATH
  local_path: MLC_DOWNLOAD_LOCAL_FILE_PATH
  md5sum: MLC_DOWNLOAD_CHECKSUM
  output_file: MLC_DOWNLOAD_FILENAME
  store: MLC_DOWNLOAD_PATH
  url: MLC_DOWNLOAD_URL
input_description: {}

# Dependencies
deps:
- tags: detect,os
- enable_if_env:
    MLC_DOWNLOAD_CHECKSUM:
    - 'on'
    MLC_HOST_OS_FLAVOR:
    - macos
  tags: get,generic-sys-util,_md5sha1sum
prehook_deps: []
post_deps: []

# Variations
variations:
  curl:
    default_env:
      MLC_DOWNLOAD_CURL_EMULATE_BROWSER: 'no'
    env:
      MLC_DOWNLOAD_TOOL: curl
    group: download-tool
  gdown:
    deps:
    - tags: get,generic-python-lib,_package.gdown
    env:
      MLC_DOWNLOAD_TOOL: gdown
    group: download-tool
  mlcutil:
    default: true
    env:
      MLC_DOWNLOAD_TOOL: mlcutil
    group: download-tool
  r2-downloader:
    env:
      MLC_DOWNLOAD_TOOL: r2-downloader
    group: download-tool
  rclone:
    deps:
    - tags: get,rclone
    - enable_if_env:
        MLC_RCLONE_CONFIG_NAME:
        - 'on'
      tags: get,rclone-config
      update_tags_from_env_with_prefix:
        _:
        - MLC_RCLONE_CONFIG_NAME
    env:
      MLC_DOWNLOAD_TOOL: rclone
    group: download-tool
  wget:
    env:
      MLC_DOWNLOAD_TOOL: wget
    group: download-tool
  cmutil:
    alias: mlcutil
  url.#:
    env:
      MLC_DOWNLOAD_URL: '#'

# Versions
versions: {}

# Tests
tests:
  run_inputs:
  - variations_list:
    - url.https://raw.githubusercontent.com/octocat/Hello-World/refs/heads/master/README
    env:
      MLC_DOWNLOAD_FILENAME: test-readme.md
  - variations_list:
    - wget,url.https://raw.githubusercontent.com/octocat/Hello-World/refs/heads/master/README
    env:
      MLC_DOWNLOAD_FILENAME: test-readme-wget.md
  - variations_list:
    - curl,url.https://raw.githubusercontent.com/octocat/Hello-World/refs/heads/master/README
    env:
      MLC_DOWNLOAD_FILENAME: test-readme-curl.md
