# Written by Grigori Fursin

alias: get-dataset-cognata-mlcommons
uid: 464ce21f2dce464e

automation_alias: script
automation_uid: 5b4e0237da074764

developers: "Grigori Fursin, Radoyeh Shojaei"

tags:
- get
- raw
- dataset
- cognata
- mlcommons-cognata
- ml-task--object-detection
- ml-task--image-segmentation

min_mlc_version: '2.2.0'

private: true

cache: false

category: AI/ML datasets
category_sort: 8500


input_mapping:
  update: MLC_DATASET_MLCOMMONS_COGNATA_UPDATE
  import: MLC_DATASET_MLCOMMONS_COGNATA_IMPORT_PATH
  private_url: MLC_DATASET_MLCOMMONS_COGNATA_PRIVATE_URL
  serial_numbers: MLC_DATASET_MLCOMMONS_COGNATA_SERIAL_NUMBERS
  group_names: MLC_DATASET_MLCOMMONS_COGNATA_GROUP_NAMES
  file_names: MLC_DATASET_MLCOMMONS_COGNATA_FILE_NAMES

env:
  MLC_DATASET: MLCOMMONS_COGNATA
  MLC_DATASET_MLCOMMONS_COGNATA_KEY1: "Dataset 1.0"




deps:
# Prepare dummy MLC cache entry to manage dataset
- names:
  - custom-cache-entry-mlcommons-cognata-dataset
  tags: create,custom,cache,entry
  extra_cache_tags: dataset,cognata,mlcommons-cognata
  skip_if_any_env:
    MLC_DATASET_MLCOMMONS_COGNATA_FILE_NAMES:
    - 'off'
    MLC_DOWNLOAD_SRC: 
    - mlcommons
  env_key: DATASET_MLCOMMONS_COGNATA
  # this script will prepare env MLC_CUSTOM_CACHE_ENTRY_{env_key}_PATH


prehook_deps:
- names:
  - gdrive-downloader-cognata
  skip_if_any_env:
    MLC_DATASET_MLCOMMONS_COGNATA_FILE_NAMES:
    - 'on'
    MLC_DOWNLOAD_SRC: 
    - mlcommons
  enable_if_env:
    MLC_DATASET_MLCOMMONS_COGNATA_IMPORTED:
    - 'no'
    MLC_DATASET_MLCOMMONS_COGNATA_DOWNLOAD_TOOL:
    - gdrive
  tags: download,file,_gdown,_url.https://drive.google.com/drive/folders/1FS-qLbzB5htgMnfry6z4gx8J_ZH_7MsJ?usp=drive_link
  env:
    MLC_DOWNLOAD_EXTRA_OPTIONS: " --folder"
    MLC_DOWNLOAD_FILENAME: 10002_Urban_Clear_Morning
    MLC_DOWNLOAD_FINAL_ENV_NAME: MLC_CUSTOM_CACHE_ENTRY_DATASET_MLCOMMONS_COGNATA_PATH
  force_cache: true
  extra_cache_tags: abtf,cognata,poc,dataset

- names:
  - rclone-downloader-cognata
  skip_if_any_env:
    MLC_DATASET_MLCOMMONS_COGNATA_FILE_NAMES:
    - 'on'
    MLC_DOWNLOAD_SRC: 
    - mlcommons
  enable_if_env:
    MLC_DATASET_MLCOMMONS_COGNATA_IMPORTED:
    - 'no'
    MLC_DATASET_MLCOMMONS_COGNATA_DOWNLOAD_TOOL:
    - rclone
  tags: download-and-extract,file,_extract,_rclone,_url.https://automotive.mlcommons-storage.org/Cognata_Dataset_PoC_Demo%2F10002_Urban_Clear_Morning.zip
  env:
    MLC_RCLONE_COPY_USING: copyurl
    MLC_RCLONE_CONFIG_CMD: ''
    MLC_DOWNLOAD_CHECKSUM: '76389b05b0ee1e08d354d3c1b696b8c0'
    MLC_EXTRACT_EXTRACTED_CHECKSUM_FILE: "<<<MLC_DATASET_COGNATA_POC_TEXT_MD5_FILE_PATH>>>"
    MLC_DOWNLOAD_PATH: <<<MLC_ABTF_SCRATCH_PATH_DATASET_COGNATA_TMP>>>
    MLC_EXTRACT_PATH: <<<MLC_ABTF_SCRATCH_PATH_DATASET_COGNATA>>>
    MLC_EXTRACT_EXTRACTED_FILENAME: 10002_Urban_Clear_Morning
    MLC_DAE_FINAL_ENV_NAME: MLC_CUSTOM_CACHE_ENTRY_DATASET_MLCOMMONS_COGNATA_PATH
  force_cache: true
  extra_cache_tags: abtf,cognata,poc,dataset

- names:
  - python
  - python3
  tags: get,python3
  skip_if_any_env:
    MLC_DATASET_MLCOMMONS_COGNATA_IMPORTED:
    - 'yes'
    MLC_DOWNLOAD_SRC: 
    - mlcommons
  enable_if_env:
    MLC_DATASET_MLCOMMONS_COGNATA_FILE_NAMES:
      - 'on'

# Python package to read/write Excel files
- tags: get,generic-python-lib,_package.openpyxl
  skip_if_any_env:
    MLC_DATASET_MLCOMMONS_COGNATA_IMPORTED:
    - 'yes'
    MLC_DOWNLOAD_SRC: 
    - mlcommons
  enable_if_env:
    MLC_DATASET_MLCOMMONS_COGNATA_FILE_NAMES:
      - 'on'

# Tool to download large files
- tags: get,aria2
  skip_if_any_env:
    MLC_DATASET_MLCOMMONS_COGNATA_IMPORTED:
    - 'yes'
    MLC_DOWNLOAD_SRC: 
    - mlcommons
  enable_if_env:
    MLC_DATASET_MLCOMMONS_COGNATA_FILE_NAMES:
    - 'on'


variations:
  abtf-demo:
    group: dataset-type
    env:
      MLC_DATASET_MLCOMMONS_COGNATA_SERIAL_NUMBERS: "10002_Urban_Clear_Morning"
      MLC_DATASET_MLCOMMONS_COGNATA_GROUP_NAMES: "Cognata_Camera_01_8M"
      MLC_DATASET_MLCOMMONS_COGNATA_FILE_NAMES: "Cognata_Camera_01_8M_ann.zip;Cognata_Camera_01_8M_ann_laneline.zip;Cognata_Camera_01_8M.zip"

  abtf-poc:
    group: dataset-type
    default: true
    env:
      MLC_DATASET_MLCOMMONS_COGNATA_SERIAL_NUMBERS: "10002_Urban_Clear_Morning"
      MLC_DATASET_MLCOMMONS_COGNATA_GROUP_NAMES: "Cognata_Camera_01_8M"
      MLC_DATASET_MLCOMMONS_COGNATA_FILE_NAMES: ""

  release:
    group: dataset-type
    env:
      MLC_COGNATA_DATASET_TYPE: "release"

  rclone:
    group: download-tool
    default: true
    env:
      MLC_DATASET_MLCOMMONS_COGNATA_DOWNLOAD_TOOL: rclone

  gdrive:
    group: download-tool
    env:
      MLC_DATASET_MLCOMMONS_COGNATA_DOWNLOAD_TOOL: gdrive
  
  mlc:
    group: download-src
    prehook_deps:
      - tags: get,rclone
        enable_if_env:
          MLC_TMP_REQUIRE_DOWNLOAD:
          - yes
      - tags: get,rclone-config,_config-name.cognata
        force_cache: true
        enable_if_env:
          MLC_TMP_REQUIRE_DOWNLOAD:
          - yes
        env:
          MLC_RCLONE_DRIVE_FOLDER_ID: 1u5FDoeXHVtDrd4zClE47Gmyr7iLFidz1
      - enable_if_env:
          MLC_TMP_REQUIRE_DOWNLOAD:
          - 'yes'
        env:
          MLC_DOWNLOAD_FINAL_ENV_NAME: MLC_DATASET_MLCOMMONS_COGNATA_PATH
          MLC_EXTRACT_FINAL_ENV_NAME: MLC_DATASET_MLCOMMONS_COGNATA_PATH
          MLC_DOWNLOAD_URL: 'mlc-cognata:mlc_cognata_dataset/unprocessed'
        extra_cache_tags: dataset,cognata,release
        force_cache: true
        names:
          - dae
        tags: download-and-extract
        force_env_keys:
          - MLC_OUTDIRNAME  
        update_tags_from_env_with_prefix:
          _url.:
            - MLC_DOWNLOAD_URL
    env:
      MLC_DOWNLOAD_SRC: mlcommons
  
  rclone,mlc:
    add_deps_recursive:
      dae:
        tags: _rclone
    env:
      MLC_RCLONE_COPY_USING: sync

  dry-run:
    group: run-mode
    env:
      MLC_DOWNLOAD_MODE: dry

  dry-run,rclone:
    env:
      MLC_DOWNLOAD_EXTRA_OPTIONS: --dry-run
  

new_env_keys:
- MLC_DATASET_MLCOMMONS_COGNATA*

print_env_at_the_end:
  MLC_DATASET_MLCOMMONS_COGNATA_PATH: Path to Cognata dataset
