alias: app-mlperf-inference-ctuning-cpp-tflite
automation_alias: script
automation_uid: 5b4e0237da074764
category: Modular MLPerf inference benchmark pipeline
default_env:
  MLC_DATASET_COMPRESSED: 'off'
  MLC_DATASET_INPUT_SQUARE_SIDE: '224'
  MLC_FAST_COMPILATION: 'yes'
  MLC_LOADGEN_BUFFER_SIZE: '1024'
  MLC_MLPERF_LOADGEN_MODE: accuracy
  MLC_MLPERF_LOADGEN_SCENARIO: SingleStream
  MLC_MLPERF_LOADGEN_TRIGGER_COLD_RUN: '0'
  MLC_MLPERF_OUTPUT_DIR: .
  MLC_MLPERF_SUT_NAME_IMPLEMENTATION_PREFIX: tflite_cpp
  MLC_MLPERF_TFLITE_USE_NEON: '0'
  MLC_MLPERF_TFLITE_USE_OPENCL: '0'
  MLC_ML_MODEL_GIVEN_CHANNEL_MEANS: 123.68 116.78 103.94
  MLC_ML_MODEL_NORMALIZE_DATA: '0'
  MLC_ML_MODEL_SUBTRACT_MEANS: '1'
  MLC_VERBOSE: '0'
deps:
- tags: detect,os
- tags: detect,cpu
- tags: get,sys-utils-mlc
- enable_if_env:
    MLC_MLPERF_DEVICE:
    - gpu
  tags: get,cuda
- names:
  - loadgen
  tags: get,loadgen,_wg-inference
- names:
  - inference-src
  tags: get,mlcommons,inference,src
- enable_if_env:
    MLC_MLPERF_BACKEND:
    - tflite
    - armnn_tflite
    MLC_MODEL:
    - mobilenet
  names:
  - ml-model
  - tflite-model
  - mobilenet-model
  tags: get,ml-model,mobilenet,raw,_tflite
- enable_if_env:
    MLC_MLPERF_BACKEND:
    - tflite
    - armnn_tflite
    MLC_MODEL:
    - resnet50
  names:
  - ml-model
  - tflite-model
  - resnet50-model
  tags: get,ml-model,resnet50,raw,_tflite,_no-argmax
- enable_if_env:
    MLC_MLPERF_BACKEND:
    - tf
    MLC_MODEL:
    - resnet50
  names:
  - ml-model
  - tflite-model
  - resnet50-model
  tags: get,ml-model,resnet50,raw,_tf
- enable_if_env:
    MLC_MLPERF_BACKEND:
    - tflite
    - armnn_tflite
    MLC_MODEL:
    - efficientnet
  names:
  - ml-model
  - tflite-model
  - efficientnet-model
  tags: get,ml-model,efficientnet,raw,_tflite
- names:
  - tensorflow
  - tflite
  tags: get,tensorflow,lib,_tflite
- enable_if_env:
    MLC_MLPERF_TFLITE_USE_ARMNN:
    - 'yes'
  names:
  - armnn
  - lib-armnn
  tags: get,lib,armnn
input_mapping:
  compressed_dataset: MLC_DATASET_COMPRESSED
  count: MLC_MLPERF_LOADGEN_QUERY_COUNT
  mlperf_conf: MLC_MLPERF_CONF
  mode: MLC_MLPERF_LOADGEN_MODE
  output_dir: MLC_MLPERF_OUTPUT_DIR
  performance_sample_count: MLC_MLPERF_LOADGEN_PERFORMANCE_SAMPLE_COUNT
  scenario: MLC_MLPERF_LOADGEN_SCENARIO
  user_conf: MLC_MLPERF_USER_CONF
  verbose: MLC_VERBOSE
new_env_keys:
- MLC_MLPERF_*
- MLC_ML_MODEL_*
- MLC_HW_NAME
new_state_keys:
- MLC_SUT_*
post_deps:
- names:
  - compiler-program
  skip_if_env:
    MLC_MLPERF_SKIP_RUN:
    - 'yes'
  tags: compile,program
- names:
  - mlperf-runner
  skip_if_env:
    MLC_MLPERF_SKIP_RUN:
    - 'yes'
  tags: benchmark-mlperf
- names:
  - save-mlperf-inference-state
  tags: save,mlperf,inference,state
prehook_deps:
- names:
  - user-conf-generator
  tags: generate,user-conf,mlperf,inference,_wg-inference
- enable_if_env:
    MLC_MLPERF_SKIP_RUN:
    - 'no'
    MLC_MODEL:
    - resnet50
  names:
  - imagenet-preprocessed
  - preprocessed-dataset
  skip_if_env:
    MLC_DATASET_COMPRESSED:
    - 'on'
  tags: get,dataset,preprocessed,imagenet,_for.resnet50,_rgb32,_NHWC
  update_tags_from_env:
  - MLC_DATASET_PREPROCESSED_IMAGENET_DEP_TAGS
- enable_if_env:
    MLC_MLPERF_SKIP_RUN:
    - 'no'
    MLC_MODEL:
    - mobilenet
    - efficientnet
  names:
  - imagenet-preprocessed
  - preprocessed-dataset
  skip_if_env:
    MLC_DATASET_COMPRESSED:
    - 'on'
  tags: get,dataset,preprocessed,imagenet,_for.mobilenet,_rgb32,_NHWC
  update_tags_from_env:
  - MLC_DATASET_PREPROCESSED_IMAGENET_DEP_TAGS
- enable_if_env:
    MLC_DATASET_COMPRESSED:
    - 'on'
    MLC_MLPERF_SKIP_RUN:
    - 'no'
    MLC_MODEL:
    - mobilenet
    - efficientnet
  names:
  - imagenet-preprocessed
  - preprocessed-dataset
  tags: get,dataset,preprocessed,imagenet,_for.mobilenet,_rgb8,_NHWC
  update_tags_from_env:
  - MLC_DATASET_PREPROCESSED_IMAGENET_DEP_TAGS
- enable_if_env:
    MLC_DATASET_COMPRESSED:
    - 'on'
    MLC_MLPERF_SKIP_RUN:
    - 'no'
    MLC_MODEL:
    - resnet50
  names:
  - imagenet-preprocessed
  - preprocessed-dataset
  tags: get,dataset,preprocessed,imagenet,_for.resnet50,_rgb8,_NHWC
  update_tags_from_env:
  - MLC_DATASET_PREPROCESSED_IMAGENET_DEP_TAGS
tags:
- app
- mlcommons
- mlperf
- inference
- tflite-cpp
tags_help: app mlperf inference tflite-cpp
uid: 415904407cca404a
variations:
  armnn:
    default_variations:
      optimization-target: use-neon
    env:
      MLC_MLPERF_TFLITE_USE_ARMNN: 'yes'
      MLC_TMP_LINK_LIBS: tensorflowlite,armnn
  armnn,tflite:
    env:
      MLC_MLPERF_BACKEND: armnn_tflite
      MLC_MLPERF_BACKEND_VERSION: <<<MLC_LIB_ARMNN_VERSION>>>
      MLC_MLPERF_SUT_NAME_IMPLEMENTATION_PREFIX: tflite_armnn_cpp
      MLC_TMP_LINK_LIBS: tensorflowlite,armnn,armnnTfLiteParser
      MLC_TMP_SRC_FOLDER: armnn
  cpu:
    default: true
    env:
      MLC_MLPERF_DEVICE: cpu
    group: device
  efficientnet:
    env:
      MLC_MODEL: efficientnet
    group: model
  fp32:
    adr:
      ml-model:
        tags: _fp32
      preprocessed-dataset:
        tags: _float32
    default: true
    env:
      MLC_MLPERF_MODEL_PRECISION: float32
    group: precision
  gpu:
    env:
      MLC_MLPERF_DEVICE: gpu
      MLC_MLPERF_DEVICE_LIB_NAMESPEC: cudart
    group: device
  int8:
    adr:
      ml-model:
        tags: _int8
      preprocessed-dataset:
        tags: _int8
    env:
      MLC_DATASET_COMPRESSED: 'on'
      MLC_MLPERF_MODEL_PRECISION: int8
    group: precision
  mobilenet:
    env:
      MLC_MODEL: mobilenet
    group: model
  resnet50:
    default: true
    env:
      MLC_MODEL: resnet50
    group: model
  singlestream:
    default: true
    env:
      MLC_MLPERF_LOADGEN_SCENARIO: SingleStream
    group: loadgen-scenario
  tf:
    env:
      MLC_MLPERF_BACKEND: tf
    group: backend
  tflite:
    default: true
    env:
      MLC_MLPERF_BACKEND: tflite
      MLC_MLPERF_BACKEND_VERSION: master
      MLC_TMP_LINK_LIBS: tensorflowlite
      MLC_TMP_SRC_FOLDER: src
    group: backend
  uint8:
    adr:
      ml-model:
        tags: _uint8
      preprocessed-dataset:
        tags: _int8
    env:
      MLC_DATASET_COMPRESSED: 'on'
      MLC_MLPERF_MODEL_PRECISION: uint8
    group: precision
  use-neon:
    env:
      MLC_MLPERF_SUT_NAME_RUN_CONFIG_SUFFIX1: using_neon
      MLC_MLPERF_TFLITE_USE_NEON: '1'
    group: optimization-target
  use-opencl:
    env:
      MLC_MLPERF_SUT_NAME_RUN_CONFIG_SUFFIX1: using_opencl
      MLC_MLPERF_TFLITE_USE_OPENCL: '1'
    group: optimization-target
