alias: truncate-mlperf-inference-accuracy-log
automation_alias: script
automation_uid: 5b4e0237da074764
cache: false
category: MLPerf benchmark support
clean_files: []
deps:
- names:
  - python
  - python3
  tags: get,python3
- names:
  - get-mlperf-submission-dir
  skip_if_env:
    MLC_MLPERF_INFERENCE_SUBMISSION_DIR:
    - 'on'
  tags: get,mlperf,submission,dir
variations:
  wg-inference:
    group: benchmark_wg
    default: true
    deps:
      - names:
        - inference-src
        tags: mlcommons,inference,src
  wg-automotive:
    group: benchmark_wg
    deps:
      - names:
        - automotive-src
        tags: mlcommons,automotive,src
input_mapping:
  input: MLC_MLPERF_INFERENCE_SUBMISSION_DIR
  submission_dir: MLC_MLPERF_INFERENCE_SUBMISSION_DIR
  submitter: MLC_MLPERF_SUBMITTER
tags:
- run
- mlc
- mlcommons
- mlperf
- inference
- mlperf-inference
- truncation
- truncator
- truncate
- accuracy
- accuracy-log
- accuracy-log-trancation
- accuracy-log-truncator
- mlc-accuracy-log-trancation
- mlc-accuracy-log-truncator
uid: 9d5ec20434084d14
