alias: get-dataset-whisper
automation_alias: script
automation_uid: 5b4e0237da074764
cache: true
new_env_keys:
- MLC_DATASET_WHISPER_PATH
tags:
- get-dataset-whisper
- get
- dataset
- whisper
uid: 2cc955c795d44978
tests:
  run_inputs:
  - variations_list:
    - rclone,preprocessed,mlc,dry-run
    - r2_downloader,preprocessed,mlc,dry-run
variations:
  preprocessed:
    group: dataset-type
    default: true
    env:
      MLC_TMP_DATASET_TYPE: preprocessed
  unprocessed:
    group: dataset-type
    deps:
    - tags: get,mlperf,inference,src
      names:
        - inference-src
    - tags: get,python
      names:
        - python
    - tags: get,generic-python-lib,_package.pandas
    - tags: get,generic-python-lib,_package.requests
    - tags: get,generic-python-lib,_package.tqdm
    - tags: get,generic-python-lib,_package.sox
    - tags: get,generic-python-lib,_package.librosa
    - tags: get,generic-sys-util,_sox
    env:
      MLC_TMP_DATASET_TYPE: unprocessed
  dry-run:
    env:
      MLC_DOWNLOAD_MODE: dry
    group: run-mode
  dry-run,rclone:
    env:
      MLC_DOWNLOAD_EXTRA_OPTIONS: --dry-run
  dry-run,r2_downloader:
    env:
      MLC_DOWNLOAD_EXTRA_OPTIONS: -x
  mlc:
    default: true
    env:
      MLC_DOWNLOAD_SRC: mlcommons
    group: download-src
  mlc,preprocessed:
    prehook_deps:
    - enable_if_env:
        MLC_TMP_REQUIRE_DOWNLOAD:
        - 'yes'
      env:
        MLC_DOWNLOAD_FINAL_ENV_NAME: MLC_DATASET_WHISPER_PATH
        MLC_EXTRACT_FINAL_ENV_NAME: MLC_DATASET_WHISPER_PATH
      extra_cache_tags: whisper,dataset
      force_cache: true
      force_env_keys:
      - MLC_OUTDIRNAME
      names:
      - dae
      tags: download-and-extract
      update_tags_from_env_with_prefix:
        _url.:
        - MLC_DOWNLOAD_URL
  rclone,preprocessed:
    env:
      MLC_DOWNLOAD_URL: mlc-inference:mlcommons-inference-wg-public/Whisper/dataset/
    prehook_deps:
    - enable_if_env:
        MLC_TMP_REQUIRE_DOWNLOAD:
        - true
      tags: get,rclone
    - enable_if_env:
        MLC_TMP_REQUIRE_DOWNLOAD:
        - true
      force_cache: true
      tags: get,rclone-config,_mlc-inference
  r2_downloader,preprocessed:
    env:
      MLC_DOWNLOAD_URL: https://inference.mlcommons-storage.org/metadata/whisper-dataset.uri
  rclone:
    add_deps_recursive:
      dae:
        tags: _rclone
    default: true
    group: download-tool
  r2_downloader:
    add_deps_recursive:
      dae:
        tags: _r2_downloader
    group: download-tool
