alias: get-lib-tcmalloc
automation_alias: script
automation_uid: 5b4e0237da074764
cache: true
category: Detection or installation of tools and artifacts
deps:
- env:
    MLC_GIT_CHECKOUT_PATH_ENV_NAME: MLC_TCMALLOC_SRC_PATH
    MLC_GIT_REPO_VERSION_ENV_NAME: MLC_TCMALLOC_VERSION
  extra_cache_tags: tcmalloc,repo,tcmalloc-repo
  force_env_keys:
  - MLC_GIT_*
  names:
  - mimalloc-repo
  tags: get,git,repo
  update_tags_from_env_with_prefix:
    _branch.:
    - MLC_GIT_CHECKOUT
    _repo.:
    - MLC_GIT_URL
    _sha.:
    - MLC_GIT_SHA
    _submodules.:
    - MLC_GIT_SUBMODULES
- tags: get,bazel
  version: 8.5.1
- env:
    MLC_GENERIC_SYS_UTIL_IGNORE_MISSING_PACKAGE: true
  tags: get,generic-sys-util,_build-essential
new_env_keys:
- MLC_TCMALLOC_PATH
- MLC_TCMALLOC_VERSION
- MLC_TCMALLOC_LIB_PATH
- +LD_LIBRARY_PATH
new_state_keys: []
post_deps: []
posthook_deps: []
prehook_deps: []
tags:
- tcmalloc
- get
- lib
tests:
  run_inputs:
  - variations_list:
    - branch.master
uid: bc454a366fed44f2
variations:
  static:
    env:
      MLC_TCMALLOC_BUILD_TYPE: static
  full:
    group: build-type
    env:
      MLC_TCMALLOC_BUILD_NAME: tcmalloc
  minimal:
    group: build-type
    default: true
    env:
      MLC_TCMALLOC_BUILD_NAME: tcmalloc_minimal

  branch.#:
    env:
      MLC_GIT_CHECKOUT: '#'
  config.#:
    env:
      MLC_TCMALLOC_CONFIG: '#'
  sha.#:
    env:
      MLC_GIT_SHA: '#'
  url.#:
    env:
      MLC_GIT_URL: '#'
    group: version
  url.official:
    default: true
    env:
      MLC_GIT_URL: https://github.com/google/tcmalloc.git
    group: version
  version.official:
    base:
    - url.official
