alias: build-docker-image
uid: 2c3c4ba2413442e7
automation_alias: script
automation_uid: 5b4e0237da074764

# Metadata
category: Docker automation
tags:
- build
- docker
- image
- docker-image
- dockerimage

# Cache
cache: false

# Environment
default_env:
  MLC_DOCKER_IMAGE_REPO: local
  MLC_DOCKER_IMAGE_TAG: latest
new_env_keys:
- MLC_DOCKER_*

# Input mapping
input_mapping:
  cache: MLC_DOCKER_CACHE
  docker_os: MLC_DOCKER_OS
  docker_os_version: MLC_DOCKER_OS_VERSION
  dockerfile: MLC_DOCKERFILE_WITH_PATH
  gh_token: MLC_GH_TOKEN
  image_name: MLC_DOCKER_IMAGE_NAME
  image_repo: MLC_DOCKER_IMAGE_REPO
  image_tag: MLC_DOCKER_IMAGE_TAG
  mlc_repo: MLC_MLOPS_REPO
  post_run_cmds: MLC_DOCKER_POST_RUN_COMMANDS
  pre_run_cmds: MLC_DOCKER_PRE_RUN_COMMANDS
  push_image: MLC_DOCKER_PUSH_IMAGE
  upload: MLC_DOCKER_PUSH_IMAGE
  real_run: MLC_REAL_RUN
  script_tags: MLC_DOCKER_RUN_SCRIPT_TAGS

# Dependencies
deps:
- tags: get,docker
prehook_deps:
- enable_if_env:
    MLC_BUILD_DOCKERFILE:
    - 'yes'
  tags: build,dockerfile

# Tests
tests:
  run_inputs:
  - env:
      MLC_DOCKER_PUSH_IMAGE: 'yes'
      MLC_REAL_RUN: 'no'
