alias: build-docker-image
uid: 2c3c4ba2413442e7

automation_alias: script
automation_uid: 5b4e0237da074764

cache: false

category: Docker automation

tags:
- build
- docker
- image
- docker-image
- dockerimage

default_env:
  MLC_DOCKER_IMAGE_REPO: local
  MLC_DOCKER_IMAGE_TAG: latest

input_mapping:
  cache: MLC_DOCKER_CACHE
  mlc_repo: MLC_MLOPS_REPO
  docker_os: MLC_DOCKER_OS
  docker_os_version: MLC_DOCKER_OS_VERSION
  dockerfile: MLC_DOCKERFILE_WITH_PATH
  gh_token: MLC_GH_TOKEN
  image_name: MLC_DOCKER_IMAGE_NAME
  image_repo: MLC_DOCKER_IMAGE_REPO
  image_tag: MLC_DOCKER_IMAGE_TAG
  post_run_cmds: MLC_DOCKER_POST_RUN_COMMANDS
  pre_run_cmds: MLC_DOCKER_PRE_RUN_COMMANDS
  real_run: MLC_REAL_RUN
  script_tags: MLC_DOCKER_RUN_SCRIPT_TAGS
  push_image: MLC_DOCKER_PUSH_IMAGE

new_env_keys:
- MLC_DOCKER_*

deps:
  - tags: get,docker

prehook_deps:
- enable_if_env:
    MLC_BUILD_DOCKERFILE:
    - 'yes'
  tags: build,dockerfile
