alias: gemini_call
automation_alias: script
automation_uid: 5b4e0237da074764
category: MLC Script Template
deps:
  - tags: get,python3
    names:
    - python
    - python3
new_env_keys: []
new_state_keys:
- MLC_GEMINI_RESPONSE
post_deps: []
posthook_deps: []
prehook_deps: []
tags:
- gemini-call
- query
input_mapping:
  api_key: MLC_GEMINI_API_KEY
  config_path: MLC_GEMINI_CONFIG_PATH
  system_prompt: MLC_GEMINI_SYSTEM_PROMPT
  user_prompt: MLC_GEMINI_USER_PROMPT
  model: MLC_GEMINI_MODEL
tests:
  run_inputs: []
uid: 1cfe3d0658364a2b
variations:
  gemini:
    group: api_provider
    default: true
    env:
      MLC_GEMINI_API_URL: 'https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key='



