alias: get-dataset-waymo-calibration
automation_alias: script
automation_uid: 5b4e0237da074764
cache: true
input_mapping:
  waymo_calibration_path: MLC_DATASET_WAYMO_CALIBRATION_PATH
new_env_keys:
- MLC_DATASET_WAYMO_CALIBRATION_PATH
tags:
- get
- waymo
- dataset
- calibration
uid: 59d3a8d48d5e4767
variations:
  kitti_format:
    default: true
    env:
      MLC_DATASET_WAYMO_FORMAT: kitti
    group: dataset-format
  mlc:
    default: true
    env:
      MLC_DOWNLOAD_SRC: mlcommons
    group: download-src
    prehook_deps:
    - enable_if_env:
        MLC_TMP_REQUIRE_DOWNLOAD:
        - true
      tags: get,rclone
    - enable_if_env:
        MLC_TMP_REQUIRE_DOWNLOAD:
        - true
      force_cache: true
      tags: get,rclone-config,_waymo
    - enable_if_env:
          MLC_TMP_REQUIRE_DOWNLOAD:
          - 'yes'
      env:
        MLC_DOWNLOAD_FINAL_ENV_NAME: MLC_DATASET_WAYMO_CALIBRATION_PATH
        MLC_EXTRACT_FINAL_ENV_NAME: MLC_DATASET_WAYMO_CALIBRATION_PATH
        MLC_DOWNLOAD_URL: mlc-waymo:waymo_preprocessed_dataset/kitti_format/testing
      extra_cache_tags: waymo,dataset
      force_cache: true
      names:
        - dae
      tags: download-and-extract
      force_env_keys:
        - MLC_OUTDIRNAME  
      update_tags_from_env_with_prefix:
        _url.:
          - MLC_DOWNLOAD_URL
  rclone:
    group: download-tool
    add_deps_recursive:
      dae:
        tags: _rclone
    default: true
  dry-run:
    group: run-mode
    env:
      MLC_DOWNLOAD_MODE: dry
  dry-run,rclone:
    env:
      MLC_DOWNLOAD_EXTRA_OPTIONS: --dry-run