alias: get-mlperf-automotive-utils
automation_alias: script
automation_uid: 5b4e0237da074764
cache: false
tags:
- get
- mlperf
- automotive
- util
- utils
- functions
uid: c20cfade1c184f83
deps:
  - tags: get,mlperf,automotive,src
    names:
      - automotive-src
new_env_keys:
  - '+PYTHONPATH'
  - MLC_MLPERF_INFERENCE_BEVFORMER_PATH
  - MLC_MLPERF_INFERENCE_SSD_RESNET50_PATH
  - MLC_MLPERF_INFERENCE_DEEPLABV3PLUS_PATH
  - MLC_MLPERF_LAST_RELEASE
  - MLC_MLPERF_INFERENCE_SOURCE
  - MLC_MLPERF_INFERENCE_VERSION
  - MLC_MLPERF_INFERENCE_SOURCE_VERSION