alias: get-dataset-coco2014
uid: 3f7ad9d42f4040f8

automation_alias: script
automation_uid: 5b4e0237da074764

cache: true

category: AI/ML datasets
category_sort: 8500

input_mapping:
  num_workers: MLC_DATASET_COCO2014_NUM_WORKERS

tags:
- get
- dataset
- coco2014
- object-detection
- original

default_env:
  MLC_DATASET_CALIBRATION: 'no'
  MLC_DATASET_COCO2014_NUM_WORKERS: 1
  
deps:

- names:
  - python
  - python3
  tags: get,python3

- tags: get,generic-python-lib,_package.tqdm
- tags: get,generic-python-lib,_package.pandas

- force_env_keys:
  - MLC_GIT_*
  names:
  - inference-src
  tags: mlperf,inference,source
  version: master

env:
  MLC_DATASET: COCO2014

new_env_keys:
- MLC_DATASET_PATH
- MLC_DATASET_PATH_ROOT
- MLC_DATASET_ANNOTATIONS_DIR_PATH
- MLC_DATASET_ANNOTATIONS_FILE_PATH
- MLC_CALIBRATION_DATASET_PATH
- MLC_COCO2014_SAMPLE_ID_PATH

posthook_deps:
- enable_if_env:
    MLC_DATASET_COCO2014_CUSTOM_ANNOTATIONS:
    - 'yes'
  tags: get,coco2014,annotations

variations:
  '50':
    default: true
    env:
      MLC_DATASET_SIZE: '50'
    group: size
  '500':
    env:
      MLC_DATASET_SIZE: '500'
    group: size
  calibration:
    env:
      MLC_DATASET_CALIBRATION: 'yes'
    group: dataset-type
  custom-annotations:
    env:
      MLC_DATASET_COCO2014_CUSTOM_ANNOTATIONS: 'yes'
    group: annotations
  default-annotations:
    default: true
    env:
      MLC_DATASET_COCO2014_CUSTOM_ANNOTATIONS: 'no'
    group: annotations
  full:
    env:
      MLC_DATASET_SIZE: ''
    group: size
  size.#:
    env:
      MLC_DATASET_SIZE: '#'
    group: size
  with-sample-ids:
    env:
      MLC_GENERATE_SAMPLE_ID: 'yes'
  validation:
    default: true
    env:
      MLC_DATASET_CALIBRATION: 'no'
    group: dataset-type
