alias: install-github-cli
uid: cd948ec309344bf8
automation_alias: script
automation_uid: 5b4e0237da074764

# Metadata
category: Detection or installation of tools and artifacts
tags:
- install
- gh
- github
- cli
- github-cli

# Cache
cache: true
clean_files: []

# Environment
default_env:
  MLC_SUDO: sudo

# Dependencies
deps:
- tags: detect,os

# Tests
tests:
  run_inputs:
  - env: {}
  - env:
      MLC_SUDO: 'no'
  - env:
      MLC_SUDO: 'no'
      MLC_GH_INSTALL_PATH: /tmp/gh-cli-test
