alias: get-huggingface-cli
uid: e9488a272f1d4160
automation_alias: script
automation_uid: 5b4e0237da074764

# Metadata
category: DevOps automation
tags:
- get
- huggingface
- hf-cli
- huggingface-cli
- cli

# Cache
cache: false
can_force_cache: true
clean_files: []

# Input mapping
input_mapping:
  token: MLC_HF_TOKEN

# Dependencies
deps:
- tags: get,generic-python-lib,_package.huggingface_hub[cli]

# Variations
variations:
  with-login:
    cache: true
    force_cache: true
    env:
      MLC_HF_DO_LOGIN: true
