alias: openai-call
uid: 8d341b0a14a64d94
automation_alias: script
automation_uid: 5b4e0237da074764

# Metadata
category: MLC Script Template
tags:
- query
- openai
- openai-call
- call

# Environment
new_env_keys: []
new_state_keys:
- MLC_OPENAI_RESPONSE

# Input mapping
input_mapping:
  api_key: MLC_OPENAI_API_KEY
  config_path: MLC_OPENAI_CONFIG_PATH
  model: MLC_OPENAI_MODEL
  system_prompt: MLC_OPENAI_SYSTEM_PROMPT
  user_prompt: MLC_OPENAI_USER_PROMPT

# Dependencies
deps:
- tags: get,python3
  names:
  - python
  - python3
prehook_deps: []
posthook_deps: []
post_deps: []

# Variations
variations:
  openai:
    group: api_provider
    default: true
    env:
      MLC_OPENAI_API_URL: https://api.openai.com/v1/chat/completions

# Tests
tests:
  run_inputs: []
