alias: install-cuda-prebuilt
automation_alias: script
automation_uid: 5b4e0237da074764
cache: true
category: CUDA automation
default_env:
  MLC_SUDO: sudo
default_version: 11.8.0
deps:
- tags: detect,os
- tags: detect,sudo
docker:
  run: true
input_mapping:
  install_prefix: MLC_CUDA_INSTALL_PREFIX
  local_run_file_path: CUDA_RUN_FILE_LOCAL_PATH
  override-driver-check: MLC_CUDA_DRIVER_INSTALL_OVERRIDE
  skip_sudo: CUDA_SKIP_SUDO
sudo_install: True
new_env_keys:
- MLC_CUDA_*
- MLC_NVCC_*
post_deps:
- skip_if_env:
    MLC_REQUIRE_INSTALL:
    - 'yes'
  tags: get,cuda
prehook_deps:
- env:
    MLC_DOWNLOAD_FINAL_ENV_NAME: MLC_CUDA_RUN_FILE_PATH
    MLC_DOWNLOAD_LOCAL_FILE_PATH: <<<CUDA_RUN_FILE_LOCAL_PATH>>>
  extra_cache_tags: cuda,run,file
  force_cache: true
  names:
  - download-script
  tags: download,file
  update_tags_from_env_with_prefix:
    _url.:
    - WGET_URL
tags:
- install
- prebuilt
- cuda
- prebuilt-cuda
- install-prebuilt-cuda
uid: 14eadcd42ba340c3
variations:
  driver:
    env:
      MLC_CUDA_INSTALL_DRIVER: 'yes'
    group: install-driver
  no-driver:
    default: true
    env:
      MLC_CUDA_INSTALL_DRIVER: 'no'
    group: install-driver
versions:
  11.7.0:
    env:
      MLC_CUDA_LINUX_FILENAME: cuda_11.7.0_515.43.04_linux.run
  11.8.0:
    env:
      MLC_CUDA_LINUX_FILENAME: cuda_11.8.0_520.61.05_linux.run
  12.0.0:
    env:
      MLC_CUDA_LINUX_FILENAME: cuda_12.0.0_525.60.13_linux.run
  12.1.1:
    env:
      MLC_CUDA_LINUX_FILENAME: cuda_12.1.1_530.30.02_linux.run
  12.2.0:
    env:
      MLC_CUDA_LINUX_FILENAME: cuda_12.2.0_535.54.03_linux.run
  12.3.2:
    env:
      MLC_CUDA_LINUX_FILENAME: cuda_12.3.2_545.23.08_linux.run
  12.4.0:
    env:
      MLC_CUDA_LINUX_FILENAME: cuda_12.4.0_550.54.14_linux.run
  12.4.1:
    env:
      MLC_CUDA_LINUX_FILENAME: cuda_12.4.1_550.54.15_linux.run
  12.5.0:
    env:
      MLC_CUDA_LINUX_FILENAME: cuda_12.5.0_555.42.02_linux.run
  12.5.1:
    env:
      MLC_CUDA_LINUX_FILENAME: cuda_12.5.1_555.42.06_linux.run
  12.6.0:
    env:
      MLC_CUDA_LINUX_FILENAME: cuda_12.6.0_560.28.03_linux.run
  12.6.1:
    env:
      MLC_CUDA_LINUX_FILENAME: cuda_12.6.1_560.35.03_linux.run
  12.8.1:
    env:
      MLC_CUDA_LINUX_FILENAME: cuda_12.8.1_570.124.06_linux.run
  12.9.1:
    env:
      MLC_CUDA_LINUX_FILENAME: cuda_12.9.1_575.57.08_linux.run
