alias: get-utils-aocl
uid: b70c25103ff341c0
automation_alias: script
automation_uid: 5b4e0237da074764
category: Detection or installation of tools and artifacts
tags:
- get
- utils
- utils-aocl
- aocl-utils
- aocl
cache: true
new_env_keys:
- MLC_AOCL_UTILS_SRC_PATH
- MLC_AOCL_UTILS_BUILD_PATH
- MLC_AOCL_UTILS_INSTALL_PATH
- MLC_AOCL_UTILS_LIB_PATH
- +LD_LIBRARY_PATH
- +LIBRARY_PATH
- +C_INCLUDE_PATH
- +CPLUS_INCLUDE_PATH
- MLC_AOCL_BINARY_INSTALL_PATH
- MLC_AOCL_UTILS_BINARY_PATH
new_state_keys: []
deps:
- tags: get,cmake
  skip_if_env:
    MLC_AOCL_BINARY_DOWNLOAD:
    - 'yes'
- tags: detect,cpu
- tags: get,git,repo
  names:
  - aocl-utils-repo
  extra_cache_tags: aocl-utils,repo,aocl-utils-repo
  env:
    MLC_GIT_CHECKOUT_PATH_ENV_NAME: MLC_AOCL_UTILS_SRC_PATH
  force_env_keys:
  - MLC_GIT_*
  update_tags_from_env_with_prefix:
    _branch.:
    - MLC_GIT_CHECKOUT
    _repo.:
    - MLC_GIT_REPO_URL
    _tag.:
    - MLC_GIT_CHECKOUT_TAG
  skip_if_env:
    MLC_AOCL_BINARY_DOWNLOAD:
    - 'yes'
variations:
  branch.#:
    env:
      MLC_GIT_CHECKOUT: '#'
  tag.#:
    env:
      MLC_GIT_CHECKOUT_TAG: '#'
    group: version
  repo.#:
    env:
      MLC_GIT_REPO_URL: '#'
    group: repo
  repo.amd:
    default: true
    env:
      MLC_GIT_REPO_URL: https://github.com/amd/aocl-utils.git
    group: repo
  binary:
    env:
      MLC_AOCL_BINARY_DOWNLOAD: 'yes'
      MLC_AOCL_BINARY_LIB_NAME: utils
      MLC_AOCL_BINARY_COMPILER: aocc
      MLC_AOCL_BINARY_VERSION: 5.2.0
      MLC_AOCL_BINARY_VERSION_PATH: 5-2
    prehook_deps:
    - tags: download-and-extract
      names:
      - aocl-utils-binary
      extra_cache_tags: aocl,utils,binary
      force_cache: true
      env:
        MLC_DAE_URL: https://download.amd.com/developer/eula/<<<MLC_AOCL_BINARY_LIB_NAME>>>/<<<MLC_AOCL_BINARY_LIB_NAME>>>-<<<MLC_AOCL_BINARY_VERSION_PATH>>>/aocl-<<<MLC_AOCL_BINARY_LIB_NAME>>>-linux-<<<MLC_AOCL_BINARY_COMPILER>>>-<<<MLC_AOCL_BINARY_VERSION>>>.tar.gz
        MLC_DOWNLOAD_FINAL_ENV_NAME: MLC_AOCL_UTILS_BINARY_PATH
        MLC_EXTRACT_FINAL_ENV_NAME: MLC_AOCL_UTILS_BINARY_PATH
        MLC_DAE_EXTRACT_DOWNLOADED: 'yes'
      update_tags_from_env_with_prefix:
        _url.:
        - MLC_DAE_URL
      force_env_keys:
      - MLC_OUTDIRNAME
  binary.aocc:
    env:
      MLC_AOCL_BINARY_COMPILER: aocc
    group: binary-compiler
    default: true
  binary.gcc:
    env:
      MLC_AOCL_BINARY_COMPILER: gcc
    group: binary-compiler
default_version: 5.2.2
versions:
  5.2.2:
    env:
      MLC_GIT_CHECKOUT: 5.2.2
  main:
    env:
      MLC_GIT_CHECKOUT: main
tests:
  run_inputs:
  - variations_list:
    - repo.amd
  - variations_list:
    - binary
    env:
      MLC_AOCL_ACCEPT_EULA: 'yes'
default_env:
  MLC_AOCL_ACCEPT_EULA: 'no'
input_mapping:
  accept_eula: MLC_AOCL_ACCEPT_EULA
input_description:
  accept_eula:
    desc: Accept the AMD EULA for binary downloads (yes/no)
