alias: get-mlperf-automotive-scratch-space
uid: c384b7604e5c47d5
automation_alias: script
automation_uid: 5b4e0237da074764

# Metadata
category: MLPerf Automotive
tags:
- get
- abtf
- inference
- scratch
- space

# Cache
cache: true

# Environment
new_env_keys:
- MLC_ABTF_SCRATCH_PATH
- MLC_ABTF_SCRATCH_PATH_MODELS
- MLC_ABTF_SCRATCH_PATH_DATASETS
- MLC_ABTF_SCRATCH_VERSION
new_state_keys: []

# Input mapping
input_mapping:
  scratch_path: MLC_ABTF_SCRATCH_PATH
input_description: {}

# Dependencies
deps: []
prehook_deps: []
posthook_deps: []
post_deps: []

# Variations
variations:
  version.#:
    env:
      MLC_ABTF_SCRATCH_VERSION: '#'
    group: version
  version.4_0:
    default: true
    env:
      MLC_ABTF_SCRATCH_VERSION: '4_0'
    group: version

# Versions
versions: {}

# Docker / container
docker:
  run: false
