alias: get-dataset-openorca
uid: 9252c4d90d5940b7
automation_alias: script
automation_uid: 5b4e0237da074764

# Metadata
category: AI/ML datasets
category_sort: 8500
tags:
- get
- dataset
- openorca
- language-processing
- original

# Cache
cache: true

# Environment
default_env:
  MLC_DATASET_CALIBRATION: 'no'
env:
  MLC_DATASET: OPENORCA
new_env_keys:
- MLC_DATASET_*

# Dependencies
deps:
- env:
    MLC_GIT_CHECKOUT_PATH_ENV_NAME: MLC_DATASET_OPENORCA_PATH
  extra_cache_tags: openorca,repo,src
  force_env_keys:
  - MLC_OUTDIRNAME
  names:
  - openorca-src
  tags: get,git,repo,_lfs,_repo.https://huggingface.co/datasets/Open-Orca/OpenOrca

# Variations
variations:
  calibration:
    env:
      MLC_DATASET_CALIBRATION: 'yes'
    group: dataset-type
  validation:
    default: true
    env:
      MLC_DATASET_CALIBRATION: 'no'
    group: dataset-type
  '500':
    env:
      MLC_DATASET_SIZE: '500'
    group: size
  '60':
    env:
      MLC_DATASET_SIZE: '60'
    group: size
  full:
    default: true
    env:
      MLC_DATASET_SIZE: '24576'
    group: size
  size.#:
    env:
      MLC_DATASET_SIZE: '#'
    group: size
