alias: get-dataset-waymo
automation_alias: script
automation_uid: 5b4e0237da074764
cache: true
tags:
- get
- dataset
- waymo
uid: 21b269c753b64437
new_env_keys:
  - MLC_DATASET_WAYMO_PATH
input_mapping:
  waymo_path: MLC_DATASET_WAYMO_PATH
variations:
  kitti_format:
    default: true
    group: dataset-format
    env:
      MLC_DATASET_WAYMO_FORMAT: kitti
  mlc:
    group: download-src
    default: true
    prehook_deps:
      - tags: get,rclone
        enable_if_env:
          MLC_TMP_REQUIRE_DOWNLOAD:
          - yes
      - tags: get,rclone-config,_waymo
        force_cache: true
        enable_if_env:
          MLC_TMP_REQUIRE_DOWNLOAD:
          - yes
      - enable_if_env:
          MLC_TMP_REQUIRE_DOWNLOAD:
          - 'yes'
        env:
          MLC_DOWNLOAD_FINAL_ENV_NAME: MLC_DATASET_WAYMO_PATH
          MLC_EXTRACT_FINAL_ENV_NAME: MLC_DATASET_WAYMO_PATH
          MLC_DOWNLOAD_URL: mlc_waymo:waymo_preprocessed_dataset/kitti_format
        extra_cache_tags: waymo,dataset
        force_cache: true
        names:
          - dae
        tags: download-and-extract
        force_env_keys:
          - MLC_OUTDIRNAME  
        update_tags_from_env_with_prefix:
          _url.:
            - MLC_DOWNLOAD_URL
    env:
      MLC_DOWNLOAD_SRC: mlcommons
  rclone:
    group: download-tool
    add_deps_recursive:
      dae:
        tags: _rclone
    default: true
  dry-run:
    group: run-mode
    env:
      MLC_DOWNLOAD_MODE: dry
  dry-run,rclone:
    env:
      MLC_DOWNLOAD_EXTRA_OPTIONS: --dry-run
