alias: get-dataset-waymo
automation_alias: script
automation_uid: 5b4e0237da074764
cache: true
tags:
- get
- dataset
- waymo
uid: 21b269c753b64437
new_env_keys:
  - MLC_DATASET_WAYMO_PATH
input_mapping:
  waymo_path: MLC_DATASET_WAYMO_PATH
variations:
  kitti_format:
    default: true
    group: dataset-format
    env:
      MLC_DATASET_WAYMO_FORMAT: kitti
