alias: get-mlperf-inference-submission-dir
uid: ddf36a41d6934a7e
automation_alias: script
automation_uid: 5b4e0237da074764

# Metadata
category: MLPerf Inference
tags:
- get
- mlperf
- inference
- submission
- local
- dir
- directory

# Cache
cache: true

# Environment
new_env_keys:
- MLC_MLPERF_INFERENCE_SUBMISSION_DIR
- MLC_MLPERF_INFERENCE_SUBMISSION_VERSION
new_state_keys: []

# Input mapping
input_mapping:
  submission_dir: MLC_MLPERF_INFERENCE_SUBMISSION_DIR
input_description: {}

# Dependencies
deps: []
prehook_deps: []
posthook_deps: []
post_deps: []

# Variations
variations:
  version.#:
    env:
      MLC_MLPERF_INFERENCE_SUBMISSION_VERSION: '#'
    group: version
  version.5_1-dev:
    default: true
    env:
      MLC_MLPERF_INFERENCE_SUBMISSION_VERSION: 5_1-dev
    group: version
  wg-automotive:
    group: working-group
    env:
      MLC_MLPERF_WORKING_GROUP: automotive
  wg-inference:
    group: working-group
    default: true
    env:
      MLC_MLPERF_WORKING_GROUP: inference

# Versions
versions: {}

# Docker / container
docker:
  run: false
