alias: get-mlperf-inference-submission-dir
automation_alias: script
automation_uid: 5b4e0237da074764
cache: true
category: MLPerf benchmark support
deps: []
docker:
  run: false
input_description: {}
input_mapping:
  submission_dir: MLC_MLPERF_INFERENCE_SUBMISSION_DIR
new_env_keys:
- MLC_MLPERF_INFERENCE_SUBMISSION_DIR
- MLC_MLPERF_INFERENCE_SUBMISSION_VERSION
new_state_keys: []
post_deps: []
posthook_deps: []
prehook_deps: []
tags:
- get
- mlperf
- inference
- submission
- local
- dir
- directory
uid: ddf36a41d6934a7e
variations:
  wg-inference:
    group: working-group
    default: true
    env:
      MLC_MLPERF_WORKING_GROUP: inference
  wg-automotive:
    group: working-group
    env:
      MLC_MLPERF_WORKING_GROUP: automotive

  version.#:
    env:
      MLC_MLPERF_INFERENCE_SUBMISSION_VERSION: '#'
    group: version
  version.5_1-dev:
    default: true
    env:
      MLC_MLPERF_INFERENCE_SUBMISSION_VERSION: 5_1-dev
    group: version
versions: {}
