alias: create-conda-env
uid: e39e0b04c86a40f2
automation_alias: script
automation_uid: 5b4e0237da074764

# Metadata
category: DevOps automation
tags:
- create
- get
- env
- conda-env
- conda-environment
- create-conda-environment

# Cache
cache: true
clean_files: []

# Environment
new_env_keys:
- +PATH
- +LD_LIBRARY_PATH
- MLC_CONDA_PREFIX
- CONDA_PREFIX
- MLC_CONDA_BIN_PATH
- MLC_CONDA_LIB_PATH

# Dependencies
deps:
- tags: detect,os
- names:
  - conda
  tags: get,conda

# Variations
variations:
  name.#:
    env:
      MLC_CONDA_ENV_NAME: '#'
