@echo off

IF NOT "%MLC_SYS_UTIL_VERSION_CMD_OVERRIDE%"=="" (
  %MLC_SYS_UTIL_VERSION_CMD_OVERRIDE%
  IF %ERRORLEVEL% NEQ 0 EXIT %ERRORLEVEL%
) ELSE (
  IF NOT "%MLC_SYS_UTIL_VERSION_CMD%"=="" (
    IF "%MLC_SYS_UTIL_VERSION_CMD_USE_ERROR_STREAM%"=="yes" (
      %MLC_SYS_UTIL_VERSION_CMD% > tmp-ver.out 2>&1
    ) ELSE (
      %MLC_SYS_UTIL_VERSION_CMD% > tmp-ver.out
    )
    IF %ERRORLEVEL% NEQ 0 EXIT %ERRORLEVEL%
  )
)
