alias: app-cp2k
automation_alias: script
automation_uid: 5b4e0237da074764
cache: true
category: HPC Application
deps:
- env:
    MLC_GIT_CHECKOUT_PATH_ENV_NAME: MLC_CP2K_SRC_PATH
    MLC_GIT_REPO_VERSION_ENV_NAME: MLC_CP2K_SRC_VERSION
  extra_cache_tags: cp2k,repo,cp2k-repo
  force_env_keys:
  - MLC_GIT_*
  names:
  - cp2k-repo
  tags: get,git,repo
  update_tags_from_env_with_prefix:
    _branch.:
    - MLC_GIT_CHECKOUT
    _repo.:
    - MLC_GIT_URL
    _sha.:
    - MLC_GIT_SHA
    _submodules.:
    - MLC_GIT_SUBMODULES
- tags: get,generic-sys-util,_autoconf
- env:
    MLC_GENERIC_SYS_UTIL_IGNORE_MISSING_PACKAGE: true
  tags: get,generic-sys-util,_build-essential
- tags: detect,cpu
- tags: get,blas
  names:
  - blas
new_env_keys:
- MLC_CP2K_SRC_PATH
- +LD_LIBRARY_PATH
new_state_keys: []
post_deps: []
posthook_deps: []
prehook_deps: []
tags:
- app
- cp2k
tests:
  run_inputs: []
uid: 06ee7deaf8fd4b9d
variations:
  with-amd:
    deps:
    - tags: get,aocc
      names:
      - aocc
  branch.#:
    env:
      MLC_GIT_CHECKOUT: '#'
  sha.#:
    env:
      MLC_GIT_SHA: '#'
  url.#:
    env:
      MLC_GIT_URL: '#'
    group: version
  url.official:
    default: true
    env:
      MLC_GIT_URL: https://github.com/cp2k/cp2k
    group: version
  version.official:
    base:
    - url.official
