alias: get-mlperf-multi-node-system-info
automation_alias: script
automation_uid: 5b4e0237da074764
cache: false
category: Platform information
deps:
- tags: detect,os
- tags: get,mlperf,single-node,system-info
  names:
  - mlperf-single-node-system-info
  skip_if_env:
    MLC_EXCLUDE_CURRENT_NODE:
    - 'True'
- names:
  - python
  - python3
  tags: get,python
input_mapping:
  submitter_org_name: MLC_MLPERF_SUBMITTER # eg;NVIDIA; Dell + Broadcom
  submitter_contact: MLC_MLPERF_SUBMITTER_CONTACT # eg; ARealPerson@mlcommons.org
  submission_id: MLC_MLPERF_SUBMISSION_ID # eg; # 42cf4c09-e67b-4546-88fe-2877add2b449
  submission_date: MLC_MLPERF_SUBMISSION_DATE # eg; ideally should be populated by the submission infrastructure
  publish_date: MLC_MLPERF_PUBLISH_DATE # eg; ideally should be populated by the submission infrastructure
  system_name: MLC_MLPERF_SYSTEM_NAME # eg; NVIDIA DGX A100
  category: MLC_MLPERF_SUBMISSION_SYSTEM_TYPE # eg; datacenter, edge, etc
  system_type_detail: MLC_MLPERF_SUBMISSION_SYSTEM_TYPE_DETAIL # eg; for datacenter: cloud, on-premises, etc and for edge: edge-server or edge-device
  status: MLC_MLPERF_SUBMISSION_SYSTEM_STATUS # eg; Available, Preview, Research_internal_development(RDI)
  system_size: MLC_MLPERF_SYSTEM_SIZE # eg; 8x GB300 + 12x GB300
  system_node_ensemble_count: MLC_MLPERF_SYSTEM_NODE_ENSEMBLE_COUNT # eg; 4
  system_node_ensemble_total: MLC_MLPERF_SYSTEM_NODE_ENSEMBLE_TOTAL # eg; 32
  other_hardware: MLC_MLPERF_OTHER_HARDWARE # Describes any other performance relevant hardware in the node, freeform field.
  cooling: MLC_MLPERF_COOLING # eg; air, liquid, etc
  hw_notes: MLC_MLPERF_HARDWARE_NOTES # Any other relevant notes about the hardware, freeform field
  ssh_ids: MLC_MULTINODE_SYSTEM_SSH_IDS 
  out_dir_path: MLC_MULTI_NODE_SYSTEM_INFO_DIR_PATH
  out_file_name: MLC_MULTI_NODE_SYSTEM_INFO_FILE_NAME
tags:
- get-mlperf-multi-node-system-info
uid: 1e4bc0644f554bc2
variations:
  cuda:
    adr:
      mlperf-single-node-system-info:
        tags: _cuda
    env:
  exclude_current_node:
    env:
      MLC_EXCLUDE_CURRENT_NODE: 'True'