alias: get-ml-model-pointpillars
automation_alias: script
automation_uid: 5b4e0237da074764
cache: true
tags:
- get
- ml-model
- ml
- model
- pointpainting
uid: 3562621a8994411d
new_env_keys:
  - MLC_ML_MODEL_POINT_PAINTING_PATH
  - MLC_ML_MODEL_DPLAB_RESNET50_PATH
input_mapping:
  pp_path: MLC_ML_MODEL_POINT_PAINTING_PATH  
  dp_resnet50_path: MLC_ML_MODEL_DPLAB_RESNET50_PATH
variations:
  gpu:
    default: true
    group: device
    env:
      MLC_ML_MODEL_PP_FORMAT: pth
      MLC_ML_MODEL_DPLAB_RESNET50_FORMAT: pth
  cpu:
    group: device
    env:
      MLC_ML_MODEL_PP_FORMAT: onnx
      MLC_ML_MODEL_DPLAB_RESNET50_FORMAT: onnx
  mlc:
    group: download-src
    default: true
    prehook_deps:
      - tags: get,rclone
        enable_if_env:
          MLC_TMP_REQUIRE_DOWNLOAD:
          - yes
      - tags: get,rclone-config,_waymo
        force_cache: true
        enable_if_env:
          MLC_TMP_REQUIRE_DOWNLOAD:
          - yes
    env:
      MLC_DOWNLOAD_SRC: mlcommons
  
