alias: get-blas
uid: 1a6e1cf75242456c
automation_alias: script
automation_uid: 5b4e0237da074764

# Metadata
category: Detection or installation of tools and artifacts
tags:
- get
- lib
- blas

# Cache
cache: true

# Environment
new_env_keys:
- MLC_BLAS_SRC_PATH
- +LD_LIBRARY_PATH
- MLC_BLAS_INSTALL_PATH
- MLC_BLAS_INC
- MLC_BLAS_LIB
new_state_keys: []

# Input mapping
input_mapping: {}
input_description: {}

# Dependencies
deps:
- force_env_keys:
  - MLC_GIT_CHECKOUT
  names:
  - blas-source-repo
  tags: get,git
- tags: detect,cpu
prehook_deps: []
posthook_deps: []
post_deps: []

# Variations
variations:
  openblas:
    add_deps_recursive:
      blas-source-repo:
        tags: _repo.https://github.com/xianyi/OpenBLAS.git
    default: true
    group: source

# Versions
default_version: master
versions:
  0.3.21:
    env:
      MLC_GIT_CHECKOUT: v0.3.21
  master:
    env:
      MLC_GIT_CHECKOUT: master
