name: MLPerf Inference TVM ResNet50

on:
  pull_request_target:
    branches: [ "main", "dev" ]
    paths:
      - '.github/workflows/test-mlperf-inference-tvm-resnet50.yml'
      - '**'
      - '!**.md'

jobs:
  tvm-run:
    name: TVM ResNet50
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9"]
        extra-options: [ "", " --adr.tvm.tags=_pip-install", " --adr.tvm.tags=_pip-install --adr.tvm-model.tags=_graph-executor"]

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install mlcflow
    - name: Pull MLOps repository
      run: |
        mlc pull repo ${{ github.event.pull_request.head.repo.html_url }} --branch=${{ github.event.pull_request.head.ref }}
        mlcr --quiet --tags=get,sys-utils-cm
    - name: Test MLC Tutorial TVM
      run: |
        mlcr --tags=run-mlperf,inference,_submission,_short --adr.python.name=mlperf --adr.python.version_min=3.8 --submitter=MLCommons --implementation=python --hw_name=gh_ubuntu-latest --model=resnet50 --backend=tvm-onnx --device=cpu --scenario=Offline --mode=accuracy --test_query_count=5 --clean --quiet ${{ matrix.extra-options }}
    - name: Randomly Execute Step
      id: random-check
      run: |
          RANDOM_NUMBER=$((RANDOM % 10))
          echo "Random number is $RANDOM_NUMBER"
          if [ "$RANDOM_NUMBER" -eq 0 ]; then
            echo "run_step=true" >> $GITHUB_ENV
          else
            echo "run_step=false" >> $GITHUB_ENV
          fi
    - name: Retrieve secrets from Keeper
      if: github.repository_owner == 'mlcommons' && env.run_step == 'true'
      id: ksecrets
      uses: Keeper-Security/ksm-action@master
      with:
        keeper-secret-config: ${{ secrets.KSM_CONFIG }}
        secrets: |-
          ubwkjh-Ii8UJDpG2EoU6GQ/field/Access Token > env:PAT
    - name: Push Results
      env:
        GITHUB_TOKEN: ${{ env.PAT }}
        USER: mlcommons-bot
        EMAIL: mlcommons-bot@users.noreply.github.com
      if: github.repository_owner == 'mlcommons' && env.run_step == 'true'
      run: |
        git config --global user.name "${{ env.USER }}"
        git config --global user.email "${{ env.EMAIL }}"
        git config --global credential.https://github.com.helper ""
        git config --global credential.https://github.com.helper "!gh auth git-credential"
        git config --global credential.https://gist.github.com.helper ""
        git config --global credential.https://gist.github.com.helper "!gh auth git-credential"
        mlcr --tags=push,github,mlperf,inference,submission --repo_url=https://github.com/mlcommons/mlperf_inference_test_submissions_v5.0 --repo_branch=auto-update --commit_message="Results from R50 GH action on ${{ matrix.os }}" --quiet
