name: MLPerf inference MLCommons C++ ResNet50

on:
  pull_request_target:
    branches: [ "main", "dev" ]
    paths:
      - '.github/workflows/test-mlperf-inference-mlcommons-cpp-resnet50.yml'
      - '**'
      - '!**.md'

jobs:     
  build:
    name: MLPerf inference MLCommons C++ ResNet50
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.12" ]
        compiler-string: [ "--adr.compiler.tags=gcc", "--adr.compiler.tags=aocc --env.MLC_AOCC_ACCEPT_EULA=yes", "--adr.compiler.tags=llvm --adr.compiler.version=17.0.6" ]
        os: [ubuntu-latest, windows-latest, macos-latest]
        exclude:
          - os: windows-latest
          - os: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install mlcflow
      run: |
        pip install mlcflow
    - name: Pull MLOps repository
      run: |
        mlc pull repo ${{ github.event.pull_request.head.repo.html_url }} --branch=${{ github.event.pull_request.head.ref }}
        mlcr --quiet --tags=get,sys-utils-mlc
    - name: Test MLPerf Inference MLCommons C++ ResNet50 on ${{ matrix.os }}
      if: matrix.os == 'windows-latest'
      run: |
        mlcr app,mlperf,inference,mlcommons,cpp --submitter="MLCommons" --hw_name=gh_${{ matrix.os }} --adr.loadgen.tags=_from-pip --pip_loadgen=yes -v --quiet
    - name: Test MLPerf Inference MLCommons C++ ResNet50 on ${{ matrix.os }}
      if: matrix.os != 'windows-latest'
      run: |
        mlcr app,mlperf,inference,mlcommons,cpp --submitter="MLCommons" --hw_name=gh_${{ matrix.os }} -v --quiet ${{ matrix.compiler-string }}
    - name: Randomly Execute Step
      id: random-check
      run: |
          RANDOM_NUMBER=$((RANDOM % 10))
          echo "Random number is $RANDOM_NUMBER"
          if [ "$RANDOM_NUMBER" -eq 0 ]; then
            echo "run_step=true" >> $GITHUB_ENV
          else
            echo "run_step=false" >> $GITHUB_ENV
          fi
    - name: Load secrets
      id: op-load-secrets
      uses: 1password/load-secrets-action@v3
      env:
        OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
        PAT: op://7basd2jirojjckncf6qnq3azai/bzbaco3uxoqs2rcyu42rvuccga/credential
    - name: Push Results
      env:
        GITHUB_TOKEN: ${{ steps.op-load-secrets.outputs.PAT }}
        USER: mlcommons-bot
        EMAIL: mlcommons-bot@users.noreply.github.com
      if: github.repository_owner == 'mlcommons' && env.run_step == 'true'
      run: |
        git config --global user.name "${{ env.USER }}"
        git config --global user.email "${{ env.EMAIL }}"
        git config --global credential.https://github.com.helper ""
        git config --global credential.https://github.com.helper "!gh auth git-credential"
        git config --global credential.https://gist.github.com.helper ""
        git config --global credential.https://gist.github.com.helper "!gh auth git-credential"
        mlcr push,github,mlperf,inference,submission --repo_url=https://github.com/mlcommons/mlperf_inference_test_submissions_v5.0 --repo_branch=dev --commit_message="Results from MLCommons C++ ResNet50 GH action on ${{ matrix.os }}" --quiet
