name: Test MLPerf automotive

on:
  pull_request_target:
    branches: [ "main", "dev" ]
    paths:
      - 'script/**meta.yaml'

jobs:
  fetch-secret:
    runs-on: ubuntu-latest
    outputs:
      gdrive_secret: ${{ steps.op-load-secret.outputs.GDRIVE_SERVICE_ACCOUNT_KEY }}
    steps:
      - name: Load secret from 1Password
        id: op-load-secret
        uses: 1password/load-secrets-action@v2
        with:
          export-env: false
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          GDRIVE_SERVICE_ACCOUNT_KEY: op://7basd2jirojjckncf6qnq3azai/bzbaco3uxoqs2rcyu42rvuccga/credential

  run-mlperf:
    runs-on: ubuntu-latest
    needs: 
      - fetch-secret
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Set RCLONE Service account env var from secret
        shell: bash
        run: |
          echo "::add-mask::${{ needs.fetch-secret.outputs.gdrive_secret }}"
          echo "RCLONE_CONFIG_MLC_COGNATA_SERVICE_ACCOUNT_CREDENTIALS=${{ needs.fetch-secret.outputs.gdrive_secret }}" >> $GITHUB_ENV
          echo "RCLONE_CONFIG_MLC_NUSCENES_SERVICE_ACCOUNT_CREDENTIALS=${{ needs.fetch-secret.outputs.gdrive_secret }}" >> $GITHUB_ENV
      - name: Run MLPerf
        run: |
          pip install mlcflow
          mlc pull repo ${{ github.event.pull_request.head.repo.html_url }} --branch=${{ github.event.pull_request.head.ref }}
          mlc test script app,mlperf,automotive
