name: MLPerf Inference Nvidia implementations

on:
  schedule:
    - cron: "35 01 * * *"

jobs:
  run_nvidia:
      if: github.repository_owner == 'gateoverflow'
      timeout-minutes: 1440
      runs-on:
       - self-hosted
       - linux
       - x64
       - cuda
       - ${{ matrix.system }}
      strategy:
        fail-fast: false
        matrix:
          system: [ "GO-spr", "phoenix", "GO-i9" ]
          # system: [ "mlc-server" ] 
          python-version: [ "3.12" ]
          model: [ "resnet50",  "retinanet",  "bert-99", "bert-99.9", "gptj-99.9", "3d-unet-99.9", "sdxl" ]
          exclude:
           - model: gptj-99.9
           - system: phoenix
           - system: GO-i9
          
      steps:
      - name: Test MLPerf Inference NVIDIA ${{ matrix.model }}
        env:
          gpu_name: rtx_4090
        run: |
          # Set hw_name based on matrix.system
          if [ "${{ matrix.system }}" = "GO-spr" ]; then
            hw_name="RTX4090x2"
            gpu_name=rtx_4090
            docker_string=" --docker --docker_recreate=yes"
          elif [ "${{ matrix.system }}" = "mlc-server" ]; then
            hw_name="H100x8"
            gpu_name=h100
            docker_string=" "
          else
            hw_name="RTX4090x1"
            gpu_name=rtx_4090
            docker_string=" --docker"
          fi
          category="datacenter,edge"
          if [ -f "gh_action/bin/deactivate" ]; then source gh_action/bin/deactivate; fi
          python3 -m venv gh_action
          source gh_action/bin/activate
          export MLC_REPOS=$HOME/GH_MLC
          pip install --upgrade mlcflow
          mlc pull repo mlcommons@mlperf-automations --branch=dev
          
          mlcr --tags=run-mlperf,inference,_all-scenarios,_submission,_full,_r5.0-dev --preprocess_submission=yes --pull_changes=yes --pull_inference_changes=yes --execution_mode=valid --gpu_name=$gpu_name --pull_changes=yes --pull_inference_changes=yes --model=${{ matrix.model }} --submitter="MLCommons" --hw_name=$hw_name --implementation=nvidia --backend=tensorrt --category=$category --division=closed  --docker_dt --docker_mlc_repo=mlcommons@mlperf-automations --docker_mlc_repo_branch=dev --adr.compiler.tags=gcc --device=cuda --use_model_from_host=yes --use_dataset_from_host=yes --results_dir=$HOME/gh_action_results --submission_dir=$HOME/gh_action_submissions --clean  $docker_string --quiet

          mlcr --tags=push,github,mlperf,inference,submission --repo_url=https://github.com/mlcommons/mlperf_inference_unofficial_submissions_v5.0 --repo_branch=auto-update --commit_message="Results from GH action on NVIDIA_$hw_name" --quiet --submission_dir=$HOME/gh_action_submissions --hw_name=$hw_name
