alias: get-mlperf-inference-nvidia-scratch-space
uid: 0b2bec8b29fb4ab7
automation_alias: script
automation_uid: 5b4e0237da074764

# Metadata
category: MLPerf Inference
tags:
- get
- mlperf
- inference
- nvidia
- scratch
- space

# Cache
cache: true

# Environment
new_env_keys:
- MLC_NVIDIA_MLPERF_SCRATCH_PATH
- MLPERF_SCRATCH_PATH
- MLC_NVIDIA_SCRATCH_SPACE_VERSION
new_state_keys: []

# Input mapping
input_mapping:
  scratch_path: MLC_NVIDIA_MLPERF_SCRATCH_PATH
input_description: {}

# Dependencies
deps: []
prehook_deps: []
posthook_deps: []
post_deps: []

# Variations
variations:
  version.#:
    env:
      MLC_NVIDIA_SCRATCH_SPACE_VERSION: '#'
    group: version
  version.4_0:
    env:
      MLC_NVIDIA_SCRATCH_SPACE_VERSION: '4_0'
    group: version
  version.4_1:
    env:
      MLC_NVIDIA_SCRATCH_SPACE_VERSION: '4_1'
    group: version
  version.4_1-dev:
    env:
      MLC_NVIDIA_SCRATCH_SPACE_VERSION: 4_1-dev
    group: version
  version.5_0-dev:
    default: true
    env:
      MLC_NVIDIA_SCRATCH_SPACE_VERSION: 5_0-dev
    group: version

# Versions
versions: {}

# Docker / container
docker:
  run: false
