alias: get-lib-aocl
uid: b2a16ffc30a0467c
automation_alias: script
automation_uid: 5b4e0237da074764

# Metadata
category: Detection or installation of tools and artifacts
tags:
- get
- lib
- lib-aocl
- aocl
- aocl-all

# Cache
cache: false

# Dependencies
deps:
- tags: get,utils,aocl-utils
  force_env_keys:
  - MLC_OUTDIRNAME
- tags: get,lib,aocl-libm
  force_env_keys:
  - MLC_OUTDIRNAME
- tags: get,lib,aocl-blis
  force_env_keys:
  - MLC_OUTDIRNAME
- tags: get,lib,aocl-libflame
  force_env_keys:
  - MLC_OUTDIRNAME
- tags: get,lib,aocl-sparse
  force_env_keys:
  - MLC_OUTDIRNAME
- tags: get,lib,aocl-compression
  force_env_keys:
  - MLC_OUTDIRNAME
- tags: get,lib,aocl-crypto
  force_env_keys:
  - MLC_OUTDIRNAME
- tags: get,lib,aocl-data-analytics
  force_env_keys:
  - MLC_OUTDIRNAME
- tags: get,lib,aocl-dlp
  force_env_keys:
  - MLC_OUTDIRNAME
- tags: get,lib,aocl-fftz
  force_env_keys:
  - MLC_OUTDIRNAME
- tags: get,lib,aocl-scalapack
  force_env_keys:
  - MLC_OUTDIRNAME

# Tests
tests:
  run_inputs:
  - variations_list: []
